### ISSUE TITLE
Calling Entity#remove on entities in EntityAddToWorldEvent Results in Error

### ISSUE THREAD

**Issue by partydev** [PaperSpigot/Paper#8490] opened 2022-10-22 02:40 UTC
### Expected behavior

Being able to call Entity#remove without error.

### Observed/Actual behavior

Calling Entity#remove leads to the following error:

https://gist.github.com/partydev/4556808b9f8747850d1dc3e90abcc1d8

The entity is still removed.

### Steps/models to reproduce

Run the following code:
```java
    @EventHandler
    public void onVillagerLoad(EntityAddToWorldEvent event) {
        event.getEntity().remove();
    }
```

### Plugin and Datapack List

Only plugin utilized was a plugin created to reproduce this bug.

### Paper version

Paper-220

**Comment by lynxplay** [comment] 2022-10-22 14:25
Duplicate of #8400 and hence also of #6451.
In general, the chunk rewrite currently calls the events EntityAdd/Remove, ChunkLoad/Unload and EntitiesLoad/Unload at times that does not allow modifications like that.

Sorry for the inconvenience.

**Closed as not planned by lynxplay** 2022-10-22 14:25 UTC
Labels: type: bug, resolution: duplicate
