### ISSUE TITLE
MapLike Errors updating from 1.16.5 -> 1.17.1

### ISSUE THREAD

**Issue by andrewkm** [PaperSpigot/Paper#6660] opened 2021-09-25 16:54 UTC
### Expected behavior

N/A

### Observed/Actual behavior

https://pastebin.com/raw/HXWmEJ4K

### Steps/models to reproduce

Update from Paper 1.16.5 Build 788 -> Paper 1.17.1 Build 278
Affected map included here: https://easyupload.io/fml3sr

### Plugin list

On Request. (andrewkm # 0001)

### Paper version

Paper 1.17.1 Build 278

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

Related:
https://bugs.mojang.com/browse/MC-197883
https://bugs.mojang.com/browse/MC-199174
Paper: https://github.com/PaperMC/Paper/issues/4236

PS: I've tried to use --forceUpgrade as well to no avail.
This happens on every restart, not a one time thing.

**Comment by Prof-Bloodstone** [comment] 2021-09-25 18:18
Reported many, many times before. Please search the issue tracker.
Duplicate of #5988 #5873 #5887 #5972 and many more.
Vanilla bug: https://bugs.mojang.com/browse/MC-227945

**Closed as completed by Prof-Bloodstone** 2021-09-25 18:18 UTC
Labels: upstream: vanilla
