### ISSUE TITLE
Cannot Hide Default Item Attributes Using HIDE_ATTRIBUTES Without AttributeModifier

### ISSUE THREAD

**Issue by BingYanchi** [PaperSpigot/Paper#11143] opened 2024-07-21 22:09 UTC
### Expected behavior

/give @s iron_sword{AttributeModifiers:[{Modifiers:[],ShowInTooltip:false}]}

Corresponding data: "minecraft:AttributeModifiers": {ShowInTooltip: 0b, Modifiers: []}

### Observed/Actual behavior

not work

### Steps/models to reproduce

```java
ItemStack itemStack = new ItemStack(Material.IRON_SWORD);
ItemMeta itemMeta = itemStack.getItemMeta();
itemMeta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
itemStack.setItemMeta(itemMeta);
Player player = (Player) sender;
player.getInventory().addItem(itemStack);
```

### Plugin and Datapack List

my plugin

### Paper version

This server is running Paper version 1.21-107-master@aa36ae6 (2024-07-21T10:39:28Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Other

**This issue cannot be reproduced in the latest Spigot, but exists in the latest Paper.**

**Comment by electronicboy** [comment] 2024-07-21 22:20
Duplicate of #10693
This works as intended, spigot blindly adds an empty attributes list to items which changed the behaviour, we do not consider this to be expected behaviour, and for cases where it doesn't matter, i.e. UIs, you can add a dummy attribute to appease it

**Closed as not planned by electronicboy** 2024-07-21 22:20 UTC
Labels: type: bug, version: 1.21
