### ISSUE TITLE
Players sometimes hit invisible wall and die when moving fast with Elytra gliding + Riptide 3 Trident

### ISSUE THREAD

**Issue by kaxonomy** [PaperSpigot/Paper#7765] opened 2022-04-25 02:53 UTC
### Expected behavior

I expect the server to slow the player down and not deal FLY_INTO_WALL damage.

### Observed/Actual behavior

Player will occasionally hit the end of the loaded chunks and take lethal damage.

### Steps/models to reproduce

1. Wear an Elytra and hold a Riptide 3 Trident in your hand
2. Use /weather rain
3. Begin gliding and then spam Riptide at a high Y level free of obstructions
4. Sometimes hitting the chunk borders will slow you down, but other times you will take lethal damage instead

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-311 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: d70ac03)
You are running the latest version
Previous version: git-Paper-267 (MC: 1.18.2)

**Comment by kennytv** [comment] 2022-04-25 07:40
Duplicate of https://github.com/PaperMC/Paper/issues/7412

**Closed as completed by kennytv** 2022-04-25 07:40 UTC
Labels: type: bug, resolution: duplicate
