### ISSUE TITLE
New server world wont generate on latest build (cd9fe9c)

### ISSUE THREAD

**Issue by LittleBigBug** [PaperSpigot/Paper#6972] opened 2021-12-01 02:43 UTC
### Stack trace

```
[20:33:50 INFO]: Starting Minecraft server on *:25565
[20:33:50 INFO]: Using epoll channel type
[20:33:50 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[20:33:50 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[20:33:50 INFO]: Preparing level "world"
[20:33:53 FATAL]: Failed to schedule load callback for chunk [0, 0]
java.util.concurrent.CompletionException: java.lang.IllegalAccessError: failed to access class net.minecraft.world.level.levelgen.SurfaceRules$i from class net.minecraft.data.worldgen.SurfaceRuleData$PaperBedrockConditionSource$1VerticalGradientCondition (net.minecraft.world.level.levelgen.SurfaceRules$i and net.minecraft.data.worldgen.SurfaceRuleData$PaperBedrockConditionSource$1VerticalGradientCondition are in unnamed module of loader java.net.URLClassLoader @484b61fc)
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[?:?]
at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[?:?]
at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[?:?]
at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalAccessError: failed to access class net.minecraft.world.level.levelgen.SurfaceRules$i from class net.minecraft.data.worldgen.SurfaceRuleData$PaperBedrockConditionSource$1VerticalGradientCondition (net.minecraft.world.level.levelgen.SurfaceRules$i and net.minecraft.data.worldgen.SurfaceRuleData$PaperBedrockConditionSource$1VerticalGradientCondition are in unnamed module of loader java.net.URLClassLoader @484b61fc)
at net.minecraft.data.worldgen.SurfaceRuleData$PaperBedrockConditionSource$1VerticalGradientCondition.a(SurfaceRuleData.java:83) ~[paper-1.18.jar:git-Paper-14]
at net.minecraft.world.level.levelgen.SurfaceRules$LazyCondition.test(SurfaceRules.java:240) ~[?:?]
at net.minecraft.world.level.levelgen.SurfaceRules$TestRule.tryApply(SurfaceRules.java:365) ~[?:?]
at net.minecraft.world.level.levelgen.SurfaceRules$SequenceRule.tryApply(SurfaceRules.java:377) ~[?:?]
at net.minecraft.world.level.levelgen.SurfaceSystem.buildSurface(SurfaceSystem.java:197) ~[paper-1.18.jar:git-Paper-14]
at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.buildSurface(NoiseBasedChunkGenerator.java:240) ~[?:?]
at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:125) ~[paper-1.18.jar:git-Paper-14]
at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus.java:342) ~[?:?]
at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:273) ~[paper-1.18.jar:git-Paper-14]
at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$35(ChunkMap.java:1245) ~[paper-1.18.jar:git-Paper-14]
at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.18.jar:?]
at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$37(ChunkMap.java:1243) ~[paper-1.18.jar:git-Paper-14]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
... 8 more
```

There were 2 stacks after this that i forgot to save and log if you need it i can run it thru again

### Plugin and Datapack List

None

### Actions to reproduce (if known)

From a fresh start, download build 14 (cd9fe9c) Link to download [Here](https://papermc.io/api/v2/projects/paper/versions/1.18/builds/14/downloads/paper-1.18-14.jar)

### Paper version

cd9fe9c build 14

**Comment by Machine-Maker** [comment] 2021-12-01 02:44
Duplicate of #6969

Fixed in build 15

**Comment by LittleBigBug** [comment] 2021-12-01 02:44
Thanks, I'm sorry I didnt see that issue since it closed

**Closed as completed by Machine-Maker** 2021-12-01 02:44 UTC
Labels: resolution: duplicate
