### ISSUE TITLE
Enchants showing up wrong in enchanting table

### ISSUE THREAD

**Issue by MrLouisDew** [PaperSpigot/Paper#11022] opened 2024-07-05 21:55 UTC
### Expected behavior

Enchantments showing up that fit the given item.

### Observed/Actual behavior

Enchantments showing up that do NOT fit the tool. As you can see in the picture, I gave the enchanting table a diamond pickaxe.
When looking at the possible enchants, I got to see Depth Strider I, Depth Strider II and Depth Strider IV.
![image](https://github.com/PaperMC/Paper/assets/70475924/a8ec4394-7980-469a-8456-69a337b614ad)
But when actually enchanting the diamond pickaxe, it does get enchanted with enchants that fit the tool.
![image](https://github.com/PaperMC/Paper/assets/70475924/05ceb092-f922-4462-b6e5-a421925b5875)
I also tested some other tools, weapons and armor, they all seem to work **incorrectly**.

### Steps/models to reproduce

1. Download: Paper version 1.21-44-master@8d91b85
2. Start server.
3. Take tools/armour/other weapons, put them in an enchanting table.

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/70475924/fca8a48a-422a-49aa-bf28-4a6053630e6d)
No datapacks.

### Paper version

version
[21:54:04 INFO]: This server is running Paper version 1.21-44-master@8d91b85 (2024-07-04T18:56:20Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-497 (MC: 1.20.4)

**Comment by Readopted** [comment] 2024-07-05 21:55
I forgot to add, I do not run any datapacks.

**Comment by Malfrador** [comment] 2024-07-05 22:34
I am unable to reproduce this issue on Paper 1.21-44 on a fresh server with the steps you provided. Only the enchantments actually supported by the item are showing up.

Are you using an unmodified 1.21 client? It being only a display issue in the enchantment GUI but not affecting the actual item result makes me suspect some protocol translation issue (e.g. ViaVersion, a proxy like Velocity, a modded client etc). 
Or did you have plugins or datapacks previously installed?

**Comment by Readopted** [comment] 2024-07-06 01:01
Hello
While I was testing this I was using an unmodified 1.21 client.
I’m using a Velocity proxy alongside ViaVersion.
I did have plugins installed but removed them all to test this issue. 
These are the plugins that I previously had on this server: 
![IMG_1846](https://github.com/PaperMC/Paper/assets/70475924/c4a813b7-60b8-4815-8b1b-4d69e173f5fc)

**Comment by lynxplay** [comment] 2024-07-06 20:00
I can also not replicate this on a plain paper server.
Without further replication steps, I'll have to close this issue.

If you find replication steps with a plugin-less velocity and a plugin-less paper server, feel free to post them here, I'll reopen the issue then.

**Closed as not planned by lynxplay** 2024-07-06 20:00 UTC
Labels: type: bug, resolution: cannot reproduce, version: 1.21

**Comment by Billybobertjoe** [comment] 2024-07-19 17:41
I'm getting this issue whenever I join on a client running an older Minecraft version (server:1.21 Client:1.20.6) Which is really annoying because some mods people use don't support the newest version

**Comment by electronicboy** [comment] 2024-07-19 17:55
we do not support protocol hacks and have 0 control over the behavioral issues that they induce
