### ISSUE TITLE
Pistons does not work correctly under alternate-current redstone system

### ISSUE THREAD

**Issue by siulung201314** [PaperSpigot/Paper#7852] opened 2022-05-27 20:40 UTC
### Expected behavior

Piston retracts when there is no redstone signal from redstone dust.

### Observed/Actual behavior

Piston cannot retract when there is no redstone signal from redstone dust.

### Steps/models to reproduce

1. Build what the photos show.
2. Turn on the lever. The piston extends
3. Turn off the lever. The piston does not retract.

![image](https://user-images.githubusercontent.com/83176041/170785195-d03187a1-6844-486e-80ed-ab0fe82ab51b.png)
![image](https://user-images.githubusercontent.com/83176041/170785210-10ac8590-ce20-44bb-8298-47b6bc2533eb.png)

### Plugin and Datapack List

without any plugins

### Paper version

This server is running Paper version git-Paper-350 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 3f7fbe3)
You are running the latest version
Previous version: git-Purpur-1628 (MC: 1.18.2)

### Other

1. (Using eigencraft), there is no any bug about piston.

2. (Using alternate-current) I place a block near the extended piston without redstone signal, the piston will then retract.
![image](https://user-images.githubusercontent.com/83176041/170786471-13d54df5-6ddf-4332-a394-c5fd099de16a.png)
![image](https://user-images.githubusercontent.com/83176041/170786510-c3a947c3-7468-46e0-892c-03fe5a422b8a.png)

2. (Using alternate-current) If two pistons stick together, they can retract without redstone signal.
![image](https://user-images.githubusercontent.com/83176041/170785566-f94dfaf7-93b4-4634-9fe8-cce8cc535cd8.png)
![image](https://user-images.githubusercontent.com/83176041/170785582-027c68da-80bb-4ec9-8b6a-d89ddaae20ba.png)

3. (Using alternate-current) If the end of the redstone wire is on the block above the piston, piston can retract without redstone signal.
![image](https://user-images.githubusercontent.com/83176041/170790703-d372bbfa-265d-41dc-be6c-e6ce164734a5.png)
![image](https://user-images.githubusercontent.com/83176041/170790724-01249b1e-55cd-4deb-8bed-99ca5b57df78.png)

4. (Using alternate-current) Replace the piston with a redstone lamp, the redstone lamp can be inactive without redstone signal.

**Comment by molor** [comment] 2022-05-27 21:03
(maybe duplicate of https://github.com/PaperMC/Paper/issues/7725?)

**Comment by siulung201314** [comment] 2022-05-27 21:35
> (maybe duplicate of #7725?)

In my case, I have also tested in Vanilla.
The piston can retract when there is no redstone signal in same structure.

**Comment by SpaceWalkerRS** [comment] 2022-05-29 19:00
Thank you for the issue report. This issue is indeed very similar to #7725. My comment there explains it in more depth, but in short: redstone was not really designed with quasi-connectivity (QC) in mind, so sometimes redstone components do provide power to a piston, but are too far away from that piston to update it, leaving it in an invalid state (either extended when it should be retracted or vice versa). That is the case here as well. The two wires diagonally above the piston do power that piston, but do not update it. 

Of course, in this case there is still a wire directly above the piston as well, which does update it. So depending on the order in which these wires depower and update neighboring blocks, the piston could get stuck extended, or not. In Vanilla, this order is location-dependent.

But as it turns out you managed to find a setup that behaves consistently even in Vanilla. But it is *extremely* sensitive. Any small changes (e.g. making the wire line 1 block longer or shorter, or providing power at a different place along the wire line, or changing the signal strength) could make the setup locational (i.e. there would be some locations where the piston gets stuck extended, and others where it would not).

With Alternate Current, the wires furthest away from a power source update last, which means this setup would always leave the piston stuck extended, regardless of location/orientation. This is because the last wire to depower does provide power to the piston, but does not update it.

Issues like this are extremely tricky to fix, since they are so closely related to the location-dependent update order of redstone dust in Vanilla. Solving one issue might create two more elsewhere. Having said that, I can see a few possible solutions that might solve more issues than they create:
- Provide block updates in a larger range around redstone wires. I'm personally not too fond of this idea, as it is not very consistent with other redstone components in the game. It also removes any possibility to use redstone dust to put a piston in an invalid state through QC-powering. I think the real issue in your setup is that the piston *is* updated, but at the wrong time.
- Incorporate block updates to neighboring blocks into the power queue. This could be done in such a way that the last wire depowers before the piston is updated. I'm not yet sure how this should work, but I think it is possible...

I will explore these options further and hopefully I'll be able to resolve this issue.

**Closed as completed** 2022-06-14 09:41 UTC
Labels: type: bug, status: accepted, priority: low
