### ISSUE TITLE
Netty Epoll Server IO Error

### ISSUE THREAD

**Issue by derech1e** [PaperSpigot/Paper#8402] opened 2022-09-28 13:57 UTC
### Stack trace

https://paste.gg/p/anonymous/487326e544284a768bd384607960ccde

### Plugin and Datapack List

No plugins or Datapacks

### Actions to reproduce (if known)

I have no exact idea what the error was trying to do. It only appeared after upgrading from build #153 to build #177.

### Paper version

```
> version
[13:54:32 INFO]: Checking version, please wait...
[13:54:32 INFO]: This server is running Paper version git-Paper-177 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 1bbd273)
You are running the latest version
Previous version: git-Paper-153 (MC: 1.19.2)
```

### Other

The server is automatically restarted at 3 am by a script outside the server. This script sends the "stop" command to the screen beforehand; waits 60 seconds and then restarts the server.

**Comment by electronicboy** [comment] 2022-09-28 14:00
Need to see the full log

**Comment by derech1e** [comment] 2022-09-28 15:01
> Need to see the full log

https://paste.gg/p/anonymous/016d0e7ff5bb4384a9998f8a25cc0d20

**Comment by electronicboy** [comment] 2022-09-29 12:08
So, basically, something induced a state desync, idk if this jar will cover the needed spots, otherwise, we'd need to find a minimal way to reproduce this, mind providing a log from this jar?

https://cdn.discordapp.com/attachments/925530366192779286/1025016018147483689/paper-paperclip-1.19.2-R0.1-SNAPSHOT-reobf.jar

**Comment by derech1e** [comment] 2022-09-29 16:40
I don't think I'll be able to reproduce this error. I just ran into it and reported the error because of the strange exception message.
It might be worth considering closing this issue if more errors of this kind don't occur.

Here is the full log of your jar: https://paste.gg/p/anonymous/e100b7a0666c493f937ccc1ba967ca7f

**Comment by derech1e** [comment] 2022-09-29 19:33
Is this error somehow critical for saving the world?

**Comment by electronicboy** [comment] 2022-09-29 19:35
No, that won't impact saving the world; That generally just looks like somebody was logging into the server, and something caused the connection to be shoved into the wrong state

**Comment by lynxplay** [comment] 2022-10-01 11:17
Concerning we don't seem to be able to dig deeper into this as you cannot replicate it, I'll take you up on your suggestion and close this issue :+1: Hopefully if this happens again, we find better replication steps or at least an environment that consistently produces this error so cats modified jar can give us a deeper look behind the curtains.

Thanks for the report anyway, I'll keep my eyes open for similar issues in the future :+1:

**Closed as not planned by lynxplay** 2022-10-01 11:17 UTC
Labels: resolution: cannot reproduce, version: 1.19.2

**Comment by yzz17** [comment] 2023-06-27 16:55
1.20.1-R0.1-SNAPSHOT

https://paste.gg/p/anonymous/929791af62a74d52aeb59822cf24f325

somehow it is related to the "online mode", if it is set to "false" the error appears
EssentialsX-2.20.1-dev+17-03ed9a5,  when doing the test to remove it... the error still appears, but the constant was the offline mode= false in server properties, greetings from Mexico :D

**Comment by MiniDigger** [comment] 2023-06-28 09:42
> This issue was closed 9 months ago. Please consider opening a [new issue](https://github.com/PaperMC/Paper/issues/new/choose) instead of leaving a comment here.

please read what github is saying and open a new issue with new reproduction settings
