### ISSUE TITLE
Weird Error on disconnect

### ISSUE THREAD

**Issue by gamelamp** [PaperSpigot/Paper#10824] opened 2024-05-29 17:53 UTC
### Stack trace

```
https://paste.gg/p/anonymous/56942441b7fa4a25817c9c275b2d6bc2
```

### Plugin and Datapack List

terralith DP
chunky
chunky border
bluemap

### Actions to reproduce (if known)

just disconnect from the server

### Paper version

"This server is running Paper version 1.20.6-115-master@9d6f2cc (2024-05-28T14:55:16Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)"

### Other

The server doesn't crash or anything, but I don't understand why it is throwing this error

**Comment by Warriorrrr** [comment] 2024-05-29 18:47
Duplicate of #10662

**Closed as not planned by Warriorrrr** 2024-05-29 18:47 UTC
Labels: resolution: duplicate, version: 1.20.6
