### ISSUE TITLE
Lights cant be destroyed in survival mode

### ISSUE THREAD

**Issue by Tackoozle** [PaperSpigot/Paper#11252] opened 2024-08-12 18:10 UTC
### Expected behavior

Lightblocks can be "overwritten" and destroyed when placing a block on it.

### Observed/Actual behavior

You cant place a block on it. There is no message. In creative it is working.

### Steps/models to reproduce

Create a server with paper, place some lightblocks, go to survivalmode, try to place some blocks at the lights position.

### Plugin and Datapack List

-

### Paper version

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API versi|
on 1.21-R0.1-SNAPSHOT)                                                                                                      |
You are running the latest version
Previous version: 1.21-127-4e6a2a1 (MC: 1.21)

### Other

It is working in vanilla minecraft.

**Comment by electronicboy** [comment] 2024-08-12 18:13
https://github.com/PaperMC/Paper/pull/6601

**Comment by Tackoozle** [comment] 2024-08-12 18:33
Well okay... In vanilla minecraft it is working, and with just paper installed they cant be replaced. Also im pretty sure this was working in 1.20

**Comment by Malfrador** [comment] 2024-08-16 00:00
Caused by https://github.com/PaperMC/paper/commit/2773dc484735a8ba9cd83354c76e733454f332d5

**Comment by Abelkrijgtalles** [comment] 2024-08-16 11:16
This should be a simple fix by just removing it from isDestroyable(), right?

**Comment by Abelkrijgtalles** [comment] 2024-08-16 21:48
This issue can be closed as it is fixed in #11275, which is merged

**Closed as completed** 2024-08-16 21:51 UTC
Labels: type: bug, status: accepted
