### ISSUE TITLE
Server JAR missing reference to com.mojang.serialization.Keyable

### ISSUE THREAD

**Issue by njsharpe** [PaperSpigot/Paper#9085] opened 2023-04-02 20:31 UTC
### Expected behavior

A successfully compiled & jarred plugin via gradle.

### Observed/Actual behavior

"Error: Cannot access Keyable ... class file for com.mojang.serialization.Keyable not found"

### Steps/models to reproduce

1. Clone latest from PaperMC/Paper on master
2. `gradlew applyPatches`
3. `gradlew createMojmapBundlerJar`
4. `gradlew createMojmapPaperclipJar`
5. `gradlew publishToMavenLocal`
6. Validate maven local by checking `~\.m2\repository\io\papermc\paper`. Should find the following folders: `paper-api`, `paper-server`, `paper-mojangapi`. Apply fix to `paper-server`, incorrectly named jar file `paper-server-<ver>-<rev>-SNAPSHOT-mojang-mapped.jar` -> `paper-server-<ver>-<rev>-SNAPSHOT.jar`
7. Load all into plugin with as gradle dependencies. Include remote repository for `paper-api` (for external dependencies like `bungeecord-chat`).
8. Include code below into the project.
9. `gradlew jar`

Code snippet that produced the error:
```java
@Override
public void onEnable() {
    DefaultedRegistry<Potion> repository = BuiltInRegistries.POTION;
    Optional<Potion> optional = registry.getOptional(ResourceLocation.tryParse("minecraft:long_fire_resistance"));
}
```

Errors out when attempting `Registry#getOptional(ResourceLocation)` since `Registry<T>` implements `Keyable`, which is not included in the `paper-server` dependency, where it should be. I believe this is unintended behavior.

### Plugin and Datapack List

N/A

### Paper version

[16:27:56 INFO]: Checking version, please wait...
[16:27:57 INFO]: This server is running Paper version git-Paper-"9893e2b" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9893e2b)
You are running the latest version
Previous version: git-Folia-"ed7a5c5" (MC: 1.19.4)

**Comment by Machine-Maker** [comment] 2023-04-02 20:51
> which is not included in the paper-server dependency, where it should be. I believe this is unintended behavior.

This is 100% intended behavior the paper-server dependency does not include all the other libraries that are bundled with the server jar provided by mojang.

**Comment by Machine-Maker** [comment] 2023-04-02 20:58
Closing as WAI for now. The only supported way of accessing server internals is with the [paperweight gradle plugin](https://github.com/PaperMC/paperweight).

**Closed as not planned by Machine-Maker** 2023-04-02 20:58 UTC
Labels: type: bug, resolution: works as intended
