### ISSUE TITLE
Grass blocks still turn snowy even though PlayerBucketEmptyEvent is cancelled with Powder Snow Bucket

### ISSUE THREAD

**Issue by lerokko** [PaperSpigot/Paper#7003] opened 2021-12-03 10:20 UTC
### Expected behavior

If the place event is being cancelled the grass should not be affected. The Grass block is in an invalid state. It should only be snowy if it has snow on top.

### Observed/Actual behavior

The grass blocks gets the snowy texture. This is server side.

### Steps/models to reproduce

Install latest version of griefprevention on paper.
Make a claim
Have another player without trust place a powder snow bucket on a grass block inside the claim
Observe

### Plugin and Datapack List

GriefPrevention version 16.17.1-2b69191
Luckperms latest

### Paper version

git-Paper-10 (MC: 1.18)
(can't test 24 rn)

### Other

I am not an expert at all I was just told this via: https://github.com/TechFortress/GriefPrevention/issues/1684#issuecomment-985195029
They said its a spigot bug, but I'm not running spigot. I do not wanna get my ass whopped on Spigot bug tracker so I figured I should mention this here first.

**Comment by aurorasmiles** [comment] 2021-12-03 10:22
Duplicate of #6630

**Closed as completed by aurorasmiles** 2021-12-03 10:22 UTC
Labels: type: bug, resolution: duplicate, version: 1.18
