### ISSUE TITLE
People can't respawn when they die. Packet problem.

### ISSUE THREAD

**Issue by PentoHub** [PaperSpigot/Paper#11038] opened 2024-07-07 22:03 UTC
### Expected behavior

When a player dies I expect them to be able to click respawn and then respawn at their bed or at an essentials (the plugin) home.

### Observed/Actual behavior

When a player dies, he or she cannot click respawn. They will not respawn and it will just bug, the button may appear clicked and you will get teleported somewhere but that's just void, you can't do anything unless you relog. Upon rejoining the server you get placed near your bed or home but only if you wait a few seconds before rejoining. If you rejoin too fast you'll simply spawn in this void again. During the entire time you're there and even a few seconds after you log out the player remains in the player list you can see when holding 'tab'.  The bug isn't unplayable as you can see, we've managed up until now just by relogging, it's just very annoying having to rejoin all the time.

### Steps/models to reproduce

Simply die in Minecraft, how this happens doesn't matter.

### Plugin and Datapack List

Pluginlist: Essentials & Core Protect
Datapacks: Silk Spawners V1.2 by [ThePatriotsCommandXS](https://modrinth.com/user/ThePatriotsCommandXS)

### Paper version

1.21 Build 44 and today updated to Build 47 (the latest one Shockbyte offers) but the issue remains.
/version output: This server is running Paper version 1.21-42-master@b89e6a0 (2024-07-04T10:58:08Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Other

The problem is unlikely to come from a plugin or datapack, we've removed all of these and tried running the server without anything and the issue remains, we have no clue what could be causing this and have plowed through the logs many times. 
We haven't changed anything in the server config or plugin config that could cause this either.
This is a message our server console gives us (host: Shockbyte). 
We've also opened a ticket over at Shockbyte and they couldn't help us but refer us to here.
![image_2024-07-06_143208615](https://github.com/PaperMC/Paper/assets/81916916/a7178537-14ed-4950-ad5d-09e7ac15c904)

**Comment by lynxplay** [comment] 2024-07-07 22:06
Duplicate of #11017

Can you actually try with latest paper please.

**Comment by PentoHub** [comment] 2024-07-07 22:09
Is build 47 not the latest build?

**Comment by lynxplay** [comment] 2024-07-07 22:10
It is but the stacktrace you provided is from build 42. We'd need a stacktrace from build 47.

**Comment by PentoHub** [comment] 2024-07-07 22:13
I can see now that in the console it does say build 42, that is weird because we had selected build 44 at that point, at this point the server is running build 47 but it still says 42 in the console. My apologies, I will have to open a ticket over at Shockbyte then since it is clearly already been noticed and fixed in Paper itself. Weird cuz the server doesn't update even when the paper.jar in the settings is correctly updated.
Thanks for the help.

**Comment by lynxplay** [comment] 2024-07-07 22:15
Okay! I'll close this for now then :) if you do replicate this on latest build, post your findings here and someone will reopen the issue!

**Closed as not planned by lynxplay** 2024-07-07 22:15 UTC
Labels: type: bug, resolution: duplicate, version: 1.21
