### ISSUE TITLE
ItemFlag.HIDE_ATTRIBUTES is removed when i set the item on inventory

### ISSUE THREAD

**Issue by orjacob555** [PaperSpigot/Paper#10693] opened 2024-05-11 14:37 UTC
### Expected behavior

i create a item with ItemFlag.HIDE_ATTRIBUTES and i expect to not see the the item attributes.

### Observed/Actual behavior

Instead i still see them.
i print the item that i save as public object and the item that is in the inventory and i could see the ItemFlag.HIDE_ATTRIBUTES not longer exists.

Console:
[17:34:25 INFO]: ItemStack{BARRIER x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name="Reset Effect", ItemFlags=[HIDE_ATTRIBUTES, HIDE_UNBREAKABLE], Unbreakable=true}}

[17:34:25 INFO]: ItemStack{BARRIER x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name="Reset Effect", ItemFlags=[HIDE_UNBREAKABLE], Unbreakable=true}}

### Steps/models to reproduce

public final static ItemStack resetEffect = createItem("Reset Effect", Material.BARRIER);

public static ItemStack createItem(String name, Material material) {
        return setMeta(new ItemStack(material), name, true, null);
}

  public static ItemStack setMeta(ItemStack itemStack, String name, boolean unbreakable, String[] lore) {
        
        ItemMeta itemMeta = itemStack.getItemMeta();
        itemMeta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        
        if (!name.isEmpty()) {
            itemMeta.displayName(getText(name));
        }

        if (unbreakable) {
            itemMeta.setUnbreakable(true);
            itemMeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        }

        if (lore != null) {

            ArrayList<Component> components = new ArrayList<>();
            for (String string : lore) {
                components.add(getText(string));
            }

            itemMeta.lore(components);
        }
        itemStack.setItemMeta(itemMeta);
        return itemStack;
    }

@EventHandler
    private void invClick(InventoryClickEvent event) {

        System.out.println(itemStack.equals(resetEffect));
        System.out.println(resetEffect);
        System.out.println(itemStack);
}

### Plugin and Datapack List

my custom plugin

### Paper version

Paper 1.20.6 #62

**Comment by Machine-Maker** [comment] 2024-05-11 14:43
Closing as "Works as Intended". The HIDE_ATTRIBUTES flag no longer can just be set without also specifying some attributes to hide. They are stored in the same data component and so you can't set one without setting some info about the other.

**Closed as not planned by Machine-Maker** 2024-05-11 14:43 UTC
Labels: type: bug, resolution: works as intended, version: 1.20.6

**Comment by lynxplay** [comment] 2024-05-24 18:38
which is also garbage, Becasue now the itemstack itself has to track its default attribute modifiers instead of pulling it from the prototype.
That would just be screaming for items to end up with incorrect attribute modifiers down the line.

The real solution here is to kindly ask mojang for a way to decouple this, beyond that not much to do that isn'T going to break down the line.

**Comment by Machine-Maker** [comment] 2024-05-24 19:57
> Right now, the only way to hide the tooltip of tools/weapons/armor is by adding a fake attribute modifier (i.e. on the GENERIC_ARMOR_TOUGHNESS attribute, put a 0 ADD_SCALAR attribute modifier) and then the ItemFlag.HIDE_ATTRIBUTES flag.

To be clear, when you do this, you are also **removing** any implicit modifiers that item type may have. If you do this to a tool, you are removing the attributes that would be default on that item type.

**Comment by SkytAsul** [comment] 2024-05-25 08:53
> To be clear, when you do this, you are also **removing** any implicit modifiers that item type may have. If you do this to a tool, you are removing the attributes that would be default on that item type.
Okay thank you for the clarification, I didn't know it works like that.
Isn't it possible to fetch the "default" attributes for the items in the `applyModifiers` method and add the `show_in_tooltip` component to it?

**Comment by lynxplay** [comment] 2024-05-25 08:57
Yea you could, but then you defined the default attributes specifically on the item stack, not the item (or material in the Bukkit world). This has the terrible side effect that any changes by Mojang or whoever down the line to the default attributes are no longer reflected.

If you copy the 1.20.6 default attributes of a diamond sword to apply them again but with show tooltip false, Mojang or a datapack change those values in a future version, now all of your created diamond swords are having wrong defaults and there is nothing paper can do about it.

**Comment by Machine-Maker** [comment] 2024-05-25 15:34
I've [created this issue](https://bugs.mojang.com/browse/MC-272008) on the mojang bug tracker, since this can kinda be considered a bug rather than a feature because of the inability to have future default modifier changes reflected.

**Comment by codeHusky** [comment] 2024-08-02 06:36
Mojang has marked that bug on their bug tracker as "invalid" - is this still something Paper doesn't want in their API? It seems Mojang has no interest in "fixing" this behavior and the current API is straight up broken. 

If Paper doesn't want the HIDE_ATTRIBUTES flag to do what it's done for several years anymore, the docs need to be changed from just "Setting to show/hide Attributes like Damage" and deprecate the flag. I would be far more in favor of just maintaining the old functionality and not breaking plugins since Mojang seems to believe that adding the empty list is the correct way.

**Comment by Machine-Maker** [comment] 2024-08-02 07:04
There is no "maintaining the old functionality". Maintaining the old function is impossible to do. Adding `meta.setAttributeModifiers(MultimapBuilder.hashKeys().hashSetValues().build())` is not always the correct solution. That will remove any implicit modifiers on non-armor items. That will then change functionality of the non-armor item. That is what upstream is currently doing to try and "fix" the issue, which then just breaks lots of items in the mean time removing the default/implicit modifiers for that item type.

**Comment by kangarko** [comment] 2024-09-22 06:43
Paper is really confusing here, the best for the customer/developer would be to make the flag work as it did before, end of conversation. I understand it's not as simple, but I don't like the overall increase of complexity where we're going.

**Comment by electronicboy** [comment] 2024-09-22 07:19
except it cannot work as it did before because Mojang changed the behaviour of how this works. I'm not really sure what you'd expect us to do to pull that off without breaking the behaviour of items like Spigot does, just because that's acceptable in one use case area for that doesn't mean it's something we can blindly apply to all items.

**Comment by codeHusky** [comment] 2024-09-22 09:06
the only real "solution" for this is essentially inserting a hack into when item stacks are serialized for inventories. that's the most "compatible" since it only works around the client, though it would be a pain to maintain. one way or another, Mojang needs to be pushed to properly fix the issue since this feature is an intentional part of the client. it's not impossible to be worked around, there's just going to be a trade off somewhere.

**Comment by electronicboy** [comment] 2024-10-03 11:48
> Just wanted to add both use cases are extremely valuable, most players know the default values

most players are generally not the ones creating these items (and where they are, they'll be subjected to the new behavior directly through the command, not as a side-effect of something that for the better part of a decade just set a flag that hides something in the UI), it's plugins which have existed for a decade with a presumed set of behavior that they can hide attributes on their items to mitigate the space taken up by fluffing up item lore, etc. 

In cases where plugins are creating GUI items, it's easy to mitigate as they can just add any attribute they want in order to cause the component to save, but implicitly removing all item attributes when you pick to hide attributes just did not feel like the correct solution here as a default practice.

**Comment by ItsMias** [comment] 2024-12-16 21:05
I feel like the answer above makes sense, but I would prefer to at least have an option in the config to imitate the previous behavoir.

**Comment by Machine-Maker** [comment] 2024-12-16 21:38
The problem is that you *cannot* imitate the original behavior. You are always going to break something no matter what.
