### ISSUE TITLE
Add a new overload to Player#sendBlockDamage that includes the entityId of the mining player

### ISSUE THREAD

**Issue by u9g** [PaperSpigot/Paper#7657] opened 2022-03-24 23:43 UTC
### Is your feature request related to a problem?

sendBlockDamage is good if you only want to send it once, but if you want to make multiple blocks look like they are mined by the player, you need to send them with different entityids.

### Describe the solution you'd like.

add a new method with signature: `void sendBlockDamage(Player p, int entityId, Location loc, float progress);`

### Describe alternatives you've considered.

making my own lib with userdev

**Comment by Owen1212055** [comment] 2022-03-24 23:49
Will be Resolved by: https://github.com/PaperMC/Paper/pull/5840
So Dupe of: https://github.com/PaperMC/Paper/issues/5246

Also dupe of your own issue.. https://github.com/PaperMC/Paper/issues/7319

**Comment by lynxplay** [comment] 2022-03-24 23:50
Yeaa thanks Owen XD was just about to typ this out. No need to open an issue for this over and over. The original is still open and a PR exists. Closing this as a duplicate..

**Closed as completed** 2022-03-24 23:50 UTC
Labels: resolution: duplicate, type: feature
