### ISSUE TITLE
Cannot remove holograms with /kill

### ISSUE THREAD

**Issue by Innesity** [PaperSpigot/Paper#8070] opened 2022-06-29 06:25 UTC
### Expected behavior

Delete the holograms

### Observed/Actual behavior

The holograms are still here after command run.

### Steps/models to reproduce

https://youtu.be/aDBGF-aQpoA

### Plugin and Datapack List

[08:24:48 INFO]: Plugins (109): AcceptTheRules, ActionPoints, AdvancedEnchantments, AnotherDailyBonus, AntiAFKPlus, AntiCurse, AntiDisconnectSpam, ArmorStandTools, asCMD*, AuctionHouse, BattlePass, BestTools, BetterFarming, BetterRTP, BetterRTPAddons, BetterTalismans, BetterTridents, BossShopPro, BountyHunters, BungeeGuard, ChatColor2, ChestSort, Citizens, ClearLag, CMC-StaffHist*, CMILib, CoreProtect, CraftingStore, CraftMC-Addon*, CraftMCToxic*, CrazyCrates, CreativeManager, DeathChestPro, DeluxeCoinflip, DeluxeMenus, DeluxeTags, DisableMessages*, Duels, DungeonSystem, eGlow, EnderDragon, Essentials, EssentialsChat, EssentialsSpawn, EvenMoreFish, FastAsyncWorldEdit (WorldEdit), GadgetsMenu, GambleBarPro*, HeadDatabase, HiddenArmor, HoloExtension, HolographicDisplays, InteractiveChat, InvSeePlusPlus, Jobs, KixsChatGames, LagAssist, LiteBans, Lottery, LPX, LuckPerms, LumberJack, LWC, MarriageMaster, mcMMO, MCPerks, MoarBows, MobHunting, MobPlugin, Multiverse-Core, MyCommand, NBTAPI, NexEngine, OmegaVision, PlaceholderAPI, PlayerKits, PlayerVaults, PlayerWarps, PlugManX (PlugMan), ProtectionStones, ProtocolLib, PvPManager, RePlant, Rewards, Roulette, ShopGUIPlus, sleep-most, spark, StaffPlus, SuperVanish, TAB, TempFly, TitleManager, TradeSystem, UltimateAutoRestart, UnbreakableAnvils*, UpgradeableHoppers, UpgradeableSpawners, Vanillabosses, Vault, VoidGen, Votifier, VotingPlugin, Vouchers, WorldBorder, WorldGuard, WorldGuardExtraFlags, XLTournaments, XPStorage

### Paper version

This server is running Paper version git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 072f54c on ver/1.18.2)

**Comment by TetraTheta** [comment] 2022-06-29 06:32
Maybe you should consult with the author of holograph plugin first, and also, it seems that you are using third-party client.

So try to reproduce with...

 - Vanilla client
 - Small portion of plugins (only with plugins **directly** related to holograph - not addon stuff)

and if the problem still persist with Spigot, it may be Paper's problem I guess.

**Comment by Owen1212055** [comment] 2022-06-29 11:36
Aren’t holograms client side? Therefor the kill command wouldn’t kill these entities since they aren’t on the server.

**Comment by PedroMPagani** [comment] 2022-06-29 11:42
That’s not a server issue, it’s a miss concept of the issue creator, the holograms are fake entities therefore the server doesn’t have any knowledge about them in arrays/lists whatsoever, they’re not real entities, that’s why the command does not remove them.

**Comment by lynxplay** [comment] 2022-06-29 13:37
Closing as already pointed out, holograms usually are purely client side and only faked from the server through packets. This is a plugin specific "issue" if you want to call it that even. Consult the plugin author or plugin wiki on how to remove holograms.

**Closed as completed** 2022-06-29 13:38 UTC
Labels: type: bug, resolution: invalid
