### ISSUE TITLE
Bukkit.createInventory() is weird

### ISSUE THREAD

**Issue by Shesper** [PaperSpigot/Paper#9892] opened 2023-10-30 21:11 UTC
### Expected behavior

After creating an anvil inventory with the Bukkit.createInventory() method, PrepareAnvilEvent must be called when controlled after it is opened to the player.

### Observed/Actual behavior

However, PrepareAnvilEvent is not actually called and the inventory behaves as if the InventoryClickEvent was cancelled, and the item disappears on SHIFT+LEFT click control.

### Steps/models to reproduce

The code is like this:

![image](https://github.com/PaperMC/Paper/assets/25113455/7fb7858b-13e4-49a8-b0c4-5a34ef553cf5) 

![111111111](https://github.com/PaperMC/Paper/assets/25113455/2e671c74-bc2b-460d-b5c6-10a10e6cff7d)

![22222222222222](https://github.com/PaperMC/Paper/assets/25113455/30dcd3d6-c838-4a70-ab3f-f32e125ed6cc)

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/25113455/cc6468c6-604f-4cc7-b8da-8a82c4e5a5aa)

### Paper version

![image](https://github.com/PaperMC/Paper/assets/25113455/50cb49d0-8310-46d4-874f-2f28727bb6a3)

**Comment by electronicboy** [comment] 2023-10-30 21:16
This is not a bug as much as it's long missing functionality from bukkit, not all createInventory method calls will end up creating a "real" inventory of a specific type, right now, you have an inventory that looks like an anvil, but has literally 0 of its functionality, the only reason you see anything happening otherwise is because the client has its own logic which "predicts" the outcome

**Comment by Sytm** [comment] 2023-10-31 04:05
You probably want to use [this "family" of methods](https://jd.papermc.io/paper/1.20/org/bukkit/entity/HumanEntity.html#openAnvil%28org.bukkit.Location,boolean%29) instead because it opens real inventories

**Comment by Lori3f6** [comment] 2024-01-20 07:13
I have searched some posts and found the problem has been persisted for a long time, as discussed in this [SpigotMC post](https://www.spigotmc.org/threads/classcastexception-inventory-anvilinventory.199136/).
The anvil inventory instance created by `server.createInventory` is a instance of `CraftInventoryCustom`, which as this post states, it is not a real `AnvilInventory` and can not cast as well. Additionally, it does not invoke `PrepareAnvilEvent`.
The biggest missed function of this is *fake* anvil inventory is the plugin unable to fetch the content inside its text bar.
It would be nice if paper add a implementation for it someway. For instance, maybe opening the UI from a real anvil created internally, not present in the world?

**Comment by Machine-Maker** [comment] 2024-01-20 07:14
> It would be nice if paper add a implementation for it someway. For instance, maybe opening the UI from a real anvil created internally, not present in the world? 

There is a way, the openAnvil method that was mentioned above your post. You can customize the title too with the InventoryOpenEvent title override.

**Comment by Warriorrrr** [comment] 2024-02-10 09:37
Closing as a duplicate of #5825, use the openAnvil method instead as a workaround

**Closed as not planned by Warriorrrr** 2024-02-10 09:37 UTC
Labels: type: bug, resolution: duplicate, mitigated
