### ISSUE TITLE
InventoryMoveItemEvent - calling event.getSource().getLocation() from the event on a composter causes NPE 

### ISSUE THREAD

**Issue by dniym** [PaperSpigot/Paper#9437] opened 2023-07-02 12:27 UTC
### Expected behavior

You should be able to use event.getSource().getLocation() from the  InventoryMoveItemEvent to obtain the location of the source inventory.

### Observed/Actual behavior

when a composter is full and creates bonemeal, and a hopper is used to pull out the bonemeal, if you attempt to get the location of the source inventory from the InventoryMoveItemEvent a NPE will occur. 

`[08:19:40 INFO]: [IllegalStack] [STDOUT] Source is: COMPOSTER
[08:19:40 INFO]: [IllegalStack] [STDOUT] e.getSource().getLocation() was null.

[08:19:41 INFO]: [IllegalStack] [STDOUT] Source is: HOPPER
[08:19:41 INFO]: [IllegalStack] [STDOUT] Location from event: Location{world=CraftWorld{name=world},x=42.0,y=70.0,z=262.0,pitch=0.0,yaw=0.0}`

As you can see from the debug code above, when getLocation() is called from the event on a composter a NPE occurs, however when it is called on a HOPPER this same error does not occur.   It is also worth noting this only seems to happen in paper and not regular spigot.

### Steps/models to reproduce

`    @EventHandler
    public void onHopperTest(InventoryMoveItemEvent e) {
    	
    	
    	if(e.getSource().getHolder() instanceof BlockInventoryHolder) {
    		BlockInventoryHolder source = ((BlockInventoryHolder)e.getSource().getHolder());
    		System.out.println("Source is: " + source.getBlock().getType());
    		if(e.getSource().getLocation() != null)
    			System.out.println("Location from event: " + e.getSource().getLocation());
    		else
    			System.out.println("e.getSource().getLocation() was null.");
    	}
    	
    }`

### Plugin and Datapack List

[08:25:04 INFO]: Server Plugins (3):
[08:25:04 INFO]: Bukkit Plugins:
[08:25:04 INFO]:  - Essentials, IllegalStack, ProtocolLib

[08:25:41 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[08:25:41 INFO]: There are no more data packs available

### Paper version

version
[08:26:12 INFO]: Checking version, please wait...
[08:26:13 INFO]: This server is running Paper version git-Paper-61 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 171ba7c)
You are running the latest version
Previous version: git-Paper-45 (MC: 1.20.1)

**Comment by lynxplay** [comment] 2023-07-02 12:45
The ComposterBlock#OutputContainer does not override the getLocation method.
Not really related to the InventoryMoveItemEvent, the inventory implementation is just missing a method.

**Comment by dniym** [comment] 2023-07-02 13:25
> The ComposterBlock#OutputContainer does not override the getLocation method. Not really related to the InventoryMoveItemEvent, the inventory implementation is just missing a method.


Yeah, sorry about blaming inventoryMoveItemEvent, it just seemed the easiest way I could think of to demonstrate the bug.

**Comment by Machine-Maker** [comment] 2023-07-02 19:56
Where is the NPE (NullPointerException) being thrown when calling an event? A method returning null is not an NPE. If calling a method in the API throws an NPE, that is an issue. Is this issue just saying that a method returns null when it should return a Location? `Inventory#getLocation` is marked as nullable already.

**Comment by dniym** [comment] 2023-07-02 20:06
02:50:54 ERROR]: Could not pass event InventoryMoveItemEvent to IllegalStack v2.9.2
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because the return value of "org.bukkit.inventory.Inventory.getLocation()" is null
        at main.java.me.dniym.enums.Protections.getWorldFromObj(Protections.java:1618)

**Comment by Machine-Maker** [comment] 2023-07-02 20:11
That's not an NPE in the API, that's just something not handling getLocation returning null, which is a valid return value as the method is marked as Nullable. Are you requesting a new feature instead, where Inventory#getLocation for Composters returns an actual location instead?

**Comment by dniym** [comment] 2023-07-02 20:12
So if you check if the inventory holder is an instanceof BlockInventoryHolder then cast this to a BlockInventoryHolder you can invoke getBlock() and GetLocation() on this same composter with no issues, the issue is that getInventory() will return null when trying to getLocation() from other BlockInvenotyHolders...  which seems very inconsistent since it only appears to affect composters.  

Unsure why there would be an edge case on this specific block when it works on others?

**Comment by Machine-Maker** [comment] 2023-07-02 20:15
Well in this case, Composter and Hopper are different. The API is inconsistent with itself, creating fake "inventory types" for Composter and Jukebox that don't actually have inventory menus. I'm not saying this shouldn't be changed, but I'm saying that this issue is poorly described. The issue is not an NPE as the title suggests, but rather that Inventory#getLocation should return the composter location instead.

**Comment by dniym** [comment] 2023-07-02 20:24
However it needs to be worded or described I suppose..   but yes for consistency's sake I do believe the api should give you the actual location of a block attached to a hopper when InventoryMoveItemEvent is triggered and event.getSource().getLocation() is invoked rather than having to specifically check for two inventories that do not behave the same as all other block inventories attached to a hopper.

**Comment by Machine-Maker** [comment] 2023-07-05 02:44
No it's fine, I just wanted to clarify that this isn't really an NPE. It's all good as is.

**Closed as completed** 2023-08-21 04:49 UTC
Labels: type: bug, status: accepted, good first issue
