### ISSUE TITLE
Custom Crafted Items getting being weird in Papermc

### ISSUE THREAD

**Issue by BarryTheShen** [PaperSpigot/Paper#9348] opened 2023-06-15 13:50 UTC
### Expected behavior

The custom items that I created should trade normally with villagers, and stack normally.

### Observed/Actual behavior

The Items after created or duplicated(in creative mode) does not appear to stack or do the expected trading action

### Steps/models to reproduce

1.  get a custom item (any item with nbt) using commands that gives it a lore or attributes
2.  try to duplicate them using middle click in creative mode
3. try stacking them again
4. DOESNT STACK

OR
1. get a custom villager
2. put in custom items for the villager settings
3. try to trade with the custom villager
4. villager does not recognize the trade

### Plugin and Datapack List

Plugins: CustomRecipes, Essentials, ExecutableItems, FastAsyncWorldEdit, Geyser-Spigot, InventoryRollbackPlus, *LoginSecurity, LuckPerms, ProtocolLib, SCore, SkinsRestorer, WorldEditSelectionVisualizer
Datapacks:There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [file/villagershopcreator-v-3-1-1-19.zip (world)]

### Paper version

This server is running Paper version git-Paper-20 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: bae6096)\nYou are running the latest version\nPrevious version: git-Paper-10 (MC: 1.20)

This is the newest release of paper

### Other

This issue has existed for #3071 
I tested this on vanilla minecraft 1.20 it works perfectly fine
It might have to do with paper preventing duping? so setting a uuid for each of the custom items to distinguish them which kind of mess the thing up. (My assumption)

**Comment by BarryTheShen** [comment] 2023-06-15 13:54
because in normal minecraft without paper it worked perfectly well both villager trading and item stacking both in single player and multiplayer so Im wondering is there a possible option to disable it?

**Comment by electronicboy** [comment] 2023-06-15 13:56
villagers is a craftbukkit issue, which is caused by how craftbukkit handles itemstacks; Fixing it is planned, but requires a good modification of how itemstacks are handled within the server

the other one, no idea; reproduce without plugins, and check the data on the stacks

**Comment by Machine-Maker** [comment] 2023-06-15 14:01
Show the specific item with nbt you are using. Sometimes this can just be fixed by changing how you are defining  your custom item.

**Comment by BarryTheShen** [comment] 2023-06-15 14:04
{Slot: 0b, id: "minecraft:potato", tag: {display: {Name: '[{"text":"Enchanted Potato","italic":false,"color":"green"}]', Lore: ['[{"text":"Compacted Potato","italic":false,"color":"blue"}]']}, Enchantments: [{id: "minecraft:unbreaking", lvl: 1s}]}, Count: 64b}

**Comment by BarryTheShen** [comment] 2023-06-15 14:06
Now the stacking is working but I think it wont work after I tried to trade with villager

**Comment by Machine-Maker** [comment] 2023-06-15 14:06
Those 2 nbts you show should be able to stack. Items can only stack if they have the same NBT tag. And the 2 you’ve sent are the same. I need to see the difference.

**Comment by BarryTheShen** [comment] 2023-06-15 14:07
for some reason after i put into the villager trading place it became this:
{Slot: 0b, id: "minecraft:potato", tag: {display: {Name: '[{"text":"Enchanted Potato","italic":false,"color":"green"}]', Lore: ['[{"text":"Compacted Potato","italic":false,"color":"blue"}]']}, Enchantments: [{id: "minecraft:unbreaking", lvl: 1s}]}, Count: 64b}

**Comment by BarryTheShen** [comment] 2023-06-15 14:07
It adds a lvl:1s

**Comment by BarryTheShen** [comment] 2023-06-15 14:08
It remove the s and removed some stuff

**Comment by BarryTheShen** [comment] 2023-06-15 14:10
Paper will automatically update the NBT tag and make it lvl:1s from lvl:1

**Comment by Machine-Maker** [comment] 2023-06-15 14:10
Yeah, so put that “s” in the thing you use to create the custom item in the first place. That way they’ll all stack

**Comment by BarryTheShen** [comment] 2023-06-15 14:12
ok Thank you for you help

**Comment by BarryTheShen** [comment] 2023-06-15 14:12
I will check if there are more issues

**Closed as completed** 2023-06-15 14:21 UTC
Labels: type: bug, version: 1.20.1
