### ISSUE TITLE
Source inventory in InventoryMoveItemEvent shows wrong stack sizes.

### ISSUE THREAD

**Issue by panzertm** [PaperSpigot/Paper#11350] opened 2024-09-01 19:43 UTC
### Expected behavior

When iterating ofer the inventory you get from the InventoryMoveItemEvent, should get the correct stack sizes from the source inventory, e.g. the hopper inventory.

### Observed/Actual behavior

The first slot of the the hopper (source inventory) shows always the stack size of 1, even though it is not 1.

### Steps/models to reproduce

Place a hopper and fill it with 5*64 Items. Place a chest below. The source-Inventory always has the stack size 1 in Slot 0.

### Plugin and Datapack List

-

### Paper version

> version
[21:37:44 INFO]: Checking version, please wait...
[21:37:44 INFO]: This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-119-100d75a (MC: 1.21)

**Comment by electronicboy** [comment] 2024-09-01 19:44
Duplicate of #9028

**Closed as not planned by electronicboy** 2024-09-01 19:44 UTC
Labels: type: bug, version: 1.21
