### ISSUE TITLE
effects are broken

### ISSUE THREAD

**Issue by HeresJohnny320** [PaperSpigot/Paper#11010] opened 2024-07-01 17:56 UTC
### Expected behavior

i thought when i die that it would get removed or be able to /effect clear 

### Observed/Actual behavior

when i died all of my effects was still on me

### Steps/models to reproduce

so the way i found it was by doing 
/effect give @a minecraft:health_boost infinite 99 true
then die from something ingame or do /kill
then all of the effects stay on you and you cant 
/effect clear @a minecraft:health_boost so its just stuck on you

### Plugin and Datapack List

im not running any datapacks or plugins right now i found the bug on my main server then tryed it on my test server with no plugins or nothing and same problem but if you want to know my list that i run on my main let me know 

### Paper version

This server is running Paper version 1.21-40-master@b45d9b6 (2024-07-01T08:23:14Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-4-090775e (MC: 1.21)

### Other

i also tryed using spigot and normal minecraft jar and effects worked how its intended but paper has a bug somewhere hope this info helps and i hope it can get resolved soon :)
also keep in mind i did not try all effects so some effects might work some might not i only tested a hand full of effects and found that the hand fulls i tryed was broke

**Comment by HeresJohnny320** [comment] 2024-07-01 18:00
also one thing i forgot is the only fix i found was todo 1 of 2 things delete player data or /effect give @A minecraft:health_boost 10 99 true so setting a time can remove that effect

**Comment by Lulu13022002** [comment] 2024-07-01 18:17
Duplicate of https://github.com/PaperMC/Paper/issues/11002, spigot "fixed" that (with a bandaid) in https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/cdd05bc7faac70a5341ce9cd6524ac2ed0a80651#nms-patches%2Fnet%2Fminecraft%2Fworld%2Fentity%2FEntityLiving.patch?t=136. The real issue is still the same as always the player instance is not recreated on respawn and it's just a matter of time before another thing break.

**Closed as not planned by Lulu13022002** 2024-07-01 18:17 UTC
Labels: type: bug, resolution: duplicate, version: 1.21
