### ISSUE TITLE
Paper 1.21 cmd.exe console sometimes can't type things.

### ISSUE THREAD

**Issue by Stars-Azusa** [PaperSpigot/Paper#10929] opened 2024-06-20 08:24 UTC
### Expected behavior

When the server is started, you can type characters in the cmd console to execute commands.

### Observed/Actual behavior

When you try to enter text in the cmd console, sometimes it doesn't work correctly, and you need to press several times or hold the key for the characters to appear.

### Steps/models to reproduce

1. Open cmd.exe.
2. Start server with command: java -jar paper-1.21-*.jar -nogui, wait for the server to load completely.
3. Try to type something in the cmd console.
4. The character sometimes can't be typed.

### Plugin and Datapack List

/datapack list:
There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
There are no more data packs available
/plugins:
Server Plugins (0):

### Paper version

[16:20:55 INFO]: Checking version, please wait...
[16:20:56 INFO]: This server is running Paper version 1.21-15-master@2df432f (2024-06-19T19:19:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-9-4ea696f (MC: 1.21)

### Other

(I'm not sure whether the problem is caused by cmd.exe, because I can type in paper gui correctly.)

**Comment by lynxplay** [comment] 2024-06-20 08:27
Duplicate of https://github.com/PaperMC/Paper/issues/10405, downgrade to java 21 or use windows terminal instead of conhost.

**Closed as not planned by lynxplay** 2024-06-20 08:27 UTC
Labels: type: bug, resolution: duplicate, version: 1.21
