### ISSUE TITLE
Getting inventory of attached doublechests now returns single chest inventory

### ISSUE THREAD

**Issue by Tritonio** [PaperSpigot/Paper#6788] opened 2021-10-16 14:36 UTC
### Expected behavior

This code:

```
//clickedBlock is a sign attached to a chest
Block attached = clickedBlock.getRelative(((Directional)clickedBlock.getBlockData()).getFacing().getOppositeFace());

InventoryHolder chestState = (InventoryHolder) attached.getState();

Inventory chestInventory = chestState.getInventory();
```
Would give me a double chest inventory in version 283.

### Observed/Actual behavior

 In version 328 it gives me a single chest inventory instead.

### Steps/models to reproduce

Try the above code for the onclick event of a sign attached to the front face of a doublechest nd print out the length of the inventory for example.

### Plugin and Datapack List

Plugins (26): BasePvP, CdTe, ChangeBlame, Demended, DiscordSRV, EnticingRestarts, Experts, GriefPrevention, HandsOff, IDGAFAYAYPOV, IllegalStack, MapDistance, MobFreezer, ProtocolLib, RandomSpawn, ReservedSlots, Shrines, Sit, SuperbVote, TAB, TradeEasy, Votifier, Vulcan, WelcomeMessage, Zapping, ZeusVSTheUnemployed

There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

328, downloaded from the website. I cannot restart my server right now back to it to get the exact string, sorry.

**Comment by electronicboy** [comment] 2021-10-16 14:37
Duplicate of #6787

**Closed as completed by electronicboy** 2021-10-16 14:37 UTC
Labels: type: bug
