### ISSUE TITLE
Server Restart Message

### ISSUE THREAD

**Issue by Askarionn** [PaperSpigot/Paper#11054] opened 2024-07-11 02:37 UTC
### Expected behavior

![image](https://github.com/PaperMC/Paper/assets/51824859/40178608-7fad-49c7-b571-2ff5d98f11b9)
(On lower server versions works fine)

### Observed/Actual behavior

![image](https://github.com/PaperMC/Paper/assets/51824859/7c64674c-fbed-4f48-8d93-df3e3591bf69)

### Steps/models to reproduce

Set a custom message with underline or bold

### Plugin and Datapack List

0 plugins

### Paper version

This server is running Paper version 1.21-50-master@20889d0 (2024-07-10T16:28:03Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-47-62ed302 (MC: 1.21)

**Comment by Warriorrrr** [comment] 2024-07-11 08:04
Unable to reproduce, using underline & bold works fine

![image](https://github.com/PaperMC/Paper/assets/50800980/c99cf360-7ca5-447c-b34c-66665567755a)
![image](https://github.com/PaperMC/Paper/assets/50800980/42cb5834-ace7-4d8e-8c23-58c26aa91256)

**Comment by Askarionn** [comment] 2024-07-11 08:06
> Unable to reproduce, using underline & bold works fine
> 
> ![image](https://private-user-images.githubusercontent.com/50800980/347732998-c99cf360-7ca5-447c-b34c-66665567755a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODU0NjcsIm5iZiI6MTcyMDY4NTE2NywicGF0aCI6Ii81MDgwMDk4MC8zNDc3MzI5OTgtYzk5Y2YzNjAtN2NhNS00NDdjLWIzNGMtNjY2NjU1Njc3NTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA4MDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMDI0NjlhYWQwZjFlYmE3NjIzYjMwNGQ2YTU1ZmEyMmJjY2UzM2FhOGRhZjA5MTM0MTc2NTdhYTkxYzdjZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uG-814TFfsjqHF9TAUmQ9O8SjjYJlu5sa-Rr91Fo3gM) ![image](https://private-user-images.githubusercontent.com/50800980/347732166-42cb5834-ace7-4d8e-8c23-58c26aa91256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODU0NjcsIm5iZiI6MTcyMDY4NTE2NywicGF0aCI6Ii81MDgwMDk4MC8zNDc3MzIxNjYtNDJjYjU4MzQtYWNlNy00ZDhlLThjMjMtNThjMjZhYTkxMjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA4MDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZmM0ZGNiNDQ4ZTM1OWUwNGU5YmVkNmIwMDhlMjI3ZjVhYTU4NzUwMGZhOGIwM2RiMTMzYzZjMzQwZTRkM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LTs0Nk0e6AP5NfFr_ylMEVoKcdkv4r6dLHjKjrec1Ks)

hi, can you please try using multi-lines as in my reference?

**Comment by lynxplay** [comment] 2024-07-11 08:22
This was presumably resolved in the latest upstream update 👍 Someone give it a quick test pls, but yea. Maybe be fixed.

**Comment by CodeByCam** [comment] 2024-07-11 15:33
> This was presumably resolved in the latest upstream update 👍 Someone give it a quick test pls, but yea. Maybe be fixed.

Seems to be all good!
![fPE8qKO](https://github.com/PaperMC/Paper/assets/41496198/a19d9216-2bed-48d2-81bd-954d6c8d3ce2)

**Comment by Askarionn** [comment] 2024-09-06 17:50
The problem seems to be back

![image](https://github.com/user-attachments/assets/e90a920e-be91-49b1-8986-5e41e7eebb3e)
![image](https://github.com/user-attachments/assets/21b73c24-46c9-4d8b-a8b2-58c9fa448751)


Checking version, please wait...
[20:49:27 INFO]: This server is running Paper version 1.21.1-57-master@b483da4 (2024-09-01T18:09:05Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

**Comment by 456dev** [comment] 2024-09-06 20:27
cannot reproduce with this config
```yaml
restart: |-
    &2&l&nBold underline
    &f
    &6&lBold only
    &f
    &6&nUnderline only
```
![image](https://github.com/user-attachments/assets/caccebc4-452a-4eca-ab33-4ad9033c64d6)

> [!NOTE]
> [Paper docs](https://docs.papermc.io/paper/reference/spigot-configuration#messages_restart) says that the config should be used with & style codes, so it is likely that § working was an impl detail

**Comment by 456dev** [comment] 2024-09-06 20:32
Nope, bukkit shutdown also seems to work fine, completely cannot reproduce
```yaml
shutdown-message: |-
    §2§l§nShutdown Bold underline
    §f
    §6§lBold only
    §f
    §6§nUnderline only
```
(cause bukkit.yml's shutdown message does use legacy section according to the docs)

![image](https://github.com/user-attachments/assets/ad1ee066-8065-4af9-ab74-5600a70f21c9)

**Comment by Askarionn** [comment] 2024-09-06 20:42
Can you test with a velocity proxy? Since now I tested with a paper server a velocity proxy, but now I tested just on paper and it seems to work fine, might be related to Velocity?

**Comment by 456dev** [comment] 2024-09-09 01:45
tested on velocity, and can reproduce. I'm not sure if there is a https://github.com/PaperMC/Velocity issue for it yet, but this isn't a paper bug, and this issue can be closed again

**Closed as not planned** 2024-09-09 02:04 UTC
Labels: type: bug, resolution: cannot reproduce, upstream: spigot, version: 1.21
