### ISSUE TITLE
Wrong message on missmatching Java version.

### ISSUE THREAD

**Issue by DxsSucuk** [PaperSpigot/Paper#8748] opened 2022-12-31 14:23 UTC
### Expected behavior

Minecraft 1.19 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/

### Observed/Actual behavior

Minecraft 1.18 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/

### Steps/models to reproduce

Run the newest PaperMC build with a Java version below 17.

### Plugin and Datapack List

None

### Paper version

This server is running Paper version git-Paper-366 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-366 (MC: 1.19.3)
You are running the latest version

**Comment by NoahvdAa** [comment] 2022-12-31 14:28
This was already changed in Paperclip (see [this commit](https://github.com/PaperMC/Paperclip/commit/9878daa51d6da3fff26d8f09a5703d19b7ead6f0)). We just need to release a new Paperclip version before Paper can update to it :)

**Comment by DxsSucuk** [comment] 2022-12-31 14:31
Ah damn it, well understand! Will close the Issue.

**Comment by NoahvdAa** [comment] 2022-12-31 14:35
The message was just meant as a note, the issue is still valid imo ^_^

**Comment by Machine-Maker** [comment] 2023-03-20 05:19
Fixed in https://github.com/PaperMC/Paper/commit/7929540ba36d01f0a3888aa9c21e4fd28ed8b8d0

**Closed as completed by Machine-Maker** 2023-03-20 05:19 UTC
Labels: type: bug, status: accepted, version: 1.19
