### ISSUE TITLE
Paper server hangs whilst loading

### ISSUE THREAD

**Issue by olijeffers0n** [PaperSpigot/Paper#8717] opened 2022-12-24 12:57 UTC
### Stack trace

```
Console output:
https://paste.ollieee.xyz/cizolupemu.yaml
```

### Plugin and Datapack List

Plugins are not loaded yet

### Actions to reproduce (if known)

It is just my development server, updated to the latest build to test.

### Paper version

Latest, cannot get the output

### Other

Tested on Spigot, works fine... Just slower cause it isn't Paper.

**Comment by Peter-Crawley** [comment] 2022-12-24 13:02
Is this the same as https://github.com/PaperMC/Paper/issues/6020

**Comment by lynxplay** [comment] 2022-12-24 13:03
presumably yea

**Comment by olijeffers0n** [comment] 2022-12-24 13:04
You can close if its a duplicate then, wasn't aware there was another issue 😄

**Comment by olijeffers0n** [comment] 2022-12-24 15:52
To keep this in sync with discord, I can replicate this on every server start and this my stack:

https://paste.ollieee.xyz/suvexoyari.csharp

**Comment by Owen1212055** [comment] 2023-04-07 17:44
Dupe of https://github.com/PaperMC/Paper/issues/6020

**Closed as not planned by Owen1212055** 2023-04-07 17:44 UTC
Labels: resolution: duplicate
