### ISSUE TITLE
async chunk loader still trying to load chunk files after the world destroy was processed

### ISSUE THREAD

**Issue by BredyAK** [PaperSpigot/Paper#8312] opened 2022-08-19 10:53 UTC
### Expected behavior

debug log: https://paste.denizenscript.com/View/100276

### Observed/Actual behavior

paper does not properly close async tasks prior to the unload.

### Steps/models to reproduce

create a world, then destroy, sometimes this issue will happen, then your server will be filled with red errors.

### Plugin and Datapack List

Plugins (13): Citizens, CoreProtect, Denizen, Depenizen, LuckPerms, NoCheatPlus, PointsNotifier, ProtocolLib, spark, Terra, Vault, WorldEdit, WorldEditSUI
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

git-Paper-387 (MC: 1.18.2)

**Comment by PedroMPagani** [comment] 2022-08-19 11:04
I'll say what someone later will, paper does not provide support to old versions :(

**Comment by BredyAK** [comment] 2022-08-19 11:40
> I'll say what someone later will, paper does not provide support to old versions :(

i thought about that too before i post this issue, but i believe it's better to post it than saying nothing. i'm not sure if there is such a problem in latest version of paper, but what if? ;)

**Comment by PedroMPagani** [comment] 2022-08-19 11:41
> > I'll say what someone later will, paper does not provide support to old versions :(
> 
> i thought about that too before i post this issue, but i believe it's better to post it than saying nothing. i'm not sure if there is such a problem in latest version of paper, but what if? ;)

You're right. Would you be able to try it in the latest builds?

**Comment by BredyAK** [comment] 2022-08-19 15:27
> You're right. Would you be able to try it in the latest builds?

this issue only happens in chance during world destroy, and i don't know what could exactly trigger these errors, and i couldn't easily reproduce it on my test server. my production server is on 1.18.2, and it won't be updated in a short time.

**Comment by Owen1212055** [comment] 2022-09-12 17:53
Were you able to reproduce this issue at all then? Even if not easily, what were the steps you went through? Additionally, it would be nice if you could test it on the [chunk rewrite PR](https://github.com/PaperMC/Paper/pull/8177).

**Comment by Owen1212055** [comment] 2022-09-27 17:43
Since there has been a recode to the entire chunk system, and since this has been unable to be reproduced I will be closing this. Feel free to comment if you are still experiencing this issue on the latest version and it can be reopened.

Thank you!

**Closed as not planned by Owen1212055** 2022-09-27 17:43 UTC
Labels: type: bug, resolution: awaiting response
