### ISSUE TITLE
Mob Spawner not working at all.

### ISSUE THREAD

**Issue by Clyde6790pGIT** [PaperSpigot/Paper#10733] opened 2024-05-16 05:02 UTC
### Expected behavior

Mob Spawner should spawn entities.

### Observed/Actual behavior

Mob Spawner never spawns entities at all.

### Steps/models to reproduce

Get a Mob Spawner
Place an egg in it
And it never spawns

### Plugin and Datapack List

ViaVersion
ViaBackwards
ViaRewind
Geyser
Floodgate
Chunky
CoreProtect
WorldEdit
Chunky
CoreProtect
GriefPrevention
SkinRestorer

### Paper version

> /version
[09:53:30 INFO]: Unknown command. Type "/help" for help.
> version
[09:53:34 INFO]: Checking version, please wait...
[09:53:36 INFO]: This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
You are running the latest version

### Other

It functions correctly on a singleplayer world.

**Comment by CodeByCam** [comment] 2024-05-16 05:11
There are two config settings that _could_ be affecting this, [`disable-mob-spawner-spawn-egg-transformation`](https://docs.papermc.io/paper/reference/world-configuration#entities_spawning_disable_mob_spawner_spawn_egg_transformation), although this should still spawn the default mob, and [`tick-rates.mob-spawner`](https://docs.papermc.io/paper/reference/world-configuration#tick_rates_mob_spawner), which can disable all spawners if configured to do so.

In saying that, this is more than likely due to a plugin. Please test without running any plugins.

**Comment by Clyde-Timonera** [comment] 2024-05-16 05:13
Hi, I had also made a mob spawner before installing any plugins and it has appeared to not function either, I brushed it off for a bit and continued with my building and added some plugins to let my friends join in until I noticed it was still behaving the same.

**Comment by Clyde-Timonera** [comment] 2024-05-16 05:19
Just tried those configurations that you recommended, seems to still not work.

**Comment by CodeByCam** [comment] 2024-05-16 05:32
Can you please provide a copy of your `latest.log`? Just upload it to a [paste service](https://paste.gg/) and share it here.

I just tried on the build you're on with fresh configs (Bukkit.yml, Spigot.yml, & Paper's configs) and I had no issue placing a spawner, then an egg inside the spawner. 

Just check your server difficulty too, if it's on Peaceful it won't spawn hostile mobs from spawners. If that isn't the issue, I'd recommend regenerating your config files to test. To do this stop your server, back them up (just make a local copy of them), and delete said files. Start your server again and it will be with default configs.

**Comment by Clyde-Timonera** [comment] 2024-05-16 05:37
Hi here is a copy of my latest.log. https://paste.gg/p/anonymous/4d0acd4cac4a469ba298677790239112
For the serv difficulty, its set to easy.

**Comment by Clyde-Timonera** [comment] 2024-05-16 05:44
Does this have to do with the mob spawner being submerged? Regenerating configs didn't change a thing.

**Comment by CodeByCam** [comment] 2024-05-16 07:24
> Does this have to do with the mob spawner being submerged? Regenerating configs didn't change a thing.

Well it depends what mob you're putting in there. It will work underwater if there's enough room and the mob is an aquatic mob.
I'll close this issue now as I'm unable to reproduce it on a fresh server with no plugins.

If you have issues similar to this in the future you can try asking on our [Discord](https://discord.gg/papermc) first in [#paper-help](https://discord.com/channels/289587909051416579/289587909051416579), but I note you're using SkinRestorer, offline mode ("cracked servers") won't be given support.

**Closed as completed by CodeByCam** 2024-05-16 07:24 UTC
Labels: resolution: invalid
