### ISSUE TITLE
Disconnect players before unloading plugins

### ISSUE THREAD

**Issue by NonSwag** [PaperSpigot/Paper#9837] opened 2023-10-14 22:56 UTC
### Is your feature request related to a problem?

My general problem is that players get kicked for `server closed` **after** the plugins got disabled
this causes the problem of `PlayerQuitEvent`/`PlayerKickEvent` not being called
This can lead for example to something like data not being stored or so

### Describe the solution you'd like.

I'd love to see the player disconnect logic being handled before the plugins unload

### Describe alternatives you've considered.

Right now when dealing with this problem I (_or plugin devs in general_) have to handle everything onDisable or kick the player

### Other

![image](https://github.com/PaperMC/Paper/assets/54660361/e7f5d6a8-b377-46eb-8232-cb9c8ec71d0b)

**Comment by NonSwag** [comment] 2023-10-14 22:58
I don't really want to create a pr for this because first I want to get some input on this
maybe there is a good reason for this idk

**Comment by lynxplay** [comment] 2023-10-14 23:05
Duplicate of #6911 and https://github.com/PaperMC/Paper/pull/9679.

Generally not something we can takle till hardfork imo, can keep discussion in the respective PR given how terribly low priority this is.

**Closed as not planned** 2023-10-14 23:05 UTC
Labels: resolution: duplicate, type: feature

**Comment by Combustible** [comment] 2023-11-19 08:20
This is a critical problem for us as well - so we just hack around it in our paper fork. Not ideal, and certainly not a PR I'd like to submit here... but this patch has worked for us for years now: 

https://github.com/TeamMonumenta/monumenta-paperfork/blob/main/patches/server/0004-Monumenta-Move-player-saving-to-before-disabling-plu.patch

Would love to see this changed someday. Until this is fixed it's difficult to reliably build a plugin that alters how player data storage works. 

@NonSwag perhaps this will help you if you happen to already use a customized paper jar.

**Comment by Combustible** [comment] 2023-11-19 08:23
Oh, it looks like the above referenced #9679 does basically this same thing, I should have checked before commenting.

**Comment by NonSwag** [comment] 2023-11-19 08:24
The problem with this is that the behavior for certain plugins COULD possibly change or even break them which is a total no-go in production but thanks for your input
