### ISSUE TITLE
Trident Respawn Rate doesn't have its own line in level preparation

### ISSUE THREAD

**Issue by Chris6ix** [PaperSpigot/Paper#7326] opened 2022-01-13 20:34 UTC
### Expected behavior

A new line for the Trident Respawn Rate?

### Observed/Actual behavior

Trident Respawn Rate in same line as Arrow Despawn Rate

### Steps/models to reproduce

Start the server?

### Plugin and Datapack List

None

### Paper version

[21:21:24 INFO]: This server is running Paper version git-Paper-150 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0c64d40)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-145 (MC: 1.18.1)

### Other

I don't know if this is a bug or if it's intended but while testing something I saw that the "Trident Respawn Rate" doesn't have its own line in the level preparation (and doesn't have a space behind the colon like all the other listed things)...which looks a bit ""unclean"
![Screenshot 2022-01-13 211217](https://user-images.githubusercontent.com/65610536/149404058-9a2cd858-de21-43eb-91ec-b93c57f028f9.png)

**Comment by lynxplay** [comment] 2022-01-13 21:01
Concerning that this is an upstream configuration option added [in this spigot patch](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/047b6f86bc7927f729039fb212aae9ca676da019), is hidden by paper by default and does not hurt anyone, I will close this issue as "works as intended".

Concerning that the commit linked specifically adds it to the same log call (besides the missing space between the column) I'd say it is pretty safe to assume that it is actually how it is supposed to work.

If any development team members disagree obviously feel free to open it again, however I do not think this is worth patching.

Thanks for the report nonetheless :)

**Closed as completed by lynxplay** 2022-01-13 21:01 UTC
Labels: type: bug, resolution: works as intended, upstream: spigot
