### ISSUE TITLE
Health boost potion effect persists upon dying

### ISSUE THREAD

**Issue by furiouswhqle** [PaperSpigot/Paper#11002] opened 2024-06-30 03:56 UTC
### Expected behavior

I expected the health boost effect to wear off upon dying.

### Observed/Actual behavior

The health boost didn't show as an effect in the inventory, but still gave additional hearts even when dying.

### Steps/models to reproduce

1) Start a paper server with version 1.21 build 39 (latest as of writing this)
2) /effect give @p health_boost infinite
3) Die

### Plugin and Datapack List

No plugins
Only default datapacks (vanilla, bukkit, paper)

### Paper version

[22:54:51 INFO]: This server is running Paper version 1.21-39-master@aa8d38d (2024-06-29T09:10:10Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version

**Comment by rymiel** [comment] 2024-06-30 11:41
Probably the same cause as https://github.com/PaperMC/Paper/issues/10907

**Comment by Malfrador** [comment] 2024-06-30 17:47
Duplicate of https://github.com/PaperMC/Paper/issues/11002 indeed

**Closed as not planned by Malfrador** 2024-06-30 17:47 UTC
Labels: type: bug, resolution: duplicate, version: 1.21
