### ISSUE TITLE
Priority of MC-Command is overridden by the same Paper-Command

### ISSUE THREAD

**Issue by Leahcimkrob** [PaperSpigot/Paper#9458] opened 2023-07-07 17:31 UTC
### Expected behavior

When I run the /locate command, I want to know which biome or structure is nearby (MC-CMD /locate)

### Observed/Actual behavior

With /locate the MC command is not executed as it was up to 1.19.4, but since 1.20 and 1.20.1 the command worldguard:loacte

### Steps/models to reproduce

Install paper and Worldguard an you can reproduce it

### Plugin and Datapack List

[19:25:43 INFO]: PM | Plugins (20):
[19:25:43 INFO]:  - AutoRestart 4.2.1
[19:25:43 INFO]:  - ChatFree 1.2
[19:25:43 INFO]:  - ChestCommands 4.0.4
[19:25:43 INFO]:  - Citizens 2.0.32-SNAPSHOT (build 3135)
[19:25:43 INFO]:  - CMI 9.6.1.0
[19:25:43 INFO]:  - CMILib 1.3.1.2
[19:25:43 INFO]:  - FastAsyncWorldEdit 2.6.5-SNAPSHOT-511;a669be2
[19:25:43 INFO]:  - HeadDatabase 4.17.3
[19:25:43 INFO]:  - HolographicDisplays 3.0.3-SNAPSHOT-b257
[19:25:43 INFO]:  - ImageMaps 1.0.7
[19:25:43 INFO]:  - LuckPerms 5.4.89
[19:25:43 INFO]:  - Multiverse-Core 4.3.2-SNAPSHOT-b870
[19:25:43 INFO]:  - PacketsBookFix 1.0
[19:25:43 INFO]:  - PlaceholderAPI 2.11.3
[19:25:43 INFO]:  - PluginManager 2.8.1
[19:25:43 INFO]:  - ProtocolLib 5.0.0-SNAPSHOT-b618
[19:25:43 INFO]:  - SignColorPlus 1.2
[19:25:43 INFO]:  - TAB-Bridge 3.1.0
[19:25:43 INFO]:  - Vault 1.7.3-CMI
[19:25:43 INFO]:  - WorldGuard 7.0.9-SNAPSHOT+2241-c0cbe27

### Paper version

[19:26:18 INFO]: This server is running Paper version git-Paper-66 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Other

After updating from 1.19.4 to 1.20.1 the /locate cmd just converted to locating players using compass
Bug is since Paper 1 (MC: 1.20)

The command comes from Worldguard.
According to Worldgaurd-Devs, you should have changed something, that the MC command no longer has priority, but now the Worldguard command.

**Comment by electronicboy** [comment] 2023-07-08 12:11
can you test with just WorldGuard + WorldEdit installed? from what I see, that command shouldn't even be registering unless CommandBook is installed, or something is pretending to be command book

Plugin commands have pretty much *always* overriden built-in commands

**Comment by electronicboy** [comment] 2023-07-08 12:20
okay, I brain farted, the commands are registered when craftbook *isn't* installed, not when it is; there is a bug report for paper for their command registration failing in 1.19+, so they made some tweaks there; idk of any changes that would impact 1.19 > 1.20, but, plugin commands have always overriden vanilla commands, like, all I could guess is that you where using an old version of WG in which their commands failed to registered for some reason

**Comment by Leahcimkrob** [comment] 2023-07-08 14:22
I had always used the latest version of Worldguard.  we started with MC version 1.16.  there locate went from vanilla, up to 1.19.4 always with the current WG version.  both until January with essentials and since then with cmi.  only with the change to 1.20 and with it the new paper and Worldguard is locate from Worldguard.

I once posted the link to the corresponding Worldgard issue.
https://github.com/EngineHub/WorldGuard/issues/2013

**Comment by electronicboy** [comment] 2023-07-08 14:35
The behavior for a decade is that plugins will override vanilla commands,
so, if this behavior wasn't the case in 1.19.x, it would sound like a bug
was accidently fixed

There is probably a feature request to backlist plugins being able to
register and replace vanilla commands, but, otherwise, everything here is
working as intended

**Comment by me4502** [comment] 2023-07-09 01:39
When I suggested they file a bug with Paper, that was because people were saying there are bugs in the commands.yml system which is intended to solve command conflicts

**Comment by davemsh** [comment] 2023-08-28 21:40
I've just run into this as well. The `commands.yml` aliasing doesn't seem to work correctly when I try to override WorldGuard's `locate` command to go back to the Mojang version, and it continues to use the plugin's version of the command rather than the alias taking precedence over it as described in the [PaperMC documentation](https://bukkit.fandom.com/wiki/Commands.yml). The `wglocate` alias I've added below works as expected, and calls the plugin's version of the command.

WorldGuard and its WorldEdit dependency are the only two plugins I have installed on the server.

```
aliases:
  icanhasbukkit:
  - version $1-
  locate:
  - minecraft:locate $1-
  wglocate:
  - worldguard:locate $1-
```

**Comment by the456gamer** [comment] 2023-08-28 21:44
try adding "locate" to 
commands.replace-commands in spigot.yml

**Comment by davemsh** [comment] 2023-08-28 21:48
I just tried adding `locate` to that section, restarted the server, and it doesn't seem to have had any effect.

**Comment by Falkenthedane** [comment] 2023-11-24 15:59
I’m having the same issue! Can’t do the location command anymore

**Comment by electronicboy** [comment] 2023-11-24 16:02
This is not a bug, this is generally how commands have worked for years, just the plugin changed
use `minecraft:command` to force it to run the vanilla command

**Comment by Falkenthedane** [comment] 2023-11-24 16:04
> This is not a bug, this is generally how commands have worked for years, just the plugin changed use `minecraft:command` to force it to run the vanilla command

Thank you! I didn’t know that was a way to do it 🫶🏻

**Comment by brothanb** [comment] 2023-11-24 17:52
FYI...  I used an alias in commands.yml to "restore" the reload command to the Minecraft command:
`aliases:
  reload:
  - minecraft:reload $1-
`

**Comment by lynxplay** [comment] 2024-07-19 07:10
Closing this as presumably completed.

**Closed as not planned by lynxplay** 2024-07-19 07:10 UTC
Labels: type: bug, resolution: works as intended
