### ISSUE TITLE
Crash: Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by codeHusky** [PaperSpigot/Paper#10121] opened 2024-01-03 23:07 UTC
### Stack trace

https://paste.gg/p/anonymous/01c13516f8854d5a875b373b5580e155

### Plugin and Datapack List

```[18:01:15 INFO]: Server Plugins (62):
[18:01:15 INFO]: Bukkit Plugins:
[18:01:15 INFO]:  - Analyse, AntiPopup, AreaShop, ChangeSlots, ChatItem, Chunky, ChunkyBorder, Citizens, CMCEvents, CMCLinkManager
[18:01:15 INFO]:  CoreProtect, CrashClaim, CrashPayment, CreativeManager, DecentHolograms, dynmap, dynmapHider, DynmapWaystones, Essentials, EssentialsSpawn
[18:01:15 INFO]:  FancyWaystones, FastAsyncWorldEdit, FreedomChat, GSit, HatCosmetics, HeadDatabase, HeadHunter, helper, helper-sql, HubParkour
[18:01:15 INFO]:  HuskyPatch, HuskyScreen, *HuskyTest, HuskyTweaks, ImageMaps, InventoryRollbackPlus, InvSeePlusPlus, LibsDisguises, LiteBans, LitebansAntiMuteBypass
[18:01:15 INFO]:  LPC, LuckPerms, Multiverse-Core, Multiverse-NetherPortals, PlaceholderAPI, Plan, PlasmoVoice, PlugManX, ProtocolLib, pv-addon-lavaplayer-lib
[18:01:15 INFO]:  QSFindItemAddOn, QuickShop, ServerSigns, spark, SubserverTools, TAB, UltimateAutoRestart, Vault, VillagerTradeLimiter, Watson
[18:01:15 INFO]:  WitherSound, WorldGuard
```

### Actions to reproduce (if known)

Server had been up for just over 10 hours with numerous active players throughout the day when crash occurred

### Paper version

```[18:01:35 INFO]: Checking version, please wait...
[18:01:35 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-Paper-270 (MC: 1.20.2)
```

### Other

I'm aware this isn't the latest version of Paper, but as this happened completely randomly, I figured I'd report it for sake of documentation and in case of this happening again. I didn't see any relevant closed issues related to this so I'm unsure if this was fixed upstream/by Mojang/etc. Will be updating the server soon so hopefully this stops, but upon reviewing it looks like we have crash reports since December 7th with this issue that are becoming more regular over time. We're waiting on Plasmovoice to update atm as the only blocker.

**Comment by Machine-Maker** [comment] 2024-01-03 23:38
This is most likely caused by one of your plugins doing something off the main thread they shouldn't. One of the more likely causes is playing a sound to a world asynchronously which plugins like to do without realizing that in most situations, its not a thread-safe operation. 

We added more specific checks for sounds in 1.20.4 that will show the offending plugin, but as you are on an earlier version, there is no way to be sure what plugin caused the issue. If you have a plugin which you know does play sounds, perhaps try removing that plugin and seeing if the crash happens again.

I'm going to close this then, on the assumption that it is something "fixed" in a later version (like sounds). If you get this issue again on 1.20.4, we can re-open it.

**Closed as not planned by Machine-Maker** 2024-01-03 23:38 UTC
Labels: type: bug, resolution: invalid

**Comment by codeHusky** [comment] 2024-01-12 21:33
After manually patching in the async catchops into 1.20.2, it appears to have been thito's fancywaystones plugin calling async playsound. Remedy for anyone with an identical set of circumstances should just be updating that plugin.
```
[15:20:47] [FWIO/ERROR]: Thread FWIO failed main thread check: play sound
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.playSound(CraftWorld.java:1871) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.playSound(CraftWorld.java:1861) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at org.bukkit.craftbukkit.v1_20_R2.CraftWorld.playSound(CraftWorld.java:1851) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at thito.fancywaystones.effect.PlaySound.lambda$createHandler$0(PlaySound.java:41) ~[FancyWaystones.1202.jar:?]
	at thito.fancywaystones.task.PostTeleportTask.run(PostTeleportTask.java:49) ~[FancyWaystones.1202.jar:?]
	at thito.fancywaystones.Task.lambda$schedule$0(Task.java:14) ~[FancyWaystones.1202.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```
