### ISSUE TITLE
Custom Biomes are not generating in the nether via datapacks in 1.18 early builds.

### ISSUE THREAD

**Issue by Athesiel** [PaperSpigot/Paper#7103] opened 2021-12-13 00:39 UTC
### Expected behavior

I've set up a test datapack to demonstrate this issue. In this datapack, the following things should occur:

The overworld should generate with two biomes: plains, and "overworld_test". 

The latter biome should generate with the feature "test_feature", i.e. red wool patches. 

The nether should generate with the nether_wastes biome, and a "nether_test" biome. 

To prove that the datapack, while in the server/world/datapacks folder, still influences nether generation, as in 1.17, the nether_wastes biome should have patches of lime wool, as per the "test_feature_existing_biome" feature.

The issue comes from that the "nether_test" biome should also appear, and generate with the "test_feature" feature, which would work with a similar datapack in 1.17.

The nether should not generate with any other biomes aside from the nether_wastes, and the nether_test biome.

### Observed/Actual behavior

The test for showing custom biomes in the overworld is successful, the test for showing that nether world generation is affected by datapacks in server/world/ as of 1.18 is successful. The test showing that custom biomes do not generate in the nether is, however, not successful. Additionally, the removal of existing biomes in the nether is unsuccessful.

### Steps/models to reproduce

To test that world generation is working at all, simply use /locatebiome minecraft:overworld_test. Upon arriving in the biome, you should see patches of red wool, confirming feature placement is functional. Then, head into the nether. There should be patches of lime wool, proving that the datapack does in fact work in the nether. Using /locatebiome minecraft:nether_test, you should not be able to locate the biome.

### Plugin and Datapack List

[worldgen_test.zip](https://github.com/PaperMC/Paper/files/7700189/worldgen_test.zip)

### Paper version

 §fThis server is running Paper version git-Paper-71 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 91f3eda)§r

### Other

This datapack has been tested in a singleplayer world. Additionally, it was suggested that the datapack would need to be placed in the file path of world_nether- this does not help, nor is it the expected functionality from 1.17, nor does it make sense given that the nether IS being modified from datapacks within the world/datapacks folder. 

The lack of ability to remove the populating biomes from the nether in the first place is concerning, but this leads me to believe the issue is that paper is not populating the dimension through the dimension/the_nether.json file, as it should be, as it was in 1.17, and as it does with the overworld.json file.

**Comment by jpenilla** [comment] 2021-12-13 00:47
Duplicate of #6880

**Closed as completed by jpenilla** 2021-12-13 00:47 UTC
Labels: type: bug, resolution: duplicate
