### ISSUE TITLE
Chunk load & Entity

### ISSUE THREAD

**Issue by PedroMPagani** [PaperSpigot/Paper#8010] opened 2022-06-17 08:46 UTC
### Is your feature request related to a problem?

Is it supposed to be this way?
When a chunk has past entities on it, and it loads, at the chunk load event we’re not able to call .getEntities, the array is empty, if you schedule it for 2 ticks, the past entities are there.

### Describe the solution you'd like.

Add the entities or a new type of event

### Describe alternatives you've considered.

What I had as logical would be once the chunk loads, the entities does too

### Other

Is there an event called for the load of these past entities?

**Comment by NoahvdAa** [comment] 2022-06-17 08:53
Sounds like a duplicate of #5872

**Comment by PedroMPagani** [comment] 2022-06-17 14:41
It seems to be a duplicate, could be a reminder for the future or someone see and patch it.

**Closed as not planned** 2022-06-17 14:41 UTC
Labels: type: feature
