### ISSUE TITLE
Adding ItemFlag in ItemMeta is ignored or is not updated

### ISSUE THREAD

**Issue by anjoismysign** [PaperSpigot/Paper#11187] opened 2024-07-28 20:33 UTC
### Expected behavior

A wooden shovel that hides all flags.

### Observed/Actual behavior

A wooden shovel that still shows attributes

<img width="385" alt="Screenshot 2024-07-28 at 4 33 52 PM" src="https://github.com/user-attachments/assets/98049158-7456-481a-90ec-efedd24e3a7f">

### Steps/models to reproduce

Use ItemMeta in a wooden shovel and add all item flags.
Give yourself the wooden shovel and see it in game.

### Plugin and Datapack List

[16:32:47 INFO]: Bukkit Plugins:
[16:32:47 INFO]:  - Basics, BlobBuild, BlobDesign, BlobEconomy, BlobLib, BlobRP, BlobTycoon, Citizens, DecentHolograms, ItemEdit
[16:32:47 INFO]:  LuckPerms, PhatLoots, PlaceholderAPI, TAB, Vault, VoidGen, VoxelSniper

### Paper version

[16:33:11 INFO]: Checking version, please wait...
[16:33:12 INFO]: This server is running Paper version 1.21-113-master@f82bea6 (2024-07-28T18:30:03Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-51-f7124df (MC: 1.21)

### Other

Only present since 1.21, cannot replicate on upstream.

**Comment by lynxplay** [comment] 2024-07-28 20:36
Duplicate of https://github.com/PaperMC/Paper/issues/10693 and the large amount of similar issues.
It is a pain that this is sadly a "works as intended" right now, but the alternative is blind item fuckery that will break items quietly in future versions so, yea. Sorry.

See the other issue linked (and its relatives) for more info, or ask in our discord if you have more questions.

**Closed as not planned by lynxplay** 2024-07-28 20:36 UTC
Labels: type: bug, resolution: duplicate, version: 1.21
