### ISSUE TITLE
Server crashes every time a chest is opened

### ISSUE THREAD

**Issue by KMatuszak** [PaperSpigot/Paper#8089] opened 2022-07-03 20:09 UTC
### Stack trace

https://paste.gg/p/anonymous/03ebefd3353d42db81bef6978c68f1c1

### Plugin and Datapack List

[22:07:31 INFO]: Plugins (0):

[22:07:40 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[22:07:40 INFO]: There are no more data packs available

### Actions to reproduce (if known)

1. Create new clean server with level seed: -5587792558583463128
2. Teleport: /tp -485 43 5842
3. Open chest you see

### Paper version

[22:07:50 INFO]: Checking version, please wait...
[22:07:51 INFO]: This server is running Paper version git-Paper-44 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: ed79fc9)
You are running the latest version

### Other

Level seed: -5587792558583463128
Chest coords: -485 43 5842

**Comment by Machine-Maker** [comment] 2022-07-03 20:19
Duplicate of https://github.com/PaperMC/Paper/issues/2312
and https://github.com/PaperMC/Paper/issues/7664
and https://github.com/PaperMC/Paper/issues/7963
and https://github.com/PaperMC/Paper/issues/8069

**Closed as not planned by Machine-Maker** 2022-07-03 20:19 UTC
Labels: resolution: duplicate
