### ISSUE TITLE
Calling the Entity.damage() function in an EntityDamageEvent with block damage causes an error.

### ISSUE THREAD

**Issue by GreatWyrm** [PaperSpigot/Paper#6696] opened 2021-10-02 02:31 UTC
### Expected behavior

The block damage and the damage from the damage() call to both successfully damage their respective targets without causing errors.

### Observed/Actual behavior

The damage call did not go through and instead threw an error
Full Error: https://paste.gg/p/anonymous/5af0356e85824f8c875132996ab9f665

### Steps/models to reproduce

Creating a registering an EventHandler in the form of this:

@EventHandler
  public void damagedEntity(EntityDamageEvent event) {
    if (event.getCause() != EntityDamageEvent.DamageCause.CUSTOM)
      for (Player player : Bukkit.getOnlinePlayers())
        player.damage(1.0D);  
  }
  
  Will reproduce the error.
  I've done some testing, and as far as I can tell, all that you need to cause this error is to put some blockdamage on the stack, and then put a different type of damage on the stack as well.

### Plugin list

Plugins (1): BlockDamageTest

(The plugin I created to reproduce the error)

### Paper version

[22:22:17 INFO]: Checking version, please wait...
[22:22:17 INFO]: This server is running Paper version git-Paper-295 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f905057)
You are running the latest version
Previous version: git-Paper-788 (MC: 1.16.5)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment] 2021-10-02 02:38
This is probably because of the shared state that CraftEventFactory has...

**Comment by Machine-Maker** [comment] 2021-10-02 03:48
~~What uh, if that was turned into a queue sorta, where you added, and then popped, that would give you the correct block damage right?~~

EDIT: hmm no the issue isn't what I thought it was

Round 2: Can we just clear the CraftEventFactory.blockDamage, after its read in CraftEventFactory?

Well, looks like that use to exist and was [removed by md_5](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/89e2b1270fb91f7bc3e00fe57ecbe99731a698b0)

**Comment by Machine-Maker** [comment] 2022-03-17 16:40
Fixed in https://github.com/PaperMC/Paper/commit/512995c2a574fda0a1b536255e3ba9ddded081e3

**Closed as completed by Machine-Maker** 2022-03-17 16:40 UTC
Labels: type: bug, status: accepted, version: 1.17
