### ISSUE TITLE
Players Randomly Kicked with 'Server went down'

### ISSUE THREAD

**Issue by Goonhaven** [PaperSpigot/Paper#9362] opened 2023-06-18 02:31 UTC
### Stack trace

```
[22:08:14 INFO]: UUID of player <playername> is *********redacted***********
[22:08:14 ERROR]: Caught previously unhandled exception :
[22:08:14 ERROR]: Paper Async Command Builder Thread Pool - 19
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.calculateChildPerms(PermissiblePEX.java:174) ~[PermissionsEx.jar:?]
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.recalculatePermissions(PermissiblePEX.java:158) ~[PermissionsEx.jar:?]
        at org.bukkit.permissions.PermissibleBase.addAttachment(PermissibleBase.java:139) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftHumanEntity.addAttachment(CraftHumanEntity.java:248) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at com.fastasyncworldedit.bukkit.BukkitPermissionAttachmentManager.lambda$getOrAddAttachment$0(BukkitPermissionAttachmentManager.java:32) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at com.fastasyncworldedit.bukkit.BukkitPermissionAttachmentManager.getOrAddAttachment(BukkitPermissionAttachmentManager.java:32) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:108) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapPlayer(WorldEditPlugin.java:566) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapCommandSender(WorldEditPlugin.java:596) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitCommandInspector.lambda$testPermission$0(BukkitCommandInspector.java:80) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
        at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at com.sk89q.worldedit.command.util.PermissionCondition.satisfied(PermissionCondition.java:54) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitCommandInspector.testPermission(BukkitCommandInspector.java:81) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.testPermissionSilent(DynamicPluginCommand.java:107) ~[FastAsyncWorldEdit-Bukkit-2.6.4-SNAPSHOT-481.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:56) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.test(BukkitCommandWrapper.java:23) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:495) ~[?:?]
        at net.minecraft.commands.Commands.sendAsync(Commands.java:451) ~[?:?]
        at net.minecraft.commands.Commands.lambda$sendCommands$4(Commands.java:424) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.calculateChildPerms(PermissiblePEX.java:170) ~[PermissionsEx.jar:?]
        ... 26 more
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
        at io.papermc.paper.plugin.manager.PaperPermissionManager.subscribeToPermission(PaperPermissionManager.java:111) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.subscribeToPermission(PaperPluginManagerImpl.java:178) ~[purpur-1.20.1.jar:git-Purpur-1995]
        at org.bukkit.plugin.SimplePluginManager.subscribeToPermission(SimplePluginManager.java:841) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.permissions.PermissibleBase.calculateChildPermissions(PermissibleBase.java:203) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.calculateChildPerms(PermissiblePEX.java:170) ~[PermissionsEx.jar:?]
        ... 26 more
[22:08:14 INFO]: <player_name> joined the game

```

### Plugin and Datapack List

Bukkit Plugins: (30):
[22:22:37 INFO]:  - BungeeTabListPlus, Chunky, Essentials, EssentialsSpawn, FastAsyncWorldEdit, FoxyMachines, FreedomChat, GriefPrevention, GrimAC, HolographicDisplays
[22:22:37 INFO]:  InfinityExpansion, LogBlock, mcMMO, *MultiChat, Networks, *PermissionsEx, *RenCornerIRC, RHLeafDecay, SFCalc, Slimefun
[22:22:37 INFO]:  spark, stafftoggle (disabled), TradeSystem, Vault, ViaBackwards, ViaVersion, voicechat, Votifier, VotingPlugin, WhatIsThis

### Actions to reproduce (if known)

Unknown. I ask each time players get kicked; one time they were chopping a tree, another time being idle - seems unrelated to any activity. They do all have wireless connections I've found so far, so could be packet-loss and keep-alive related.

### Paper version

Current: git-Purpur-1995 (MC: 1.20.1)*
Previous: git-Paper-26 (MC: 1.20.1)

(only using Purpur for the keep-alive option for patchy connections ironically)

### Other

Error on bungee when player disconnected (with message 'server went down', which it didn't): "DownstreamBridge <-> [Survival] - NativeIoException: recvAddress(..) failed: Connection reset by peer"

Spark profile:  https://spark.lucko.me/ngRIAJ13HV

I don't know if the stack trace I posted is related to the kick for this particular player, because for another there was no such issue with permissionsex.

**Comment by imDaniX** [comment] 2023-06-18 17:40
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.calculateChildPerms(PermissiblePEX.java:174) ~[PermissionsEx.jar:?]
        at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.recalculatePermissions(PermissiblePEX.java:158) ~[PermissionsEx.jar:?]
```
Seems like PermissionsEx problem to me. Please, consider migrating to some actually supported plugin, like [LuckPerms](https://luckperms.net/).

**Comment by Goonhaven** [comment] 2023-06-19 00:19
> ```
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
>         at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.calculateChildPerms(PermissiblePEX.java:174) ~[PermissionsEx.jar:?]
>         at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.recalculatePermissions(PermissiblePEX.java:158) ~[PermissionsEx.jar:?]
> ```
> 
> Seems like PermissionsEx problem to me. Please, consider migrating to some actually supported plugin, like [LuckPerms](https://luckperms.net/).

I shouldn't have included that stack trace - he's the only player who gets disconnected with that stack trace. I don't think it's PEx.

**Comment by electronicboy** [comment] 2023-06-19 00:22
That error is not the cause, it won’t cause a disconnect; we don’t accept reports from software that isn’t ours, nor is this the place for support, all we can tell you is that the connection between the proxy and the server was closed in an unexpected manner, you’d need to see if there’s any more in your logs which might be useful, or start looking into network diagnosis

**Closed as not planned by electronicboy** 2023-06-19 00:22 UTC
Labels: version: 1.20.1
