### ISSUE TITLE
Aliases registered with the Brigadier Command API do not have priority over vanilla commands.

### ISSUE THREAD

**Issue by NamiUni** [PaperSpigot/Paper#11035] opened 2024-07-07 16:35 UTC
### Expected behavior

Aliases should take precedence over vanilla commands for commands executed by the player or console.

### Observed/Actual behavior

Commands executed by the player or console are executed with vanilla commands taking precedence over aliases.

### Steps/models to reproduce

```
public final class PaperPluginExample extends JavaPlugin {
    @Override
    public void onEnable() {
        getLifecycleManager().registerEventHandler(LifecycleEvents.COMMANDS, event -> {
            final var command = Commands.literal("msg")
                    .executes(context -> {
                        context.getSource().getSender().sendMessage("test");
                        return Command.SINGLE_SUCCESS;
                    }).build();
            event.registrar().register(command, List.of("tell", "w"));
        });
    }
}
```

### Plugin and Datapack List

[01:26:28 INFO]: Server Plugins (2):
[01:26:28 INFO]: Paper Plugins:
[01:26:28 INFO]:  - PaperPluginExample
[01:26:28 INFO]: Bukkit Plugins:
[01:26:28 INFO]:  - LuckPerms

### Paper version

[01:27:06 INFO]: This server is running Paper version 1.21-46-master@2fa5e0e (2024-07-06T21:32:48Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-44-8d91b85 (MC: 1.21)

### Other
![image](https://github.com/PaperMC/Paper/assets/53502121/f6a0afd3-eb65-4fc6-97cb-7684efeb13f5)

log
https://pastes.dev/w0RfWFOgUN

This bug occurs even if the command is registered during bootstrapping.
Also, this bug does not occur with BukkitCommandAPI.
https://github.com/PaperMC/Paper/pull/11011 may have something to do with it.

**Comment by quiquelhappy** [comment] 2024-07-09 21:41
we are having issues with this too. it is very annoying.

**Comment by Emibergo02** [comment] 2024-07-09 22:17
Me too

**Comment by TheosisOfficial** [comment] 2024-07-25 07:51
Also experiencing this, would be great to have fixed soon!

**Comment by NamiUni** [comment] 2024-07-25 11:32
Since it may be challenging to identify or fix the cause of the issue, please try not to put too much pressure on the developers. Thank you for your understanding. :)

**Comment by Folas1337** [comment] 2024-07-25 11:45
> Since it may be challenging to identify or fix the cause of the issue, please try not to put too much pressure on the developers. Thank you for your understanding. :)

While I strongly agree with this point, I also think we should still show how much of an impact this is really having by respectfully stating that we're affected by it.

Definitely do not pressure the lovely devs who make this awesome software who should be praised for it BUT still **respectfully** say you're affected and would like to see this fixed. At least that's my opinion and I just wanted to share it :)

**Comment by Technofied** [comment] 2024-07-26 05:39
We're experiencing this issue too. :(

**Comment by jpenilla** [comment] 2024-07-28 20:20
Please test the build linked in PR #11186

**Comment by Folas1337** [comment] 2024-07-29 17:02
I tested it with Carbon and it seems to be working fine :)
From my point of view, who was originally the one complaining and @NamiUni was the one who reproduced it and then reported it here, this is looking good but we can also get Nami to verify with the thing they created to be absolutely sure and then hopefully get this merged soon(ish) :)

**Closed as completed** 2024-07-30 18:28 UTC
Labels: type: bug, status: accepted, version: 1.21
