### ISSUE TITLE
Importing old flatworld causes NullPointers/scary chunk corruption during data migration

### ISSUE THREAD

**Issue by bergerkiller** [PaperSpigot/Paper#7131] opened 2021-12-16 17:30 UTC
### Stack trace

[Here is my log file with all the error spam](https://paste.gg/p/anonymous/b7444519ff77498abcc4e56dfec00bad)

Relevant snippet:
```
[18:14:58] [Server thread/INFO]: bergerkiller issued server command: /tp bergerkiller 753 21 553
[18:14:58] [Server thread/INFO]: [bergerkiller: Teleported bergerkiller to 753.500000, 21.000000, 553.500000]
[18:14:58] [Paper Async Chunk Task Thread #2/ERROR]: No key placement in MapLike[{config:{},name:"minecraft:plain_flower"}]; No key feature in MapLike[{config:{},name:"minecraft:plain_flower"}]
[18:14:58] [Paper Async Chunk Task Thread #0/ERROR]: Could not apply datafixers for chunk task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'testworld_flat', (46,36), hashcode:1043210708, priority: -1
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832.createBiomeSection(V2832.java:836) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832.createBiomeSections(V2832.java:811) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832$2.convert(V2832.java:391) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832$2.convert(V2832.java:371) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:79) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:13) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convert(MCDataConverter.java:79) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convertTag(MCDataConverter.java:40) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.world.level.chunk.storage.ChunkStorage.upgradeChunkTag(ChunkStorage.java:115) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:94) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-77]
[18:14:58] [Paper Async Chunk Task Thread #2/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:790) ~[?:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:363) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-77]
[18:14:58] [Paper Async Chunk Task Thread #0/ERROR]: Chunk file at [46, 36] is in the wrong location; relocating. (Expected [46, 36], got [0, 0])
[18:14:58] [Paper Async Chunk Task Thread #1/ERROR]: Could not apply datafixers for chunk task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'testworld_flat', (45,36), hashcode:149428143, priority: -1
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832.createBiomeSection(V2832.java:836) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832.createBiomeSections(V2832.java:811) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832$2.convert(V2832.java:391) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832$2.convert(V2832.java:371) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:79) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:13) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convert(MCDataConverter.java:79) ~[paper-1.18.1.jar:git-Paper-77]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convertTag(MCDataConverter.java:40) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.world.level.chunk.storage.ChunkStorage.upgradeChunkTag(ChunkStorage.java:115) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:94) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-77]
[18:14:58] [Paper Async Chunk Task Thread #1/ERROR]: Chunk file at [45, 36] is in the wrong location; relocating. (Expected [45, 36], got [0, 0])
[18:14:58] [Paper Async Chunk Task Thread #0/ERROR]: Could not de-serialize chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'testworld_flat', (46,36), hashcode:1043210708, priority: -1
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.chunk.ChunkStatus.b(net.minecraft.world.level.chunk.ChunkStatus)" because the return value of "net.minecraft.world.level.chunk.storage.ChunkRegionLoader.getStatus(net.minecraft.nbt.NBTTagCompound)" is null
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:149) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-77]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-77]
```

### Plugin and Datapack List

Plugins (10): BKCommonLib, LightAPI, LightCleaner, Maplands, My_Worlds, SignLink, spark, TCCoasters, Train_Carts, WorldEdit

### Actions to reproduce (if known)

Download the world: https://ci.mg-dev.eu/stash/testworld_flat.zip

Load the world and move/teleport to these far-away coordinates, which likely contain old chunk data:
`/tp yourname 753 21 553`

### Paper version

This server is running Paper version git-Paper-77 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5ad1d9a)

### Other

This is a world used without problems on Paper 1.16.2, and imports and loads fine on Paper 1.16.5.

This is an old flat test world I've been using for a very long time. It seems to have accumulated a lot of chunk errors over the years. However, loading this world on 1.16.5 logs no errors at all, teleporting to those coordinates. On 1.18.1 there are tonnes of errors. I have not noticed any chunk corruption, but that could just be because its a desolate flat world with only villages in the far reaches.

If you need more info from me or such do @ me on Discord, I dont track the github notifications too much

**Comment by menelmir** [comment] 2021-12-16 23:24
Hello,
I have a similar issue (I don't know if it's exactly the same, but it seems to). But my world is not a flat world.
I use only Multiverse-Core 4.3.2-SNAPSHOT-867 (some others, but even while disabling all of them, I still have the issue), on "Paper version git-Paper-"5ad1d9a" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5ad1d9a)"
I have 4 worlds (with their nether and the_end each), only this one is buggy, but not its nether world.
This world is newer than the others whitch are very olds, I don't rembember what is its "native" version.
In 1.17.1, all is going well, but as soon I try to update to 1.18.1, I have this issue.

I can transfer a zip of the world on demand (it's a small world (sorry)).

Here is a part of my stacktrace, full stacktrace the file :
[fullstacktrace.txt](https://github.com/PaperMC/Paper/files/7731014/fullstacktrace.txt)

[00:02:55] [Paper Async Chunk Task Thread #0/ERROR]: Could not apply datafixers for chunk task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'worldname', (-58,-1), hashcode:1995813055, priority: -1
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832.createBiomeSection(V2832.java:836) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832.createBiomeSections(V2832.java:811) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832$2.convert(V2832.java:391) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832$2.convert(V2832.java:371) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:79) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:13) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convert(MCDataConverter.java:79) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convertTag(MCDataConverter.java:40) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at net.minecraft.world.level.chunk.storage.ChunkStorage.upgradeChunkTag(ChunkStorage.java:115) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:94) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
[00:02:55] [Paper Async Chunk Task Thread #1/ERROR]: Could not apply datafixers for chunk task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'worldname', (-58,-2), hashcode:1601565789, priority: -1
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832.createBiomeSection(V2832.java:836) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832.createBiomeSections(V2832.java:811) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832$2.convert(V2832.java:391) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2832$2.convert(V2832.java:371) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:79) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:13) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convert(MCDataConverter.java:79) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convertTag(MCDataConverter.java:40) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at net.minecraft.world.level.chunk.storage.ChunkStorage.upgradeChunkTag(ChunkStorage.java:115) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:94) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
[00:02:55] [Paper Async Chunk Task Thread #0/ERROR]: Chunk file at [-58, -1] is in the wrong location; relocating. (Expected [-58, -1], got [0, 0])
[00:02:55] [Paper Async Chunk Task Thread #0/ERROR]: Could not de-serialize chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'worldname', (-58,-1), hashcode:1995813055, priority: -1
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.chunk.ChunkStatus.b(net.minecraft.world.level.chunk.ChunkStatus)" because the return value of "net.minecraft.world.level.chunk.storage.ChunkRegionLoader.getStatus

(net.minecraft.nbt.NBTTagCompound)" is null
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:149) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
[00:02:55] [Paper Async Chunk Task Thread #1/ERROR]: Chunk file at [-58, -2] is in the wrong location; relocating. (Expected [-58, -2], got [0, 0])
[00:02:55] [Paper Async Chunk Task Thread #1/ERROR]: Could not de-serialize chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'worldname', (-58,-2), hashcode:1601565789, priority: -1
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.chunk.ChunkStatus.b(net.minecraft.world.level.chunk.ChunkStatus)" because the return value of "net.minecraft.world.level.chunk.storage.ChunkRegionLoader.getStatus

(net.minecraft.nbt.NBTTagCompound)" is null
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:149) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
[00:02:55] [Paper Async Chunk Task Thread #1/ERROR]: Failed to execute chunk load task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'worldname', (-58,-2), hashcode:1601565789, priority: -1
java.lang.IllegalStateException: Expected this task to be scheduled, but another was! Other: null, current: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'worldname', (-58,-2), hashcode:1601565789, 

priority: -1
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.lambda$complete$1(ChunkLoadTask.java:124) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1955) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.complete(ChunkLoadTask.java:122) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:110) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
[00:02:55] [Paper Async Chunk Task Thread #0/ERROR]: Failed to execute chunk load task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'worldname', (-58,-1), hashcode:1995813055, priority: -1
java.lang.IllegalStateException: Expected this task to be scheduled, but another was! Other: null, current: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'worldname', (-58,-1), hashcode:1995813055, 

priority: -1
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.lambda$complete$1(ChunkLoadTask.java:124) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1955) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.complete(ChunkLoadTask.java:122) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:110) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-"5ad1d9a"]
.....................

Thanks.

**Comment by molor** [comment] 2021-12-17 10:37
Here's something related to datafixers too, got tons of this exceptions while loading world (1.17.1 -> 1.18.1) via Chunky:
https://paste.gg/p/anonymous/10f6e66007174dbbbce257b75e6c1e3a

**Comment by electronicboy** [comment] 2021-12-17 10:40
This issue is for an explict scenario, your paste there molor seems unrelated to this one

**Comment by menelmir** [comment] 2021-12-17 12:16
> This issue is for an explict scenario, your paste there molor seems unrelated to this one

The errors in the log are similar, and are caused by same behavior : old chunks loading, in a way or another ;)

**Comment by Spottedleaf** [comment] 2021-12-17 14:41
https://github.com/PaperMC/Paper/commit/5b5f0aa6c8fe2bd66f91098d7980e63266d6d3b7
Will fix the conversion problem, however there is a clear failure with the I/O system that's caused it to pass an empty NBTTagCompound into the read result, so this will remain open.

**Comment by Spottedleaf** [comment] 2021-12-17 14:58
Second part resolved by https://github.com/PaperMC/Paper/commit/4b0b72554fe15c2cc4727b4d78e2deb4bca98848

Let me know if you see anything like this on the latest paper builds now.

**Closed as completed by Spottedleaf** 2021-12-17 14:58 UTC

**Comment by menelmir** [comment] 2021-12-17 19:06
It's seems to be fixed for me, except one error which apparead only once after applied patches (it disappeared from subsequent reboots), here is the stacktrace :

[19:51:19] [Paper Async Chunk Urgent Task Thread/ERROR]: Could not apply datafixers for chunk task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'worldname', (-32,24), hashcode:1156171964, priority: -1
java.lang.NullPointerException: Cannot invoke "ca.spottedleaf.dataconverter.types.MapType.hasKey(Object)" because "level" is null
	at ca.spottedleaf.dataconverter.minecraft.versions.V2842$1.convert(V2842.java:25) ~[paper-1.18.1.jar:git-Paper-"4b0b725"]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2842$1.convert(V2842.java:17) ~[paper-1.18.1.jar:git-Paper-"4b0b725"]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:79) ~[paper-1.18.1.jar:git-Paper-"4b0b725"]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:13) ~[paper-1.18.1.jar:git-Paper-"4b0b725"]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convert(MCDataConverter.java:79) ~[paper-1.18.1.jar:git-Paper-"4b0b725"]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convertTag(MCDataConverter.java:40) ~[paper-1.18.1.jar:git-Paper-"4b0b725"]
	at net.minecraft.world.level.chunk.storage.ChunkStorage.upgradeChunkTag(ChunkStorage.java:115) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:94) ~[paper-1.18.1.jar:git-Paper-"4b0b725"]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-"4b0b725"]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-"4b0b725"]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-"4b0b725"]
	
Thanks for the fixes you made :D

**Comment by Spottedleaf** [comment] 2021-12-17 19:22
Do you have the world data that produces that error?

**Comment by bergerkiller** [comment] 2021-12-25 20:09
I retested the initial flat world with Paper #101. There are still errors, but the number of them has greatly reduced. So I think the main problem is now fixed.

https://paste.gg/p/anonymous/dacd284d77d144f7968d734a944c7ffd
