### ISSUE TITLE
Cancelling EntityShootBowEvent does not cancel the shooting sound

### ISSUE THREAD

**Issue by FoPzl** [PaperSpigot/Paper#11596] opened 2024-11-08 21:08 UTC
### Expected behavior

No bow shoot sound heard.

### Observed/Actual behavior

Bow shoot sound heard for players shooting both bows and crossbows, piglins shooting crossbows, and pillagers shooting crossbows. No bow shoot sound heard for skeletons and strays shooting bows.

### Steps/models to reproduce

Create a handler to cancel the event:
```
@EventHandler
public void onShoot(EntityShootBowEvent e) {
    e.setCancelled(true);
}
```
Shoot bow or crossbow, or get mob to shoot.

### Plugin and Datapack List

None (tested in isolation)

### Paper version

1.21.3-14

**Comment by electronicboy** [comment] 2024-11-08 21:14
The call for playing some of these sounds looks to have been moved into methods called before the event is fired, this will require a bit of shuffling

**Comment by FaMa91** [comment] 2024-11-09 23:11
Additionally there is a graphic glich. It seems it consumes an arrow, but when you click on the stack the number go back.
Is it possible to avoid this glitch too?

**Comment by kashike** [comment] 2024-11-11 17:59
Duplicate of #10665.

**Closed as not planned by kashike** 2024-11-11 17:59 UTC
Labels: type: bug, resolution: duplicate
