### ISSUE TITLE
Entity#playEffect does not work with EntityEffect.HURT

### ISSUE THREAD

**Issue by chasertw123** [PaperSpigot/Paper#9022] opened 2023-03-21 21:38 UTC
### Is your feature request related to a problem?

With 1.19.4 MC seems to have started to just silently ignore the Hurt EntityEffect. They seem to have replaced it with a new Packet (ClientboundHurtAnimationPacket). 

### Describe the solution you'd like.

I'd perferably like to see the EntityEffect.HURT deprecated. Then add in a new function on LivingEntity to utilize the new yaw option in said new packet.

### Describe alternatives you've considered.

Additionally even though deprecated functionally could be restored to the EntityEffect.HURT with it just getting a random yaw as it use to.

**Comment by Xander-de-Keijzer** [comment] 2023-03-22 19:51
Related to/duplicate of #8988

**Comment by CJCrafter** [comment] 2023-05-22 02:24
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#sendHurtAnimation(float)

For anyone who stumbles upon this thread.

**Comment by Warriorrrr** [comment] 2023-08-14 23:59
Implemented by upstream in https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/01aa02eb531ba554701b02986193c874ccb7635d

**Closed as completed by Warriorrrr** 2023-08-14 23:59 UTC
Labels: type: feature
