### ISSUE TITLE
Player.setSaturatedRegenRate() and Player.setUnsaturatedRegenRate() do not work consistently

### ISSUE THREAD

**Issue by JWartofsky3** [PaperSpigot/Paper#6678] opened 2021-09-29 04:37 UTC
### Expected behavior

Setting the saturatedRegenRate and unsaturatedRegenRate consistently alters the players health regeneration rate

### Observed/Actual behavior

Setting the regen rate works when combined with a PlayerJoinEvent, but not with a PlayerRespawnEvent

Expected behavior is that it should work in both cases

### Steps/models to reproduce

Use a simple plugin that sets the saturatedRegenRate and unsaturatedRegenRate on player join and on player respawn. 

In both cases, the message prints indicating that the fields were both set. On joining the server, the slower health regen takes effect. On respawn, the message is printed but the vanilla behavior is used

Here's the code for the simple plugin I used. I can send the jar file if that is helpful:

```

public class SetRegenRateBug extends JavaPlugin implements Listener {

    final static int HEALTH_REGEN_DELAY = 180;

    @Override
    public void onEnable() {
        this.getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public static void onPlayerRespawnEvent(PlayerRespawnEvent playerRespawnEvent) {
        setPlayerHungerRates(playerRespawnEvent.getPlayer());
    }

    @EventHandler
    public static void onPlayerJoinEvent(PlayerJoinEvent playerJoinEvent) {
        setPlayerHungerRates(playerJoinEvent.getPlayer());
    }

    private static void setPlayerHungerRates(Player player) {
        player.setSaturatedRegenRate(HEALTH_REGEN_DELAY);
        player.setUnsaturatedRegenRate(HEALTH_REGEN_DELAY);
        JavaPlugin.getPlugin(SetRegenRateBug.class).getServer().getConsoleSender().sendMessage("Set regen rate to " + HEALTH_REGEN_DELAY);
    }
}
```

### Plugin list

No plugins are used other than the example plugin above

### Paper version

This server is running Paper version git-Paper-281 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f7e3976)
You are running the latest version
Previous version: git-Paper-255 (MC: 1.17.1)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

I have a small example plugin that shows just this issue, but there doesn't seem to be a way to add attachments

All of the relevant code is under steps to reproduce

**Comment by JWartofsky3** [comment] 2021-09-29 05:25
On further note, if you set a delay with a runnable when using the player respawn event, setting the regenRate works consistently

**Comment by imDaniX** [comment] 2021-09-29 13:59
I think you should use [`PlayerPostRespawnEvent`](https://papermc.io/javadocs/paper/1.17/com/destroystokyo/paper/event/player/PlayerPostRespawnEvent.html) instead.

**Comment by Machine-Maker** [comment] 2021-09-29 18:40
Yes, the player is "reset" after respawn (which is after the PlayerRespawnEvent) which resets quite a bit about the player including the `FoodData` of which that is a part of. @imDaniX's solution is probably the right answer, closing this as works as intended.

**Closed as completed** 2021-09-29 18:40 UTC
Labels: resolution: works as intended, version: 1.17
