### ISSUE TITLE
Server Crash (unsure what's caused)

### ISSUE THREAD

**Issue by RealPengtastic** [PaperSpigot/Paper#8290] opened 2022-08-13 23:04 UTC
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://paste.gg/p/anonymous/284d277ecebe4a9b9b68efb3c3c2850a/files/e1ceaea5f0c2486888e894593f5b1e5a/raw

### Plugin and Datapack List

[22:52:23 INFO]: Plugins (6): CoreProtect, CraftEnhance, dynmap, GrimAC, ViaBackwards, ViaVersion

### Actions to reproduce (if known)

Could be caused by ticking tile entities or the outdated map (1.17.1)

### Paper version

[22:54:40 INFO]: This server is running Paper version git-Paper-111 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 02831e3)
You are running the latest version
Previous version: git-Paper-81 (MC: 1.19)

### Other

I am unsure how it's caused and I don't know how to fix it.

**Comment by electronicboy** [comment] 2022-08-15 20:03
Duplicate of #2312
for quick ref, https://paper-chan.moe/paper-optimization ctrl-f "treasure"

**Closed as not planned by electronicboy** 2022-08-15 20:03 UTC
Labels: resolution: duplicate
