### ISSUE TITLE
end gateway can't teleport entities riding on other entities

### ISSUE THREAD

**Issue by Amotassic** [PaperSpigot/Paper#9697] opened 2023-09-09 15:18 UTC
### Expected behavior

Entities riding other entities should teleport without issues by end gateway within the same world.

### Observed/Actual behavior

Entities riding other entities can't teleport.

### Steps/models to reproduce

![屏幕截图 2023-09-09 230022](https://github.com/PaperMC/Paper/assets/125993576/be0de101-b50c-4935-9417-d12270d442a5)

### Plugin and Datapack List

Server Plugins (0):

[23:16:47 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[23:16:47 INFO]: There are no more data packs available

### Paper version

[23:17:37 INFO]: Checking version, please wait...
[23:17:38 INFO]: This server is running Paper version git-Paper-171 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 33bec7f)
You are running the latest version

**Comment by lynxplay** [comment] 2023-09-09 15:18
Duplicate of #9172

**Closed as not planned by lynxplay** 2023-09-09 15:18 UTC
Labels: type: bug, resolution: duplicate
