### ISSUE TITLE
Zombie Pigmen spawn in Basalt Deltas

### ISSUE THREAD

**Issue by Gurrarr** [PaperSpigot/Paper#10251] opened 2024-02-14 12:56 UTC
### Expected behavior

Zombie pigmen shouldn't be allowed to spawn in Basalt Deltas

### Observed/Actual behavior

Zombie Pigmen spawn in Basalt Deltas

### Steps/models to reproduce

Build platform in Basalt Deltas, mine was 20x20 out of nether brick but quite sure it can be built from anything with any size.
Confirm entire platform is within Basalt Delta biome. Zombie Pigmen spawn.

### Plugin and Datapack List

MinehutPlugin, TreeCapitator, ViaVersion

### Paper version

Paper version git-Paper-409 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e171ef)

**Comment by Warriorrrr** [comment] 2024-02-14 13:19
After setting up a platform in a basalt deltas biome, placing a command block to kill anything other than players and zombified piglins and setting the tick rate to 10000, I wasn't able to see any zombified piglins spawning on the platform. Unless you have other reproduction steps I'll have to close this as unable to reproduce

**Comment by Gurrarr** [comment] 2024-02-15 13:41
Oh thats strange, okay, thank you for letting me know, I'll see if I can
reset the server completely

**Comment by lynxplay** [comment] 2024-07-05 22:53
Closing this as it has been stale.

**Closed as not planned by lynxplay** 2024-07-05 22:53 UTC
Labels: type: bug, resolution: awaiting response
