### ISSUE TITLE
ArmorStand#setGravity also changes NoPhysics, allowing the armor stand to no clip through blocks

### ISSUE THREAD

**Issue by Toseflo** [PaperSpigot/Paper#11388] opened 2024-09-10 19:19 UTC
### Expected behavior

Using Entity#setGravity should only change the gravity value of the entity.

### Observed/Actual behavior

Setting the gravity of an armor stand to false also changes noPhysics to true. This allows the armor stand to be pushed through blocks.

### Steps/models to reproduce

1. Use the method Entity#hasNoPhysics() on an armor stand. It should return false.
2. Use the method Entity#setGravity(false) on the armor stand.
3. Check the noPhysics value again, it should now be true.
4. You can now push the armor stand with a piston through blocks

### Plugin and Datapack List

Only a test plugin to set the gravity and get the physics value. No datapacks

### Paper version

This server is running Paper version 1.21.1-76-master@e945cfe (2024-09-10T17:56:53Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-69-925c3b9 (MC: 1.21.1)

**Comment by Machine-Maker** [comment] 2024-09-10 19:48
What happens if you call setNoPhysics(false) after setting the gravity?

**Comment by Toseflo** [comment] 2024-09-10 20:14
With setNoPhysics(false), both values are false. But after a reload, NoPhysics is true again.

**Comment by Machine-Maker** [comment] 2024-09-10 20:17
>  But after a reload, NoPhysics is true again.

Oh ok. So in vanilla, this is also true.
![image](https://github.com/user-attachments/assets/bf0969de-1efe-4d22-b03b-efbd2787b04a)
![image](https://github.com/user-attachments/assets/d6624b07-ed70-47a7-971f-f6b794caa84b)

The first image is from the load method for armor stands (all vanilla). The noPhysics flag is set by that method. And the second image shows the impl of that image. If the stand has no gravity, it also has no physics.

**Comment by Toseflo** [comment] 2024-09-10 20:25
Oh, you are right. I tested it in vanilla and there armor stands without gravity can also be pushed into blocks. Didn't know that this is possible.
So I guess this issue can be closed, since this is the vanilla behavior?

**Comment by Machine-Maker** [comment] 2024-09-10 20:27
> So I guess this issue can be closed, since this is the vanilla behavior?

If you can find a vanilla issue that talks about this that's confirmed as an issue, we can re-open this, but for now I'll close it as works-as-intended.

**Closed as not planned by Machine-Maker** 2024-09-10 20:27 UTC
Labels: type: bug, resolution: works as intended, version: 1.21.1
