### ISSUE TITLE
piston cant push minecart and rail

### ISSUE THREAD

**Issue by NBS-Paste** [PaperSpigot/Paper#8709] opened 2022-12-22 02:45 UTC
### Expected behavior

pistion to push minecart and rail together

### Observed/Actual behavior

piston only pushed rail

### Steps/models to reproduce

power piston

### Plugin and Datapack List

Plugins (15): ChunkLoader, Chunky, DeadChest, DynDeath, dynmap, floodgate, Geyser-Spigot, HeadsPlus, HiddenArmor, Mapify, ProtocolLib, SilkSpawners_v2, VeinMiner, WorldEdit, WorldGuard

 There are 13 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/explosiondropsall (world)], [file/anti ghast grief v1.1.3 (world)], [file/anti enderman grief v1.1.3 (world)], [file/custom nether portals v2.3.6 (world)], [file/durability ping v1.1.3 (world)], [file/nether portal coords v1.1.3 (world)], [file/back to blocks (world)], [file/more trapdoors data pack (world)], [file/spawning spheres v1.1.3 (world)], [file/merge-xp (world)], [file/anti enderman grief v1.1.3.zip (world)]

### Paper version

: This server is running Paper version git-Paper-349 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 7b52db5)
You are running the latest version
Previous version: git-Paper-340 (MC: 1.19.3)

**Comment by Owen1212055** [comment] 2022-12-29 01:13
Can you please include a picture/video of what we're supposed to be looking at here?

**Comment by NBS-Paste** [comment] 2022-12-29 01:20
https://youtu.be/ToFsSXhHbxs

9:53 is what should happen.
What actually happens is the rail just gets pushed and not the minecart.
It used to work as well. No pictures of it working sorry.

**Comment by Owen1212055** [comment] 2022-12-29 01:34
https://user-images.githubusercontent.com/23108066/209892167-f9d18efc-caee-466a-864b-c9e78d6248e8.mp4

I'm not able to reproduce this.

**Comment by NBS-Paste** [comment] 2022-12-29 01:35
I’ll try it again but I did notice you weren’t using a detector rail.

**Comment by lynxplay** [comment] 2023-07-08 12:26
Given the fact this seems to not be replicable and no further replication steps were given, I'll close this issue.
If anyone can provide replication steps, feel free to post here so I can reopen the issue :)

**Closed as not planned** 2023-07-08 13:48 UTC
Labels: type: bug, resolution: cannot reproduce
