### ISSUE TITLE
Hoglins despawn when going through nether portal

### ISSUE THREAD

**Issue by n0rbyt3** [PaperSpigot/Paper#6632] opened 2021-09-20 16:32 UTC
### Expected behavior

Putting a hoglin onto a lead and moving it through a nether portal should let it appear in the overworld.

### Observed/Actual behavior

The lead drops in the nether, the hoglin despawns immediately.

### Steps/models to reproduce

- Go to the nether
- Use a lead on a hoglin
- Let the hoglin move through the nether portal

### Plugin list

Chunky, OpenInv

### Paper version

This server is running Paper version git-Paper-266 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0d19cd7)

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

### Other

It is possible to move pigs with a lead from the overworld to the nether. It is also possible to put minecards through nether portals and they won't despawn in the overworld.

Workaround for the hoglins: use a nametag on it.

**Comment by NoahvdAa** [comment] 2021-09-20 16:42
Can't reproduce on the same version.
```
This server is running Paper version git-Paper-266 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0d19cd7)
You are running the latest version
Previous version: null (MC: 1.17.1)
```

**Comment by n0rbyt3** [comment] 2021-09-20 17:13
Hmm... my server ia running on a Raspberry Pi 4 (4GB RAM). The Paper process has 3GB assigned. Maybe a hardware related issue?

Did you set the nether portal far away from the overworld spawn? Even if I go to the nether portal before to load the chunk in the overworld, the hoglin is despawned immediately and the lead drops.

**Comment by NoahvdAa** [comment] 2021-09-20 17:35
I made a nether portal around spawn on a flat world, will try again with different conditions in a bit.

**Comment by Prof-Bloodstone** [comment] 2021-09-25 19:20
I'm also unable to reproduce on latest. Do you have other people in overworld? Could you provide more details on exactly what you do?

Closing for now as cannot reproduce, but can reopen if needed.

**Closed as completed by Prof-Bloodstone** 2021-09-25 19:20 UTC
Labels: resolution: cannot reproduce, version: 1.17

**Comment by n0rbyt3** [comment] 2021-09-26 08:20
@Prof-Bloodstone I have tested it again today with Paper-278 and I cannot reproduce it anymore. Either I was blind because the hoglins did spawn on a small hill in the overworld or it really didn't work. However, it works as expected now. Thanks for your investigation! :)

**Comment by nsde** [comment] 2022-01-01 20:24
I have the same problem. On Paper #101 1.18.1. The log shows nothing at all.

**Comment by nsde** [comment] 2022-01-01 20:25
And no I don't have peaceful enabled.
