### ISSUE TITLE
Generating end world does not spawn new dragon

### ISSUE THREAD

**Issue by DzXAnt22** [PaperSpigot/Paper#9627] opened 2023-08-19 02:25 UTC
### Expected behavior

When deleting end world and restarting the server, there should be a new dragon along with the newly generated end world.

### Observed/Actual behavior

The end world restarts, but no dragon spawned.

### Steps/models to reproduce

Delete "world_the_end" folder and restart server.

### Plugin and Datapack List

none

### Paper version

This server is running Paper version git-Paper-"307d05b" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 307d05b)

**Comment by CodeByCam** [comment] 2023-08-19 03:15
Hey DzXAnt22, I'm unable to reproduce this. I see you've been discussing this in Discord too, so I'll close this ticket as it doesn't seem to be a Paper issue and we can continue discussing it on Discord.

**Closed as completed by CodeByCam** 2023-08-19 03:15 UTC
Labels: type: bug, resolution: works as intended
