### ISSUE TITLE
Terrain loading issue

### ISSUE THREAD

**Issue by Baggette** [PaperSpigot/Paper#7691] opened 2022-04-02 19:51 UTC
### Expected behavior

Terrain to load properly 

### Observed/Actual behavior

upon logging in terrain is invisible and sometimes requires a relog for it to be loaded in

### Steps/models to reproduce

join a server running papermc 1.18.2 and it'll sometimes happen upon logging in or loading chunks. (I haven't had this issue with 1.18.1)

### Plugin and Datapack List

(I have had this issue on a server of a friend of mines as well)
`Plugins (20): AdvancedTeleport, AuthMe, CoreProtect, DiscordSRV, Essentials, floodgate, Geyser-Spigot, GriefPrevention, LuckPerms, MineableSpawners, Multiverse-Core, Multiverse-Inventories, Paintball, PlaceholderAPI, ProtocolLib, SilkTouchAmethyst, SkinsRestorer, TAB, VoidGenerator*, WorldEdit`
**my friends server**
https://media.discordapp.net/attachments/889222518085386302/959901404275814470/unknown.png

### Paper version

`This server is running Paper version git-Paper-276 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: ea2c81e)
You are running the latest version
Previous version: git-Paper-274 (MC: 1.18.2)`
**my friends server**
https://media.discordapp.net/attachments/889222518085386302/959901474706583632/unknown.png

**Comment by molor** [comment] 2022-04-15 08:27
Maybe this is what it looks like in the game — I have also encountered this several times after joining
"Empty" chunk is always the chunk where the player is spawned

![2022-04-15_11 26 01](https://user-images.githubusercontent.com/19989717/163546188-b68304a2-f8c3-49e0-abc4-6066ffc06723.png)

Mobs walk in this chunk as usual, so I think that chunk was loaded on server side and that's a client render bug, but I'm not sure. Relogin solves that issue

**Comment by Malfrador** [comment] 2022-04-15 17:32
Is the server checking for collision in the bugged chunks? If you can move around or if you are falling through the terrain it is not checking for collision.

Also, how does your MSPT look like (/mspt)? This can sometimes happen if the server is lagging or close to lagging. 

If collision is working and MSPT are fine, the chunk is loaded on the server and something went wrong with sending it. In this case the issue sounds awfully similar to https://github.com/PaperMC/Paper/issues/4679 which should have been fixed by the Tuinity merge a while ago (and was just recently closed because of that).

**Comment by electronicboy** [comment] 2022-04-15 17:33
server sends an empty chunk on login, entities in the chunk would suggest that it's loaded by the client in some form of capacity, can you reproduce on a fully vanilla client?

**Comment by molor** [comment] 2022-04-15 17:35
In my case it's vanilla
("Sadness" server is Paper, we just hid the server brand name from other players this time)

![image](https://user-images.githubusercontent.com/19989717/163602609-d322414e-a7e0-4ab2-9957-0108268f4c29.png)

**Comment by NoahvdAa** [comment] 2022-08-06 23:39
Sounds like this was fixed in d1e1217, since the affected chunk here is whatever chunk you were standing in while joining. If you can still reproduce this issue on a supported version (at the time of writing, 1.19), please comment or open a new issue.

**Closed as completed by NoahvdAa** 2022-08-06 23:39 UTC
Labels: type: bug

**Comment by molor** [comment] 2022-08-07 07:36
Is there any chance that this very annoying bug will be fixed in 1.18.2?
Some servers still can't update to 1.19 ):

**Comment by electronicboy** [comment] 2022-08-07 07:40
1.18.2 is basically EOL, maybe it might be backported in the final "shove this branch to it's death", but, 0 promises or commitments there
