### ISSUE TITLE
Crash with BlockTracker

### ISSUE THREAD

**Issue by Krakenied** [PaperSpigot/Paper#11056] opened 2024-07-11 08:56 UTC
### Stack trace

https://pastes.dev/1efChsblav

### Plugin and Datapack List

BlockTracker - https://cdn.modrinth.com/data/gOtvzAQX/versions/m1gTN0dL/BlockTracker-1.0.6.jar

### Actions to reproduce (if known)

- No server config changes.
- Place random 5 blocks (creative is allowed) in a chunk which can be unloaded
- Leave the server
- Don't stop it - wait 10 seconds for chunk unload

### Paper version

```
> ver
[10:50:07 INFO]: Checking version, please wait...
[10:50:07 INFO]: This server is running Paper version 1.21-50-master@20889d0 (2024-07-10T16:28:03Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
```

### Other

Works correctly on latest Paper 1.20.6 build no. 148 using the same plugin version.

BlockTracker related code: https://github.com/Krakenied/BlockTracker/blob/7135f65791da04b91d4ceb1f7f5e05c36d00fb01/src/main/java/dev/krakenied/blocktracker/bukkit/BukkitListener.java#L147-L151

Original issue: https://github.com/Krakenied/BlockTracker/issues/1

**Comment by lynxplay** [comment] 2024-07-11 08:58
Duplicate of #10900

**Closed as not planned by lynxplay** 2024-07-11 08:58 UTC
Labels: type: bug, resolution: duplicate, version: 1.21
