### ISSUE TITLE
1.18 upgrade breaks portal links

### ISSUE THREAD

**Issue by schnism** [PaperSpigot/Paper#7419] opened 2022-01-28 23:24 UTC
### Expected behavior

Portals linked in 1.17 are still linked in 1.18

### Observed/Actual behavior

On first entering of a portal in nether side after update to 1.18 a new portal is generated and the existing one is ignored. When the new one is destroyed the old one works as before in both directions

### Steps/models to reproduce

* Run paper-1.17.1-408.jar in a completely new world
* Enter nether, tp to 1000 ~ 1000
* build a portal 
* enter overworld
* tear down portal and rebuild some blocks away
* Both portals are linked no matter what direction.
* Stay in nether

* Shutdown server, run paper-1.18.1-177.jar
* Enter the portal from nether side
==> Existing portal not used, new portal build at old position, directly besides your moved one
* tear down new one
* Both work as before 

### Plugin and Datapack List

None, reproducible in bare bones setup

### Paper version

This server is running Paper version git-Paper-177 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 2e99e5e)
You are running the latest version
Previous version: git-Paper-408 (MC: 1.17.1)

### Other

Might be related to https://github.com/PaperMC/Paper/issues/7145, as the chunk is somehow invalid as never entered yet in 1.18 yet, so portal is not found.

Maybe logic needs to be changed in order (find portal vs. convert chunk)

**Comment by NoahvdAa** [comment] 2022-01-28 23:28
This seems to be a duplicate of #6995.

**Comment by schnism** [comment] 2022-01-28 23:34
> This seems to be a duplicate of #6995.

I had a look at https://github.com/PaperMC/Paper/issues/6995 before but this seems to be rather related to Muliverse and was confirmed solved without Multiverse.

This here can be reproduced in a bare lab without any plugins.

**Comment by lynxplay** [comment] 2022-02-03 00:17
I can reproduce this :+1: and hence went on a bit of a code review tour:

The high level cause of this (or at least I believe it to be) is [this](https://github.com/PaperMC/Paper/blob/master/patches/server/0744-Optimise-general-POI-access.patch#L971) poi access optimization. While it in general works great (and makes sense), the chunk upgrade process from 1.17 to 1.18 has an unwanted effect on this.

The data converter, when converting chunks from 1.17 to 1.18 in the overworld, resets their `Status` from `full` to `empty`, allowing the new world generation (e.g. below-bedrock etc) to take place. 
See [the dataconverter patch, `ca.spottedleaf.dataconverter.minecraft.versions.V2832.updateChunkData`](https://github.com/PaperMC/Paper/blob/master/patches/server/0775-Rewrite-dataconverter-system.patch). Hence, the previously mentioned optimization interprets the chunk as an empty chunk and skips POI lookups for it, which produces the reported result: 

No POI is found for the portal -> A new portal is created.

**Comment by Spottedleaf** [comment] 2022-02-03 00:34
Likely caused by https://github.com/PaperMC/Paper/blob/79dd62ae620c082646b2f376451cceb52d3b4618/patches/server/0744-Optimise-general-POI-access.patch#L971

**Comment by lynxplay** [comment] 2022-02-03 00:35
> Likely caused by
> 
> https://github.com/PaperMC/Paper/blob/79dd62ae620c082646b2f376451cceb52d3b4618/patches/server/0744-Optimise-general-POI-access.patch#L971

Oh see github has fancy patch integration ? I just linked that as a hyperref.

**Comment by berlincount** [comment] 2022-02-03 16:03
Okay, tried the steps from the description with `spigot-1.17.1.jar` and `spigot-1.18.1.jar` - no problem there, linked portals are okay.

Interestingly: tried `paper-1.17.1-184.jar` on the world after this - portals also intact. Deconstructing the portal in the overworld and recontructing it in a third location lead to intact portals as well. With `paper-1.17.1-177.jar` after, portals stayed intact as well.

**Comment by berlincount** [comment] 2022-02-03 16:05
> > This seems to be a duplicate of #6995.
> 
> I had a look at #6995 before but this seems to be rather related to Muliverse and was confirmed solved without Multiverse.
> 
> This here can be reproduced in a bare lab without any plugins.

nah, it was only a suspicion MV was causing this, but the discussion thread there also shows it's unrelated. so, technically, these two issues are duplicates of the same underlying issue, with this one having more info on the probable cause.

**Closed as completed** 2022-02-03 19:28 UTC
Labels: type: bug, status: accepted
