### ISSUE TITLE
Villager 

### ISSUE THREAD

**Issue by zombihunterbonn** [PaperSpigot/Paper#6692] opened 2021-10-01 21:44 UTC
### Expected behavior

Villagers add food to their inventory

### Observed/Actual behavior

Villagers do not add food to their inventory and abandon the harvest

### Steps/models to reproduce

![Uploading Screenshot_20211001-201518_Minecraft.png…]()

### Plugin list

None

### Paper version

paper-1.17.1-295

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment] 2021-10-01 21:45
> 1.17.1 last

is not a version

**Comment by zombihunterbonn** [comment] 2021-10-01 21:52
> > 1.17.1 last
> 
> is not a version

Sry I am editing this

**Comment by zombihunterbonn** [comment] 2021-10-01 21:53
Now it's the right version

**Comment by Machine-Maker** [comment] 2021-10-01 22:05
@zombihunterbonn what is your `mobGriefing` gamerule set to? run `/gamerule mobGriefing`. If its set to false, villagers won't pick up food. mob griefing needs to be enabled for that to happen.

**Comment by zombihunterbonn** [comment] 2021-10-01 23:26
> @zombihunterbonn what is your `mobGriefing` gamerule set to? run `/gamerule mobGriefing`. If its set to false, villagers won't pick up food. mob griefing needs to be enabled for that to happen.

It's true

**Comment by Machine-Maker** [comment] 2021-10-02 19:27
Cannot reproduce, if you can provide reproduction steps with no plugins or datapacks, comment them, closing for now.

**Closed as completed by Machine-Maker** 2021-10-02 19:27 UTC
Labels: resolution: cannot reproduce
