### ISSUE TITLE
Mobs despawning through portals (only person on server and with another afk <128 blocks away)

### ISSUE THREAD

**Issue by parkerha** [PaperSpigot/Paper#9628] opened 2023-08-19 05:18 UTC
### Expected behavior

Using Ianxofour's gold farm, zombified piglins should go through portal in nether side and emerge in overworld before going into another portal, taking them to killing chamber above nether roof.

### Observed/Actual behavior

Zombified piglins never appear in killing chamber. Am online alone on the server. Logged in with my alt at the same time and went to overworld side of zombie pigman farm, at which I can see the pigmen coming through the portal and instantly despawning. 

### Steps/models to reproduce

This is me showing the glitch.

https://www.youtube.com/watch?v=DX3R3cvJMeo

### Plugin and Datapack List

plugins:
GravityControl

datapacks:
[vanilla (built-in)]
[file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-132 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: eb8f2bb)
You are running the latest version
Previous version: git-Paper-116 (MC: 1.20.1)

### Other

Used to work up to a few weeks ago when I last remember using it. Could have to do with the GravityControl plugin as it has to do with duping gravity blocks through portals and I installed it in the past few weeks.

**Comment by CodeByCam** [comment] 2023-08-19 07:07
Hey parkerha, 
Can you please test this without any plugins running to see if the issue persists? Additionally, can you please provide a schematic or zipped world file for the gold farm?

**Comment by parkerha** [comment] 2023-08-19 16:23
Yes, just checked and issue still persists without the GravityControl plugin. Gold farm is Ianxofour's design, he has a link in the video description for the world download. Here is the video: https://www.youtube.com/watch?v=uBpMwXVn6iY
Let me know if you need me to post the file myself, it's just slightly too big to upload directly. Also let me know if you need my world specifically. Thank you!!

**Comment by CodeByCam** [comment] 2023-08-20 08:12
Cheers for the info.
I've realised this is actually a duplicate of another issue that was recently created (https://github.com/PaperMC/Paper/issues/9593), including using the same farm, so I'll be closing this issue.  As mentioned in this issue by Lynx you can use [this plugin](https://hangar.papermc.io/Kyle/Otherside) to help.


Unlike you though, on latest Paper (default configs) I didn't have any issue with them despawning when coming through the portal when I had an account at both the kill floor & bridge in the overworld:

 ![C9AQRK8](https://github.com/PaperMC/Paper/assets/41496198/8d6bac52-be2c-48c1-9897-30187f78c40a)

**Closed as completed by CodeByCam** 2023-08-20 08:12 UTC
Labels: type: bug, resolution: duplicate

**Comment by parkerha** [comment] 2023-08-20 19:18
It is a similar issue, but that person had other people online and tried to work the gold farm, so the despawning was happening due to the other people. I downloaded the otherside plugin, and the problem persists. The pigmen instantly despawn even though they are supposed to stay for 20 seconds by default. So, with and without plugins the nether teleportation does not work.

**Comment by parkerha** [comment] 2023-08-20 19:25
Nevermind I was on peaceful........... thanks for the help!!
