### ISSUE TITLE
Dispensers with blocks above them not behaving same as in vanilla

### ISSUE THREAD

**Issue by South-Paw** [PaperSpigot/Paper#7696] opened 2022-04-03 08:55 UTC
### Expected behavior

The two screenshots below behave exactly the same in vanilla; when the redstone is powered via the button, the water will be dispensed. When the redstone is powered again, all the dispensers will pick up the water

![2022-04-03_20 38 32](https://user-images.githubusercontent.com/2154764/161419478-921f18b4-5b07-40f5-8837-8e494f973896.png)

![2022-04-03_20 38 25](https://user-images.githubusercontent.com/2154764/161419476-7af99cf3-3947-41f2-9240-23e84b57130a.png)

### Observed/Actual behavior

On Paper the first example behaves the same as in vanilla, however the second one where the dispensers are powered through the block does not behave the same. When all the dispensers should pick up the water, instead only every _second_ dispenser picks up water.

![2022-04-03_19 47 23](https://user-images.githubusercontent.com/2154764/161419710-2f17950f-c876-4ef0-b174-84485d2ffe84.png)

(mid button press screenshot above)

The remaining water sources then create new sources and the contraption breaks.

### Steps/models to reproduce

Build the examples in game, place water buckets in every dispenser and press the button 🤷‍♂️

### Plugin and Datapack List

n/a - tested this on a clean PaperMC server (no plugins or data packs) and still observed issue occurring

### Paper version

This server is running Paper version git-Paper-277 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 87e11bf)
You are running the latest version

### Other

Another discord user said that this work working fine on their server and I was linked a discussion from a wee-while ago where someone had a similar issue with dispensers and it was suggested to toggle `use-faster-eigencraft-redstone`.

So I tried setting `use-faster-eigencraft-redstone` to `true` and it appears to resolve the issue... 🤔

**Comment by Machine-Maker** [comment] 2022-04-03 16:28
Can reproduce on 1.18.2. This is also reproducible on Spigot 1.18.2 with slightly different results, and yet again on CraftBukkit 1.18.2 with even more different results.

**Comment by SpaceWalkerRS** [comment] 2022-07-14 10:50
This is a vanilla issue, not related to bukkit/spigot/paper. Behavior of redstone dust networks is different in different locations. Even in vanilla you will find that some dispensers will stay stuck on in some locations.

**Comment by lynxplay** [comment] 2022-08-07 23:49
Going off of space walkers statement (I think they know like, a little about redstone), this is a works as intended.
Closing this issue for said reason ^

**Closed as not planned by lynxplay** 2022-08-07 23:49 UTC
Labels: type: bug, resolution: works as intended, version: 1.18

**Comment by South-Paw** [comment] 2022-08-08 01:39
> High performance Spigot fork that **aims to fix gameplay and mechanics inconsistencies**

I thought this was a prime example of an inconsistency or mechanic that would be a good candidate for Paper to fix especially given that `use-faster-eigencraft-redstone` fixes the behaviour when enabled 🤔

Regardless, thanks all

**Comment by lynxplay** [comment] 2022-08-08 01:49
If one of the redstone engines already fixes this (have you tried alternate-current ?) that would probably be the best case to use.
Or stick with eigencraft.
Generally speaking "fixing" quirks in the vanilla redstone engine is a pretty dicey thing to do in regards to what players expect to work (Extreme example but like, quasi connectivity or directional redstone are a thing and are being used and for both you can argue that they are either a bug or a bug that turned feature) Adding a config option for it, especially when we seem to already be providing alternatives that fix the behavior, seems overkill to me.

**Comment by South-Paw** [comment] 2022-08-08 06:31
Okay thanks for the explanation, that makes more sense especially the note on the quirks of vanilla redstone - it might be great for one server but breaks stuff on another 👍
