### ISSUE TITLE
When you die while receiving an effect that affects the attribute, the attribute does not reset.

### ISSUE THREAD

**Issue by quruqu** [PaperSpigot/Paper#11020] opened 2024-07-05 09:12 UTC
### Expected behavior

If you die while receiving a potion effect that affects an attribute, the potion effect will disappear, but the affected attribute will not be reset.

### Observed/Actual behavior

When you die while receiving the minecraft:health_boost effect, the effect disappears, but the minecraft:generic.max_health attribute is not reset.
The minecraft:jump_boost effect also does not reset the minecraft:generic.safe_fall_distance attribute when it dies.

### Steps/models to reproduce

https://github.com/PaperMC/Paper/assets/174780878/48c7e39f-8122-4333-aa38-5c507c99da5c

### Plugin and Datapack List

It also happens on a newly created server

### Paper version

This server is running Paper version 1.21-40-master@b45d9b6 (2024-07-01T08:23:14Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 4 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.20.6-138-906df69 (MC: 1.20.6)

### Other

When you die under the minecraft:jump_boost effect, the minecraft:generic.jump_strength attribute is reset.

**Comment by lynxplay** [comment] 2024-07-05 12:31
Duplicate of #10907

**Closed as not planned by lynxplay** 2024-07-05 12:31 UTC
Labels: type: bug, resolution: duplicate, version: 1.21
