### ISSUE TITLE
Attempted to place a Tile Entity

### ISSUE THREAD

**Issue by Truzzolo** [PaperSpigot/Paper#9537] opened 2023-07-27 10:37 UTC
### Timings or Profile link

https://pastes.dev/KW13uR8LV5

### Description of issue

I'm running a paper 1.19.4 server with a custom map of Italy (22k x 24k) so it's very big and our server has about 20/30 player's online. But when the players joins and they start to go across the map, the server begins to spam this warn with different coords every time. We understood that the problem is a try of the server to place a TileEntity (Skull), but it can't do that.
Actually this process uses so Much RAM, and it increases as players keep joining.

So we tried everything but there are so many corrupted entity tiles, so i tried to use the same map downloaded from the original site on a 1.16.5 server, and i used the remove-corrupted-tile-entities option on paper.yml, and everything seems to work, but when i tried this on 1.19.4, i looked inside the paper-world-defaults.yml but there isn't an option similar to the 1.16.5 one.

Can someone help me? Thanks

```
[09:36:28 WARN]: com.destroystokyo.paper.exception.ServerInternalException: Attempted to place a tile entity (net.minecraft.world.level.block.entity.TileEntitySkull@187189c5) at 13288,82,9437 (Block{minecraft:air}) where there was no entity tile!
[09:36:28 WARN]: Chunk coordinates: 13280,9424
[09:36:28 WARN]: World: minecraft:overworld
[09:36:28 WARN]:        at net.minecraft.world.level.chunk.LevelChunk.setBlockEntity(LevelChunk.java:727)
[09:36:28 WARN]:        at net.minecraft.world.level.chunk.storage.ChunkSerializer.lambda$postLoadChunk$11(ChunkSerializer.java:742)
[09:36:28 WARN]:        at net.minecraft.world.level.chunk.LevelChunk.runPostLoad(LevelChunk.java:813)
[09:36:28 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkFullTask.run(ChunkFullTask.java:49)
[09:36:28 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351)
[09:36:28 WARN]:        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118)
[09:36:28 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.executeMainThreadTask(ChunkTaskScheduler.java:250)
[09:36:28 WARN]:        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1008)
[09:36:28 WARN]:        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:579)
[09:36:28 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1330)
[09:36:28 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312)
[09:36:28 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
[09:36:28 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389)
[09:36:28 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174)
[09:36:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[09:36:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Plugin and Datapack List

AuthMe, BlockLocker, Citizens, ClearLag, CraftEnhance, CraftingStore, DecentHolograms, Essentials, EssentialsChat, EssentialsSpawn,  GSit, icbmBukkit, LPX, LuckPerms, Maintenance, MOTD, NBTAPI, PlaceholderAPI, PlugManX, ProtocolLib, QualityArmory, ReallyFakePlayers, SimpleScore, SkinsRestorer, Skript, spark, StaffList, SuperVanish, TAB, Tickets, TimeManager, TradeSystem, TransportPipes, UIChat, UICore, UIImperi, UiItems, UIJoin, UIPosta, UIStaffUtils, UITexture, UIVehicles, UIWar, Vault, VehiclesPlusPro, ViaVersion, VillagerShop, WorldEdit, WorldGuard

### Server config files

https://paste.gg/p/anonymous/368891c2298e4f88ae0e8635210c1d51 >> Bukkit.yml

https://paste.gg/p/anonymous/b26d6e0b2f6546218491106e8e132d5b >> paper-global.yml

https://paste.gg/p/anonymous/249fc4dc2ea3430bbb44341dfa9660b5 >> paper-world-defaults.yml

https://paste.gg/p/anonymous/fce4494f61af41af8d884f7bd2a7ddcd >> spigot..yml

### Paper version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

**Comment by pop4959** [comment] 2023-08-05 23:54
Can you provide a link to a world download that has the issue? Also specific coordinates if relevant.

**Comment by Warriorrrr** [comment] 2023-08-13 08:24
Closing this since it isn't really a paper issue, your custom map has block entity data at locations where there aren't actually block entities. If you want to get rid of the errors, you can use a plugin like chunky to do a one-time load of all your chunks, but they should be safe to just ignore.

**Closed as not planned by Warriorrrr** 2023-08-13 08:24 UTC
Labels: type: bug, resolution: works as intended

**Comment by tomasalias** [comment] 2024-03-20 10:37
@Warriorrrr I have the same issue with my earth map. How do fix this? Is there a plugin?

**Comment by masmc05** [comment] 2024-03-20 11:02
> @Warriorrrr I have the same issue with spawners on my earth map. How do fix this? Is there a plugin? It would take ages for Chunky to load all the chunks.

if chunky is not good enough for you then just ignore the errors

it's not possible to have a faster fix than using chunky

**Comment by tomasalias** [comment] 2024-03-23 16:45
@masmc05 I can ignore the errors, but not the crashes!

**Comment by electronicboy** [comment] 2024-03-23 16:47
The problem is that spigots API leads to inconsistent world state, need to look into removing the busted block entities from the world in order to prevent issues

**Comment by tomasalias** [comment] 2024-03-23 16:52
> The problem is that spigots API leads to inconsistent world state, need to look into removing the busted block entities from the world in order to prevent issues

Do you know plugin, that will remove these tile entities, before they crash the server?
