### ISSUE TITLE
Memory Leaks paper1.20.4

### ISSUE THREAD

**Issue by 1470429149** [PaperSpigot/Paper#10820] opened 2024-05-29 13:39 UTC
### Expected behavior

When I use the dungeon plugin to repeatedly unload and add worlds, the memory just always grows, which is very strange, when I use java heap dump I found that the unloaded worlds have loaded chunks
![image](https://github.com/PaperMC/Paper/assets/96332168/55d889fe-a875-4bab-8293-66bca0d4524d)
![image](https://github.com/PaperMC/Paper/assets/96332168/bb507bc0-3bcc-4bff-8bbe-9c79a79c01c2)
![image](https://github.com/PaperMC/Paper/assets/96332168/7e69250e-f9a5-427f-8c2c-3515a04d18c5)
![image](https://github.com/PaperMC/Paper/assets/96332168/e0b53a82-4313-48f8-86b2-47c4ec57aa89)
![image](https://github.com/PaperMC/Paper/assets/96332168/3bec56d8-d9a4-4b23-af84-1235be3283ea)

![image](https://github.com/PaperMC/Paper/assets/96332168/1167adb2-a4d7-4d5f-8e45-9f75c6416535)

### Observed/Actual behavior

The world should not remain in memory after unloading

### Steps/models to reproduce

repeatedly unload and add worlds

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/96332168/8d43d49f-cc09-4df0-a87b-72ab4c8c4f56)

### Paper version

![image](https://github.com/PaperMC/Paper/assets/96332168/f887c36b-3c66-4c2d-a88d-1f339ab58020)

**Comment by lynxplay** [comment] 2024-05-29 13:44
Presumably a duplicate of https://github.com/PaperMC/Paper/issues/9199?
(followed up in https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2278#issuecomment-1583679524)

Can you attempt this without mythic mobs?

**Comment by 1470429149** [comment] 2024-05-29 13:48
Thanks a lot, I will retest as you suggested and if it persists I will open the issue again

**Comment by lynxplay** [comment] 2024-05-29 14:37
After a bit more investigation, there is something on our end that might be causing this 👍

**Comment by electronicboy** [comment] 2024-05-30 17:59
Okay, I brain farted, further looking this doesn't seem to be us, as the map storing that is actually a weak map. if this reoccurs, we'd need a minimal reproduction, otherwise you'd need to look into what the retainers are

**Closed as not planned by electronicboy** 2024-05-30 17:59 UTC
Labels: type: bug, version: 1.20.4
