### ISSUE TITLE
Delayed command registration fails in 1.19.1+

### ISSUE THREAD

**Issue by mibby** [PaperSpigot/Paper#8255] opened 2022-08-07 06:42 UTC
### Expected behavior

Commands from WorldGuard to work as they use to in 1.19.

### Observed/Actual behavior

Commands from WorldGuard do not work in 1.19.1+.

### Steps/models to reproduce

* Install WorldGuard & WorldEdit to Paper-113 plugin folder.
* Set yourself as OP
* Try to use commands from WorldGuard such as ``/god``.
* Command is unknown.

### Plugin and Datapack List

WorldEdit dev 6234
WorldGuard dev 2204

https://builds.enginehub.org/

### Paper version

Paper version git-Paper-113 (MC: 1.19.2)

### Other

RE: https://github.com/EngineHub/WorldGuard/issues/1943

**Comment by Machine-Maker** [comment] 2022-08-07 06:44
This is just an initial guess, but this is probably because the CommandMap is no longer used for executing commands, the brigadier dispatcher is. And they are only synced when CraftServer#syncCommands() is called. which is once after plugin loading, and during a reload.

This change was made (purposefully, I think) by spigot for 1.19.1

**Comment by mibby** [comment] 2022-08-07 06:45
@wizjany / @me4502 Ping for notice.

**Comment by A248** [comment] 2022-08-07 15:15
I can confirm this bug with LibertyBans' command aliases. Command registration fails to have effect after the startup process.

Command **unregistration** also fails. Unregistering a command has no effect, either.

**Comment by Owen1212055** [comment] 2024-05-11 20:39
Fixed by https://github.com/PaperMC/Paper/pull/8235

**Closed as completed by Owen1212055** 2024-05-11 20:39 UTC
Labels: type: bug, status: accepted, version: 1.19
