### ISSUE TITLE
Health scaling doesn't work correctly with the max health attribute.

### ISSUE THREAD

**Issue by erenkarakal** [PaperSpigot/Paper#8718] opened 2022-12-24 13:31 UTC
### Expected behavior

Your visible hearts should not change.

### Observed/Actual behavior

https://user-images.githubusercontent.com/67760502/209438060-7c1fe7f3-1ffc-4a37-980f-e4deeae79c30.mp4

When you stop using an item with a health attribute, your visible hearts change.

### Steps/models to reproduce

1. Set your max health to any number. (tested with 50)
2. Enable health scaling. `p.setHealthScaled(true)`
3. Set your scaled health. `p.setHealthScale(20)`
4. Use an item with a max health attribute. `/give @p leather_helmet{AttributeModifiers:[{AttributeName:"generic.max_health",Amount:20.0,Slot:mainhand,Name:"generic.max_health",UUID:[I;-1221124,11452,1679,-22904]}]} 1`
5. Stop using the item.

### Plugin and Datapack List

`Plugins (18): CoreProtect, DiscordSRV, GrimAC, GSit, Hippo, LuckPerms, PlaceholderAPI, ProtocolLib, SkBee, SkinsRestorer, Skript, skript-placeholders, skript-reflect, TAB, Vault, ViaBackwards, ViaVersion, WorldEdit`

`There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]`

### Paper version

```
This server is running Paper version git-Paper-358 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f26e9cc)
You are running the latest version
Previous version: git-Paper-210 (MC: 1.19.2)
```

**Comment by Malfrador** [comment] 2023-08-15 05:35
I am unable to reproduce this issue on the latest version of Paper (1.20.1-126) using the steps you provided. The scaled health displayed to the player gets updated correctly when switching to and from the helmet, and the amount of hearts does not change. It might have been fixed by chance, or was caused by one of your installed plugins.

Therefore I am going to close this issue for now. If you or anyone else is able to reproduce it (without any plugins), feel free to reply and it can be reopened.

**Closed as not planned by Malfrador** 2023-08-15 05:35 UTC
Labels: type: bug, resolution: cannot reproduce, version: 1.19.3
