### ISSUE TITLE
Hoppers into Composters and InventoryMoveItemEvent

### ISSUE THREAD

**Issue by paul-palmer** [PaperSpigot/Paper#8142] opened 2022-07-14 18:21 UTC
### Timings or Profile link

https://timings.aikar.co/?id=87d234d02dcc4a72833455e6730498a1

### Description of issue

Similar to #976 and hoppers generating spurious InventoryMoveItemEvent events when they are pointing at full containers, there is another similar scenario that can cause significant lag.

When a hopper points into a composter and the hopper contains items that cannot be composted, the items cannot be pushed out of the hopper. The hopper will then generate an InventoryMoveItemEvent each tick for every ItemStack in the hopper that cannot be composted.

In the spirit of #976, would it be possible to not generate the InventoryMoveItemEvent if the item cannot be pushed to the composter?

### Plugin and Datapack List

Craftmatic
Worldguard

### Server config files

```bukkit.yml
settings:
  use-map-color-cache: true
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 4000
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server closed
  minimum-api: none
spawn-limits:
  axolotls: 5
  water-underground-creature: 5
  water-ambient: 80
  monsters: 80
  animals: 40
  water-animals: 80
  ambient: 20
chunk-gc:
  period-in-ticks: 600
ticks-per:
  axolotl-spawns: 1
  water-underground-creature-spawns: 1
  water-ambient-spawns: 1
  water-spawns: 1
  ambient-spawns: 1
  animal-spawns: 200
  monster-spawns: 1
  autosave: 6000
aliases: now-in-commands.yml
```

```spigot.yml
config-version: 12
settings:
  log-named-deaths: true
  log-villager-deaths: true
  debug: false
  save-user-cache-on-stop-only: false
  bungeecord: false
  sample-count: 12
  player-shuffle: 0
  user-cache-size: 1000
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-multiplier: 10.0
  timeout-time: 60
  restart-on-crash: false
  restart-script: ./start.sh
  netty-threads: 8
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
messages:
  whitelist: You are not whitelisted on this server!
  unknown-command: Unknown command. Type "/help" for help.
  server-full: The server is full!
  outdated-client: Outdated client! Please use {0}
  outdated-server: Outdated server! I'm still on {0}
  restart: Server is restarting
commands:
  log: true
  tab-complete: 0
  send-namespaced: true
  spam-exclusions:
  - /skill
  silent-commandblock-console: false
  replace-commands:
  - setblock
  - summon
  - testforblock
  - tellraw
advancements:
  disable-saving: false
  disabled:
  - minecraft:story/disabled
stats:
  disable-saving: false
  forced-stats: {}
world-settings:
  default:
    hopper-can-load-chunks: false
    seed-nether: 30084232
    seed-stronghold: default
    below-zero-generation-in-existing-chunks: true
    simulation-distance: default
    thunder-chance: 100000
    max-entity-collisions: 8
    seed-endcity: 10387313
    seed-bastion: 30084232
    seed-fortress: 30084232
    seed-mansion: 10387319
    seed-fossil: 14357921
    seed-portal: 34222645
    end-portal-sound-radius: 0
    trident-despawn-rate: 120
    verbose: true
    mob-spawn-range: 8
    hopper-amount: 1
    dragon-death-sound-radius: 0
    seed-village: 10387312
    seed-desert: 14357617
    seed-igloo: 14357618
    seed-jungle: 14357619
    seed-swamp: 14357620
    seed-monument: 10387313
    seed-shipwreck: 165745295
    seed-ocean: 14357621
    seed-outpost: 165745296
    seed-slime: 987234911
    max-tnt-per-tick: 100
    view-distance: 8
    enable-zombie-pigmen-portal-spawns: false
    item-despawn-rate: 6000
    arrow-despawn-rate: 120
    wither-spawn-sound-radius: 0
    hanging-tick-frequency: 100
    zombie-aggressive-towards-villager: true
    nerf-spawner-mobs: false
    growth:
      twistingvines-modifier: 100
      weepingvines-modifier: 100
      cavevines-modifier: 100
      glowberry-modifier: 100
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      beetroot-modifier: 100
      carrot-modifier: 100
      potato-modifier: 100
      wheat-modifier: 100
      netherwart-modifier: 100
      vine-modifier: 100
      cocoa-modifier: 100
      bamboo-modifier: 100
      sweetberry-modifier: 100
      kelp-modifier: 100
    merge-radius:
      exp: 2.5
      item: 0.5
    entity-activation-range:
      ignore-spectators: false
      water: 12
      villagers: 12
      flying-monsters: 32
      villagers-work-immunity-after: 100
      villagers-work-immunity-for: 20
      villagers-active-for-panic: true
      animals: 12
      monsters: 24
      raiders: 24
      misc: 4
      tick-inactive-villagers: true
      wake-up-inactive:
        animals-max-per-tick: 4
        animals-every: 1200
        animals-for: 100
        monsters-max-per-tick: 8
        monsters-every: 400
        monsters-for: 100
        villagers-max-per-tick: 4
        villagers-every: 600
        villagers-for: 100
        flying-monsters-max-per-tick: 8
        flying-monsters-every: 200
        flying-monsters-for: 100
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 40
      misc: 32
      other: 64
    ticks-per:
      hopper-transfer: 8
      hopper-check: 1
    hunger:
      jump-walk-exhaustion: 0.05
      jump-sprint-exhaustion: 0.2
      combat-exhaustion: 0.1
      regen-exhaustion: 6.0
      swim-multiplier: 0.01
      sprint-multiplier: 0.1
      other-multiplier: 0.0
    max-tick-time:
      tile: 50
      entity: 50
    squid-spawn-range:
      min: 45.0
  worldeditregentempworld:
    verbose: false
  faweregentempworld:
    verbose: false
players:
  disable-saving: false
```

```server.properties
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=false
level-name=world
motd=A Minecraft Server
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=hard
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=16
max-build-height=400
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
debug=false
force-gamemode=false
rate-limit=0
hardcore=false
white-list=true
broadcast-console-to-ops=true
spawn-npcs=true
previews-chat=false
spawn-animals=true
snooper-enabled=true
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=40
max-world-size=29999984
```

No paper*.yml

### Paper version

This server is running Paper version git-Paper-61 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: cd215af)
You are running the latest version

### Other

These timings collected while in a chunk with 225 hoppers pointing down into composters each containing 4 wooden shovels.
  
The timings show the craftmatic plugin being heavily impacted. This is the affected listener in that plugin:

	@EventHandler(priority = LOWEST, ignoreCancelled = true)
	public void onInventoryMoveItemEvent(final InventoryMoveItemEvent e) {
		final InventoryHolder holder = e.getSource().getHolder();
		if (holder instanceof final Dropper dropper) {
			if (this.plugin.isKnownCraftingBlock(dropper.getBlock())) {
				e.setCancelled(true);
			}
		}
	}

I believe Worldguard is not heavily impacted because getDestination() returns null for these particular events and Worldguard can more cheaply ignore them.

**Comment by Owen1212055** [comment] 2022-08-07 13:40
I can reproduce this "behavior", however, I think that this is just a result of how this event works, and changing this would result in a behavior change. (This occurs for all types of containers with hoppers)
![image](https://user-images.githubusercontent.com/23108066/183293491-40d9aa61-8c39-41aa-9c8a-9871f8901892.png)
For example, if I try to put a chest in the hopper with these items... it will fire the event and fail because there is still possible room in the inventory but it can't find a valid slot.
![image](https://user-images.githubusercontent.com/23108066/183293538-b870dd93-6d19-4359-a237-03d1334ed221.png)

However, if I override the item using
```java
 @EventHandler
    public void onInventoryMoveItemEvent(final InventoryMoveItemEvent e) {
        e.setItem(new ItemStack(Material.SKELETON_SKULL));
    }
```
this allows me to convert the chest into a skull before it is moved into the chest.
![image](https://user-images.githubusercontent.com/23108066/183293564-0b4daf5d-8379-494a-8f8a-3fb01ae827af.png)


If the event wasn't fired, this behavior would no longer be possible.
Therefore I will be closing this, thank you for your report! If you still feel however that it is possible to accomplish something like this without breaking behavior, feel free to comment and this can be reopened. 😄

**Closed as not planned by Owen1212055** 2022-08-07 13:40 UTC
Labels: scope: performance, resolution: works as intended

**Comment by paul-palmer** [comment] 2022-08-13 14:09
I am disappointed as one of the compelling reasons to use Paper is it has historically been focused on performance. In this case, you are indicating that poor performance is the intended behavior.

**Comment by CommandDan** [comment] 2022-08-13 14:21
> I am disappointed as one of the compelling reasons to use Paper is it has historically been focused on performance. In this case, you are indicating that poor performance is the intended behavior.

Well as Owen mentioned, you wouldn't be able to check when an item tries to go inside the container.

What could be done is having a config boolean to disable the checks, but then you will break any plugin relying on it in your server.

**Comment by electronicboy** [comment] 2022-08-13 14:31
The problem here is that hoppers just blatantly suck and the logic to add an item to an inventory relies upon literally trying to merge into every single slot, I've had a few ideas for marginal improvements over the years but there's sadly no denying the fact that hoppers just blatantly suck, and most solutions end up impeding on farms or are generally only gonna head off certain cases

generally,
1) the event is only fired once (or, actually, twice, one for pull, one for push) per hopper tick, assuming nothing calls getItem(); if something cares about the item then we need to respect this
2) calling getHolder() will do a full blockstate snapshot of the source block, i.e. creating a tile entity snapshot on each call, use getHolder(false) to mitigate this one if desirable

outside of 1, the real issue here is that hoppers try to merge the item into every single slot in an inventory, which is somewhat of a norm for how inventories transferring items anywhere works, even when you pick up items from the world, sadly, 3 is the biggest issue outside of plugins and generally somewhat unavoidable; most of what's gonna be done here is going to be capturing "oh shit" states, but this is risky and has many headaches involved with trying to track such states properly

**Comment by Cryptite** [comment] 2022-08-13 23:04
Regrettably it'd be a bit of work, but would the concept of a "dirty inventory" boolean be useful? In short, an inventory/hopper has an awareness about whether the destination inventory it's trying to shove stuff into has ever changed (dirty or not). This could honestly be as ephemeral as only persisting as long as its chunk is loaded. Any hopper that tries to access a chest would, after its first insertion attempt flag the inventory has having been checked already.

You'd then of course have to have logic to do an Inventory.equals() check after things like player interactions, etc to see whether the destination inv has changed. Mostly just threw this out there outta my ass but it is certainly a common practice. Easier said than done, anyway

**Comment by electronicboy** [comment] 2022-08-13 23:10
That was one of my primary "easy" thinking but it's not free of caveats, you'd need to mark as dirty on get operations too, just because you can't see if something got a stack and mutated it in some manner, etc

**Comment by Cryptite** [comment] 2022-08-14 13:25
Yeah, I suppose being "touched" at all (get) would dirty it, however many innuendos there are with that statement. It's the only way to be sure
