### ISSUE TITLE
/help is not helpful [QOL]

### ISSUE THREAD

**Issue by WildPenquin** [PaperSpigot/Paper#9906] opened 2023-11-04 10:33 UTC
Hi,

When typing  `/help [any command]`, I do not get any kind of helpful usage summary. It seems like all usage information is missing or the help message is truncated. An example:
```
[12:10:28 INFO]: --------- Help: /whitelist ----------------------
[12:10:28 INFO]: Description: A Mojang provided command.
[12:10:28 INFO]: Usage: whitelist
```
In the official server one could get something useful out, though it is not prettily formatted:
```
/help whitelist
[12:23:29] [Server thread/INFO]: /whitelist on
[12:23:29] [Server thread/INFO]: /whitelist off
[12:23:29] [Server thread/INFO]: /whitelist list
[12:23:29] [Server thread/INFO]: /whitelist add <targets>
[12:23:29] [Server thread/INFO]: /whitelist remove <targets>
[12:23:29] [Server thread/INFO]: /whitelist reload
```

### Describe the solution you'd like.

Print out a helpful usage summary for all commands. Now one  needs to open a wiki page or something for all commands one does not remember how to use =).

### Describe alternatives you've considered.

Open a browser and use the wiki.

**Comment by electronicboy** [comment] 2023-11-04 15:11
This is basically intended behavior in a sense, craftbukkit replaces the entire help system built into vanilla, which made a lot more sense when they also modified the command itself as they could also add the missing syntax information in a more traditional manner. outside of stripping that out, this is probably a "won't fix/WAI"

**Comment by codeHusky** [comment] 2023-11-06 17:46
spigot could probably make some changes to the help system to actually respect the new help info and provide it somehow, but IMO probably better implemented via plugin developers if anything. would be helpful to have an API to expose the vanilla command's help info though

**Closed as completed** 2024-04-28 17:49 UTC
Labels: type: feature, status: accepted
