### ISSUE TITLE
EncoderException in ClientboundSoundPacket of noteblock

### ISSUE THREAD

**Issue by 0-9** [PaperSpigot/Paper#10143] opened 2024-01-07 04:59 UTC
### Stack trace

```
[13:36:26 ERROR]: Packet encoding of packet ClientboundSoundPacket (ID: 102) threw (skippable? false)
io.netty.handler.codec.EncoderException: String too big (was 65525 characters, max 32767)
        at net.minecraft.network.Utf8String.write(Utf8String.java:35) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.network.FriendlyByteBuf.writeUtf(FriendlyByteBuf.java:694) ~[?:?]
        at net.minecraft.network.FriendlyByteBuf.writeUtf(FriendlyByteBuf.java:690) ~[?:?]
        at net.minecraft.network.FriendlyByteBuf.writeResourceLocation(FriendlyByteBuf.java:703) ~[?:?]
        at net.minecraft.sounds.SoundEvent.writeToNetwork(SoundEvent.java:61) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSoundPacket.write(ClientboundSoundPacket.java:45) ~[?:?]
        at net.minecraft.network.FriendlyByteBuf.writeId(FriendlyByteBuf.java:176) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSoundPacket.write(ClientboundSoundPacket.java:45) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:42) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.20.4.jar:git-Paper-381]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Plugin and Datapack List

none

### Actions to reproduce (if known)

I'm not good at English.

https://www.youtube.com/watch?v=5h8DLpkR_2k

1.get player head with over 32767 length of NoteBlockSound nbt 
(i used nbt editor https://www.curseforge.com/minecraft/mc-mods/nbt-editor)
2.place player head on noteblock
3. click note block

### Paper version

This server is running Paper version git-Paper-381 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 07b956e)
You are running the latest version
Previous version: git-Paper-379 (MC: 1.20.4)

**Comment by electronicboy** [comment] 2024-01-07 07:32
You mean, you edited the NBT of a players datafile on the server in order to reproduce this?

**Comment by Sytm** [comment] 2024-01-07 08:47
The mod they used seems to be a client side mod that uses the creative set item packet to modify the NBT data of items. So _theoretically_ this could be reproduced to creative servers, although almost any sane server owner would have plugins in place that prevent this sort of stuff

**Comment by electronicboy** [comment] 2024-01-07 09:33
oh, it was the other reported issue in which there was the question over how the server was even able to get that into the server, this one is more obvious

**Comment by kennytv** [comment] 2024-01-12 18:33
Should be fixed with https://github.com/PaperMC/Paper/commit/f28caff92752681593137edea91b8fa908995d8e, probably

**Closed as completed by kennytv** 2024-01-12 18:33 UTC
Labels: type: bug, upstream: vanilla, priority: low
