### ISSUE TITLE
entity transported using minecart from nether to overworld disappears

### ISSUE THREAD

**Issue by weihao** [PaperSpigot/Paper#7064] opened 2021-12-09 00:24 UTC
### Expected behavior

entity transported using minecart from nether to overworld should survive whether a chunk is loaded or not.

### Observed/Actual behavior

entity transported using minecart from nether to overworld disappears when the chunk is unloaded.

### Steps/models to reproduce

1. load an entity into a minecart
2. push the minecart with entity into a nether portal
3. destroy the minecart to have the entity go through the portal
4. if the chunk is not loaded, the entity disappears

### Plugin and Datapack List

Plugins (15): AdvancedTeleport, BlueBridgeCore, BlueBridgeGP, BlueMap, Chunky, CoreProtect, DiscordSRV, floodgate, GriefPrevention, PrometheusExporter, SpigotPing, UltimateAutoRestart, Vault, WorldEdit, WorldGuard

### Paper version

This server is running Paper version git-Paper-60 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 74fd151)
You are running the latest version
Previous version: git-Paper-59 (MC: 1.18)

### Other

no illegalstack, other side is must be unloaded (no players/away from spawn)

if the chunk is loaded, everything is normal

**Comment by lynxplay** [comment] 2021-12-09 02:23
Was not capable of reproducing this on my local setup, as plugins are used I (on discord) requested the reporter to replicate it without plugins, which they are currently attempting :+1:

**Comment by lynxplay** [comment] 2021-12-11 01:53
I am closing this as no further input seems to be brought forward by the reporter. Concerning that both I and they couldn't reproduce this on a plain server, there is not enough evidence to justify this issue.

If you manage to replicate it none the less, feel free to comment your findings so we can reopen the issue and investigate further.

**Closed as completed** 2021-12-11 01:54 UTC
Labels: type: bug, resolution: cannot reproduce
