### ISSUE TITLE
Crashes with villagers

### ISSUE THREAD

**Issue by xEchoes** [PaperSpigot/Paper#7664] opened 2022-03-26 23:06 UTC
### Stack trace

```
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-132 (MC: 1.18.1) ---
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] The server has not responded for 10 seconds! Creating thread dump
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] ------------------------------
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] Server thread dump (Look for plugins here before reporting to Paper!):
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] Ticking entity: minecraft:villager, entity class: net.minecraft.world.entity.npc.EntityVillager
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] Entity status: removed: false, valid: true, alive: true, is passenger: false
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] Entity UUID: 45809a32-844b-4b81-a5a4-1d3a074a272c
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] Position: world: 'rebootearth' at location (281.5, 21.0, -223.49000000953674)
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] Velocity: (0.0, -0.0784000015258789, 0.0) (in blocks per tick)
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] Entity AABB: AABB[281.19999998807907, 21.0, -223.79000002145767] -> [281.80000001192093, 22.950000047683716, -223.1899999976158]
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] ------------------------------
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] Current Thread: Server thread
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] PID: 29 | Suspended: false | Native: false | State: RUNNABLE
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] Stack:
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] net.minecraft.world.level.levelgen.synth.ImprovedNoise.noise(ImprovedNoise.java:72)
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] net.minecraft.world.level.levelgen.synth.PerlinNoise.getValue(PerlinNoise.java:156)
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] net.minecraft.world.level.levelgen.synth.PerlinNoise.getValue(PerlinNoise.java:141)
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] net.minecraft.world.level.levelgen.synth.NormalNoise.getValue(NormalNoise.java:87)
[Sat, 26. Mar 2022 17:25:42 CDT ERROR] net.minecraft.world.level.levelgen.NoiseSampler.getOffset(NoiseSampler.java:590)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.levelgen.NoiseSampler.target(NoiseSampler.java:557)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.levelgen.NoiseSampler.sample(NoiseSampler.java:551)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.biome.MultiNoiseBiomeSource.getNoiseBiome(MultiNoiseBiomeSource.java:79)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.biome.BiomeSource.getBiomesWithin(BiomeSource.java:181)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.levelgen.feature.OceanMonumentFeature.checkLocation(OceanMonumentFeature.java:48)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.levelgen.feature.WorldGenMonument$$Lambda$1906/0x00000008011ceb30.test(Unknown Source)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.levelgen.structure.pieces.PieceGeneratorSupplier.a(PieceGeneratorSupplier.java:23)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.levelgen.structure.pieces.PieceGeneratorSupplier$$Lambda$1883/0x00000008011c8d00.createGenerator(Unknown Source)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.levelgen.feature.StructureFeature.canGenerate(StructureFeature.java:251)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.levelgen.structure.StructureCheck.canCreateStructure(StructureCheck.java:113)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.levelgen.structure.StructureCheck.lambda$checkStart$1(StructureCheck.java:94)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.levelgen.structure.StructureCheck$$Lambda$14005/0x000000080371b738.get(Unknown Source)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] it.unimi.dsi.fastutil.longs.Long2BooleanOpenHashMap.computeIfAbsent(Long2BooleanOpenHashMap.java:496)
[Sat, 26. Mar 2022 17:25:47 CDT ERROR] net.minecraft.world.level.levelgen.structure.StructureCheck.lambda$checkStart$0(StructureCheck.java:91)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.world.level.StructureFeatureManager.checkStructurePresence(StructureFeatureManager.java:123)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.world.level.levelgen.feature.StructureFeature.getNearestGeneratedFeature(StructureFeature.java:172)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.world.level.chunk.ChunkGenerator.findNearestMapFeature(ChunkGenerator.java:236)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.server.level.ServerLevel.findNearestMapFeature(ServerLevel.java:1779)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.world.entity.npc.VillagerTrades$TreasureMapForEmeralds.getOffer(VillagerTrades.java:387)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.world.entity.npc.AbstractVillager.addOffersFromItemListings(AbstractVillager.java:281)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.world.entity.npc.Villager.updateTrades(Villager.java:956)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.world.entity.npc.Villager.increaseMerchantCareer(Villager.java:786)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.world.entity.npc.Villager.mobTick(Villager.java:258)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.world.entity.npc.Villager.inactiveTick(Villager.java:234)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1130)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.server.level.WorldServer$$Lambda$10752/0x00000008031f7a18.accept(Unknown Source)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.world.level.Level.guardEntityTick(Level.java:970)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670)
[Sat, 26. Mar 2022 17:25:52 CDT ERROR] net.minecraft.server.level.WorldServer$$Lambda$10662/0x00000008031ec6a0.accept(Unknown Source)
[Sat, 26. Mar 2022 17:25:57 CDT ERROR] net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43)
[Sat, 26. Mar 2022 17:25:57 CDT ERROR] net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650)
[Sat, 26. Mar 2022 17:25:57 CDT ERROR] net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607)
[Sat, 26. Mar 2022 17:25:57 CDT ERROR] net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)
[Sat, 26. Mar 2022 17:25:57 CDT ERROR] net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
[Sat, 26. Mar 2022 17:25:57 CDT ERROR] net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
[Sat, 26. Mar 2022 17:25:57 CDT ERROR] net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[Sat, 26. Mar 2022 17:25:57 CDT ERROR] net.minecraft.server.MinecraftServer$$Lambda$3963/0x000000080143d820.run(Unknown Source)
[Sat, 26. Mar 2022 17:25:57 CDT ERROR] java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
```

### Plugin and Datapack List

AdvancedRenamer, AltDetector, AnimatedScoreboard, AntiRaidFarm, AuctionHouse, AureliumSkills, BankPlus, BetterRTP, BoatInertia, BottledExp, Brewery, BuycraftX, CMILib, Celeste, ChatColor2, ChatItemDisplay, ChestShop, ChestShopNotifier, Citizens, CitizensGUI, CitizensText, CombatLogX, CommandPanels, CommandSigns, CommandWhitelist, CommunityQuests, ConsoleSpamFix, CoreProtect, CrazyCrates, CreativeControl, DailyRewards, DeathMessagesPrime, DiscordSRV, DragonDropElytra, Duels, Dynmap-Towny, EconomyShopGUI, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExcellentEnchants, ExecutableBlocks, ExecutableItems, FastLogin, GHolo, GSit, GappleOptions, Graves, HeadDrops, HelpCustom, HoloDropsX, HolographicDisplays, HsRails, ImageOnMap, InteractionVisualizer, InventoryRollback, InventoryRollbackPlus, InvisibleItemFrames, Jobs, LiteBans, LuckPerms, LumberJack, MarriageMaster, MessageAnnouncer, MeteoritesPro, MineAlert, MineableSpawners, MovingDevApi, Multiverse-Core, MusicBox, MyCommand, MythicMobs, NexEngine, NightVision, NoChatLagServer, NoteBlockAPI, OpenInv, PartyChat, PlaceholderAPI, PlayTime, PlayerParticles, PlayerWarps, ProjectileKnockback, ProtocolLib, Quests, ReligionLab, SCore, ServerRestart, ServerRestorer, ServerTutorialPlus, ServerUtils, ServerlistMOTD, Sickle, SiegeWar, SilkSpawners, SimplePets, SirBlobmanCore, Spartan, StackMob, StaffPlus, SuperVanish, SuperbVote, TAB, TokenManager, Towny, TownyChat, TownyCultures, TownyFlight, TrElytra, Vault, ViaVersion, VoidSpawn, Votifier, WeatherVote, WebOp, WhitelistPro, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, XpBottles, ajParkour, betterbroadcaster, dynmap, eGlow and uShop

### Paper version

Most recent Paper release, #267 version 1.18.2

**Comment by xEchoes** [comment] 2022-03-26 23:09
This error message is what happens once the server crashes

**Comment by NoahvdAa** [comment] 2022-03-26 23:10
> ### Paper version
>
> Most recent Paper release, https://github.com/PaperMC/Paper/issues/267 version 1.18.2

Your logs suggest something else;

> THIS IS NOT A BUG OR A CRASH  - git-Paper-132 (MC: 1.18.1) ---

**Comment by xEchoes** [comment] 2022-03-26 23:13
my bad on that
but after it crashed multiple times, i updated to the most recent paper version and it still output the same error,

```
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-267 (MC: 1.18.2) ---
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] The server has not responded for 10 seconds! Creating thread dump
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] ------------------------------
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] Server thread dump (Look for plugins here before reporting to Paper!):
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] Ticking entity: minecraft:villager, entity class: net.minecraft.world.entity.npc.EntityVillager
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] Entity status: removed: false, valid: true, alive: true, is passenger: false
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] Entity UUID: 7a94d84b-ad5f-4741-b340-1a858e19f315
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] Position: world: 'rebootearth' at location (281.50999999046326, 21.0, -223.49000000953674)
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] Velocity: (0.0, -0.0784000015258789, 0.0) (in blocks per tick)
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] Entity AABB: AABB[281.2099999785423, 21.0, -223.79000002145767] -> [281.8100000023842, 22.950000047683716, -223.1899999976158]
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] ------------------------------
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] Current Thread: Server thread
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] PID: 29 | Suspended: false | Native: false | State: RUNNABLE
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] Stack:
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] net.minecraft.world.level.levelgen.synth.ImprovedNoise.noise(ImprovedNoise.java:75)
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] net.minecraft.world.level.levelgen.synth.PerlinNoise.getValue(PerlinNoise.java:164)
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] net.minecraft.world.level.levelgen.synth.PerlinNoise.getValue(PerlinNoise.java:149)
[Sat, 26. Mar 2022 17:54:53 CDT ERROR] net.minecraft.world.level.levelgen.synth.NormalNoise.getValue(NormalNoise.java:98)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$ShiftNoise.compute(DensityFunctions.java:756)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$ShiftA.compute(DensityFunctions.java:767)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.compute(DensityFunctions.java:381)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$Marker.compute(DensityFunctions.java:447)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.compute(DensityFunctions.java:381)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$Marker.compute(DensityFunctions.java:447)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.compute(DensityFunctions.java:381)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$ShiftedNoise.compute(DensityFunctions.java:643)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.compute(DensityFunctions.java:381)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$Marker.compute(DensityFunctions.java:447)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.compute(DensityFunctions.java:381)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$TerrainShaperSpline.compute(DensityFunctions.java:1301)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.compute(DensityFunctions.java:381)
[Sat, 26. Mar 2022 17:54:58 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$Ap2.compute(DensityFunctions.java:1139)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.compute(DensityFunctions.java:381)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$Ap2.compute(DensityFunctions.java:1141)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.compute(DensityFunctions.java:381)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$Marker.compute(DensityFunctions.java:447)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.compute(DensityFunctions.java:381)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$Marker.compute(DensityFunctions.java:447)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.compute(DensityFunctions.java:381)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$Ap2.compute(DensityFunctions.java:1141)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.levelgen.DensityFunctions$HolderHolder.compute(DensityFunctions.java:381)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.biome.Climate$Sampler.sample(Climate.java:456)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.biome.MultiNoiseBiomeSource.getNoiseBiome(MultiNoiseBiomeSource.java:76)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.biome.BiomeSource.getBiomesWithin(BiomeSource.java:187)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.levelgen.feature.OceanMonumentFeature.checkLocation(OceanMonumentFeature.java:39)
[Sat, 26. Mar 2022 17:55:03 CDT ERROR] net.minecraft.world.level.levelgen.feature.WorldGenMonument$$Lambda$2038/0x00000008011f3bc8.test(Unknown Source)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.world.level.levelgen.structure.pieces.PieceGeneratorSupplier.a(PieceGeneratorSupplier.java:24)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.world.level.levelgen.structure.pieces.PieceGeneratorSupplier$$Lambda$2015/0x00000008011ef3a8.createGenerator(Unknown Source)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.world.level.levelgen.feature.StructureFeature.canGenerate(StructureFeature.java:166)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.world.level.levelgen.structure.StructureCheck.canCreateStructure(StructureCheck.java:92)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.world.level.levelgen.structure.StructureCheck.lambda$checkStart$1(StructureCheck.java:84)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.world.level.levelgen.structure.StructureCheck$$Lambda$11575/0x00000008032f9e50.get(Unknown Source)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] it.unimi.dsi.fastutil.longs.Long2BooleanOpenHashMap.computeIfAbsent(Long2BooleanOpenHashMap.java:496)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.world.level.levelgen.structure.StructureCheck.checkStart(StructureCheck.java:83)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.world.level.StructureFeatureManager.checkStructurePresence(StructureFeatureManager.java:151)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.world.level.chunk.ChunkGenerator.getNearestGeneratedStructure(ChunkGenerator.java:466)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.world.level.chunk.ChunkGenerator.findNearestMapFeature(ChunkGenerator.java:392)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.server.level.ServerLevel.findNearestMapFeature(ServerLevel.java:1810)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.server.level.ServerLevel.findNearestMapFeature(ServerLevel.java:1803)
[Sat, 26. Mar 2022 17:55:08 CDT ERROR] net.minecraft.world.entity.npc.VillagerTrades$TreasureMapForEmeralds.getOffer(VillagerTrades.java:390)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.npc.AbstractVillager.addOffersFromItemListings(AbstractVillager.java:281)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.npc.Villager.updateTrades(Villager.java:958)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.npc.Villager.increaseMerchantCareer(Villager.java:788)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.npc.Villager.mobTick(Villager.java:260)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:247)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.Mob.serverAiStep(Mob.java:865)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3267)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.Mob.aiStep(Mob.java:628)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2917)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.Mob.tick(Mob.java:396)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.entity.npc.Villager.tick(Villager.java:292)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1134)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.server.level.WorldServer$$Lambda$10230/0x000000080301cb88.accept(Unknown Source)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.world.level.Level.guardEntityTick(Level.java:936)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:673)
[Sat, 26. Mar 2022 17:55:13 CDT ERROR] net.minecraft.server.level.WorldServer$$Lambda$10148/0x00000008030039b0.accept(Unknown Source)
[Sat, 26. Mar 2022 17:55:18 CDT ERROR] net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43)
[Sat, 26. Mar 2022 17:55:18 CDT ERROR] net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:653)
[Sat, 26. Mar 2022 17:55:18 CDT ERROR] net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591)
[Sat, 26. Mar 2022 17:55:18 CDT ERROR] net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483)
[Sat, 26. Mar 2022 17:55:18 CDT ERROR] net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455)
[Sat, 26. Mar 2022 17:55:18 CDT ERROR] net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225)
[Sat, 26. Mar 2022 17:55:18 CDT ERROR] net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[Sat, 26. Mar 2022 17:55:18 CDT ERROR] net.minecraft.server.MinecraftServer$$Lambda$4154/0x00000008014b3918.run(Unknown Source)
[Sat, 26. Mar 2022 17:55:18 CDT ERROR] java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
````

**Comment by electronicboy** [comment] 2022-03-27 08:27
Duplicate of #7269 
generally, duplicate of #2312 too

**Closed as completed by electronicboy** 2022-03-27 08:27 UTC
Labels: resolution: duplicate, upstream: vanilla

**Comment by EverNeverYT** [comment] 2024-07-08 08:25
yo descubri el error quitando estas opciones del mythicmobs 
    Level: 3
    Profession: CARTOGRAPHER
    Type: JUNGLE
al parecer el bug se da cuando intentas obligar a un villager a tener profecion o typo ala fuerza 
es mejor quitar las opciones de lever, profession o type 
esto ayudara a que el aldeano se genere mas rapido y no relentise el servidor!
