### ISSUE TITLE
Player can't join with `DomainSocket`

### ISSUE THREAD

**Issue by Coloryr** [PaperSpigot/Paper#10086] opened 2023-12-28 10:40 UTC
### Expected behavior

Player can't join with `DomainSocket`
```
[18:35:13 WARN]: Exception verifying Color_yr
java.lang.ClassCastException: class io.netty.channel.unix.DomainSocketAddress cannot be cast to class java.net.InetSocketAddress (io.netty.channel.unix.DomainSocketAddress is in unnamed module of loader java.net.URLClassLoader @25f38edc; java.net.InetSocketAddress is in module java.base of loader 'bootstrap')
	at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:308) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.lambda$handleCustomQueryPacket$1(ServerLoginPacketListenerImpl.java:389) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Observed/Actual behavior

Player join

### Steps/models to reproduce

1. use UnixDomainSocket
2. Join

### Plugin and Datapack List

none

### Paper version

This server is running Paper version git-Paper-354 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

**Comment by MiniDigger** [comment] 2023-12-28 10:52
I really don't think that anything in the game is designed with IPC in mind
what is your usecase and why can't you just use tcp?

**Comment by Coloryr** [comment] 2023-12-28 11:13
> I really don't think that anything in the game is designed with IPC in mind what is your usecase and why can't you just use tcp?

use this https://github.com/Coloryr/Velocity/tree/dev%2F3.0.0

**Comment by electronicboy** [comment] 2023-12-28 14:55
Duplicate of #9923

**Closed as not planned by electronicboy** 2023-12-28 14:55 UTC
Labels: type: bug, resolution: duplicate, version: 1.20.4
