### ISSUE TITLE
stops loading chunks then crashes

### ISSUE THREAD

**Issue by Vinniethejet** [PaperSpigot/Paper#7660] opened 2022-03-25 03:16 UTC
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://paste.gg/p/anonymous/356df9168e8a47c2896da8cc820701b8

### Plugin and Datapack List

Worldedit, worldguard, multiverse, luckyperms, essentials (chat, spawn),vault

### Actions to reproduce (if known)

loading chunks?

### Paper version

git-Paper-267

### Other

im running a VPS with a AMD Ryzen 9 5900X or
 equivalent and 22gigs of ram. The world size is about 150gb from 2011. it was running stable up until 3 days ago.

**Comment by Castafers** [comment] 2022-03-28 00:17
I'm having the same issue, specifically village chunks cause this issue to be much more severe. If you run ECO + ECOENCHANTS, it'll escalate this issue severely. Something appears to be wrong with the loot tables? I'm running my own server, with an AMD Ryzen 9 5900x

**Comment by electronicboy** [comment] 2022-03-28 10:26
Duplicate of #2312

**Closed as completed by electronicboy** 2022-03-28 10:26 UTC

**Comment by electronicboy** [comment] 2022-03-28 10:29
Looks like in part of the upgrade, something induced loadin the legacy structures file and processing data upgrades on that was holding up the load, could maybe consider a `--forceUpgrade`, its not 100% recommended but can help in regards to dealing with the legacy structures stuff

**Comment by Castafers** [comment] 2022-03-28 18:55
Hey Electronicboy, is this normal to happen on a pregenerated world when reloading the same chunks?
