### ISSUE TITLE
falling-block-height-nerf incorrect description or broken

### ISSUE THREAD

**Issue by 7HourVOG-Run** [PaperSpigot/Paper#8323] opened 2022-08-23 23:19 UTC
### Expected behavior

Setting falling-block-height-nerf to a value below 1 disables the feature

### Observed/Actual behavior

Setting falling-block-height-nerf to a value below than 1 that is not 0 does not disable the feature

### Steps/models to reproduce

Set falling-block-height-nerf to -1, watch as all gravity blocks in your server instantly get killed/despawn/broken the moment they start falling (including but not limited to Sand, Gravel, and TnT) 
Blocks behave inconsistently when breaking, also. Sand and Gravel always drop corresponding blocks, tnt straight up disappears.

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-132 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: a76998d)
You are running the latest version
Previous version: git-Paper-125 (MC: 1.19.2)

### Other

"The height at which falling blocks will be removed from the server. Values less than 1 will disable this feature." -> "The height at which falling blocks will be removed from the server. 0 will disable this feature." perhaps?

Also, is this saying that blocks that fall this height despawn, or blocks that fall below this height despawn?

**Comment by lynxplay** [comment] 2022-08-23 23:23
Pretty much a duplicate of #6981.
The value indicates the y value above which falling block like entities are removed. Setting the value to -1 will result in any falling block like entity to be removed when its y level is *above* -1.

The documentation on this is rather iffy I agree, but the feature works.

MM has an open PR (#6986) to further ease usage of this.

**Closed as not planned by lynxplay** 2022-08-23 23:23 UTC
Labels: type: bug, resolution: duplicate, version: 1.19

**Comment by 7HourVOG-Run** [comment] 2022-08-24 00:32
Ok, good to know, thank you (and sorry for the duplicate!)
