### ISSUE TITLE
Players always log into overworld world, even when logged out in nether or end

### ISSUE THREAD

**Issue by Ed-Silver** [PaperSpigot/Paper#9060] opened 2023-03-27 21:33 UTC
### Expected behavior

Players should log back into the world that they were in when they logged out. Logging out in the nether should see you returned to the nether, not to the same coordinates in the overworld.

### Observed/Actual behavior

Players that log out in the nether are forced into the overworld when logged back in, causing them to fall to their deaths or suffocate in blocks. They spawn in at the same nether coords they logged out, but in the wrong dimension (always the overworld).

### Steps/models to reproduce

Install all plugins..
Log out in nether.
Log back in to find yourself in the overworld.

### Plugin and Datapack List

dynmap (Dynmap version: core=3.4-828, plugin=3.4-828)
floodgate ( 2.2.2-SNAPSHOT)
Geyser-Spigot (version 2.1.0-SNAPSHOT)
ViaVersion (ViaVersion 4.6.2)

[vanilla (built-in)], [file/bukkit (world)], [file/afk display v1.1.3.zip (world)], [file/anti enderman grief v1.1.3.zip (world)], [file/multiplayer sleep v2.6.3.zip (world)], [file/silence mobs v1.1.3.zip (world)], [file/unlock all recipes v2.0.4.zip (world)], [file/more mob heads v2.11.0.zip (world)], [file/player head drops v1.1.3.zip (world)], [file/wandering trades v1.6.0.zip (world)]

(all datapacks from vanilla tweaks)

### Paper version

Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

**Comment by Machine-Maker** [comment] 2023-03-27 22:29
You are using an unsupported version, 1.19.2. Regardless, I cannot reproduce this on a 1.19.4 paper server without plugins or datapacks. Closing as "cannot reproduce" unless you can replicate this issue without any plugins or datapacks.

**Closed as not planned by Machine-Maker** 2023-03-27 22:29 UTC
Labels: type: bug, resolution: cannot reproduce
