### ISSUE TITLE
Loading entity NBT Crash on New World, No Plugins

### ISSUE THREAD

**Issue by stricq** [PaperSpigot/Paper#8496] opened 2022-10-23 02:24 UTC
### Stack trace

```
https://paste.gg/p/anonymous/6473ea1de1f84345a8947614299a8a47
```

### Plugin and Datapack List

N/A

### Actions to reproduce (if known)

Start Server with a new world and login.  Move around for a bit.

### Paper version

This server is running Paper version git-Paper-230 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 6665076)

**Comment by Owen1212055** [comment] 2022-10-23 02:25
Dupe of https://github.com/PaperMC/Paper/issues/8494

**Closed as completed by Owen1212055** 2022-10-23 02:25 UTC
