### ISSUE TITLE
EntityBowShootEvent consuming arrows on cancel (1.20.6/1.21.1)

### ISSUE THREAD

**Issue by FN-FAL113** [PaperSpigot/Paper#11431] opened 2024-09-23 03:46 UTC
### Expected behavior

Works fine on 1.20.4 below
it would be great the API can add an additional function on this to set whether arrows are consumed or not. 

### Observed/Actual behavior

Arrows are being consumed on event cancel

### Steps/models to reproduce

1. shoot an arrow
2. event.setCancelled(true)
3. arrows are consumed

### Plugin and Datapack List

```
[11:45:19 INFO]: Server Plugins (5):
[11:45:19 INFO]: Bukkit Plugins:
[11:45:19 INFO]:  - Essentials, FNAmplifications, RelicsOfCthonia, SfChunkInfo, Slimefun
```

### Paper version

```
This server is running Paper version 1.21.1-96-master@4514c71 (2024-09-22T21:50:05Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-85-c5a1066 (MC: 1.21.1)
```

**Comment by NoahvdAa** [comment] 2024-09-23 10:57
Duplicate of #10665, thanks for the report though

**Closed as not planned by NoahvdAa** 2024-09-23 10:57 UTC
Labels: type: bug, resolution: duplicate, version: 1.21.1

**Comment by FN-FAL113** [comment] 2024-09-23 11:23
> Duplicate of #10665, thanks for the report though

Can that PR be prioritized, its works fine on 1.20.4 but why not on recent mc versions. Thank you
