### ISSUE TITLE
touching the worldborder will cause the player to glitch

### ISSUE THREAD

**Issue by Symmettry** [PaperSpigot/Paper#10051] opened 2023-12-19 08:23 UTC
### Expected behavior

the player should be able to enter back into the worldborder and be stopped by the worldborder by a wall

### Observed/Actual behavior

touching the worldborder causes the player to glitch and freeze in place
after exiting the worldborder with e.g. spectator, when you try to re-enter, it will cause your character to freeze and glitch momentarily aswell (denying access back inside)

### Steps/models to reproduce

set worldborder to something like 20, try to go outside the world border, and try to go back in after leaving with spectator

### Plugin and Datapack List

FastAsyncWorldEdit, Multiverse-Core, SkBee, Skript, spark
Vanilla datapacks

### Paper version

This server is running Paper version git-Paper-329 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: f1820dc)

### Other

Expected behavior occurs on vanilla and singleplayer; only occurs for me on paper.

**Comment by Symmettry** [comment] 2023-12-19 08:24
Oh, it also bugs when running against the worldborder, also freezing the player

**Comment by Symmettry** [comment] 2023-12-19 08:25
This does not happen on vanilla / singleplayer.

**Comment by lynxplay** [comment] 2023-12-19 09:07
Duplicate of #9859, you are not running latest paper either.

**Closed as not planned by lynxplay** 2023-12-19 09:07 UTC
Labels: type: bug, resolution: duplicate

**Comment by Symmettry** [comment] 2023-12-19 17:42
That's odd, I just installed from https://papermc.io/downloads/paper a few days ago. Hmm
