### ISSUE TITLE
Iron golems water flow issue

### ISSUE THREAD

**Issue by Ryzz3nn** [PaperSpigot/Paper#10441] opened 2024-04-20 21:56 UTC
### Expected behavior

the iron golems should go through the water as seen in the video from an singleplayer world of the farm

https://github.com/PaperMC/Paper/assets/47952472/6e3294e3-e7d9-4f38-a2bc-c94ac62d5a7f

Link to schematic for the farm: https://www.mediafire.com/file_premium/yazr5bqfsotxk65/Iron_Farm_Castle.litematic/file

### Observed/Actual behavior

the iron golems will be stuck at the edge of the drop

### Steps/models to reproduce

Link to schematic for the farm: https://www.mediafire.com/file_premium/yazr5bqfsotxk65/Iron_Farm_Castle.litematic/file

### Plugin and Datapack List

the same happels with plugins
![image](https://github.com/PaperMC/Paper/assets/47952472/9ec40936-d59e-4400-9c06-4926423cf2ab)

### Paper version

This server is running Paper version git-Paper-493 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: a6b6ecd)
You are running the latest version
Previous version: git-Paper-485 (MC: 1.20.4)

**Comment by Malfrador** [comment] 2024-06-22 16:40
I cannot reproduce this with the schematic provided on 1.20.6 or 1.21. The iron golems go through the water just fine and fall to their burning deaths. However, the farm gets clogged up quite easily, causing a bit of an iron golem traffic jam before the drop. 

So either this problem has been fixed in newer versions, or it was caused by one of your plugins. 
The collision optimisation patch that could cause this is still missing from 1.21. However, the farm also works fine on 1.20.6, which has all the relevant patches applied.

As I cannot reproduce this on 1.21 or 1.20.6, and 1.20.4 is unlikely to get any more fixes as it is outdated, I will close this issue. 
If you can reproduce this on 1.21 and _without any plugins_, feel free to reply and it can be reopened.

**Closed as not planned by Malfrador** 2024-06-22 16:40 UTC
Labels: type: bug, resolution: invalid, version: 1.20.4
