### ISSUE TITLE
Player Heads with "profile" item component don't work properly

### ISSUE THREAD

**Issue by ogzhancelik** [PaperSpigot/Paper#10776] opened 2024-05-23 16:25 UTC
### Expected behavior

When you give yourself a player head with the item component "profile", it should give you the player head with the skin of the indicated component value and the texture should stick with the given player head.

### Observed/Actual behavior

The texture is visible in the inventory at first. But whenever you interact with it (place it on the ground, throw the item etc.), some of the player heads lose its skin texture and convert to one of the default skin textures. The issue occurs in some skins but the texture sticks properly for the other ones. I observed that which skins are sticking is inconsistent across my two servers.

### Steps/models to reproduce

1. Use a give command to get a player head with a profile component (for ex. `/give @p minecraft:player_head[minecraft:profile="test"]`)
2. When you get the skull, the skin should be visible.
3. Throw the item on the ground, or place it.
4. The correct skin disappears and converts to one of the default skins.
5. If it works properly, try with another skin name.

### Plugin and Datapack List

No plugins.
No datapacks.

### Paper version

This server is running Paper version 1.20.6-90-master@b149584 (2024-05-22T17:30:13Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

### Other

I also tested it on a spigot server if it's an important detail. It doesn't work properly on Spigot too but the problem is not exactly the same and it's highly inconsistent.

**Comment by kennytv** [comment] 2024-05-23 17:36
Cannot reproduce

**Comment by lynxplay** [comment] 2024-06-01 08:47
Closing this as no further comment regarding replication steps was provided.
If you have working replication steps on latest paper without plugins, post them here and we can reopen this :+1:

**Closed as not planned by lynxplay** 2024-06-01 08:47 UTC
Labels: type: bug, resolution: cannot reproduce, version: 1.20.6

**Comment by Xenapte** [comment] 2024-07-17 16:22
I can confirm this on my side. It seems to be a vanilla issue caused by slow internet connections; my server has bad internet speed to mojang's skin servers - the skin also failed to generate for me until I tried using a proxy to speed it up. Somehow this wasn't a issue before 1.20.6.

**Comment by electronicboy** [comment] 2024-07-17 17:41
This is generally a spigot issue, you need to call update() on the profile and then create the itemstack and do whatever in the response if you want to ensure that you properly populate the skull info, otherwise, spigot having made that async means that you enter a pretty tight race condition
