### ISSUE TITLE
Different behavior with armor stands between Vanilla and Paper

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#9616] opened 2023-08-16 09:06 UTC
### Expected behavior

Armor stands do not move when they are fixed in place using cauldrons.

### Observed/Actual behavior

Armor stands in Paper get knocked even though they are fixed in place using cauldrons.

### Steps/models to reproduce

Player provided the following schematic:

https://transfer.sh/p3GJlUr3x1/glass_prison_v3.litematic

Paste the following schematic in both vanilla and paper worlds.
Equip a sweeping edge 3 sword on your hand, get inside the machine and hit the armor stands with the sword.

Vanilla armor stands do not move from their positions, while Paper armor stands get pushed around because of the Sweeping Edge effect. This causes the player to be able to break the glass chamber and escape, which is not possible normally.

### Plugin and Datapack List

No plugins.

### Paper version

This server is running Paper version git-Paper-128 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 47b805f)

### Other

Videos of the schematic provided by the player :

https://youtu.be/QVlQacXBXQ4

https://www.youtube.com/watch?v=3nlcU0V-08k

**Comment by Warriorrrr** [comment] 2023-08-16 10:18
Can confirm with the following simplified setup from the schematic
<img src="https://github.com/PaperMC/Paper/assets/50800980/af6190b1-72e3-4a7d-8c48-4e6368c11e1d" width=50% height=50%>
The armor stand can move a small bit when sprint attacking (no sweeping edge/sword required), but only on the x axis, was not able to reproduce on spigot/vanilla.

**Comment by Lulu13022002** [comment] 2023-10-04 17:49
This has been fixed with the rewrite of some part of the collision system to adhere with more type of voxelshape: mostly [here](https://github.com/PaperMC/Paper/commit/6af97e11b6a5c86dcbae29d554875ee271c5e51c) and the following fixes

**Closed as completed by Lulu13022002** 2023-10-04 17:49 UTC
Labels: type: bug, status: accepted
