### ISSUE TITLE
PlayerArmSwingEvent not cancelling

### ISSUE THREAD

**Issue by Tennessene** [PaperSpigot/Paper#8449] opened 2022-10-09 22:22 UTC
### Expected behavior

If a player swings their arm, the animation should not be seen by the player or at least other players if canceled.

### Observed/Actual behavior

When the player swings their arm, the animation is still seen by everyone even though the event is canceled.

### Steps/models to reproduce

Create a plugin with a PlayerArmSwingEvent listener and set canceled to true.

### Plugin and Datapack List

Chunky, HaloBattles (One of my custom plugins), PlugManX (PlugMan), ProtocolLib, ViaBackwards, ViaVersion, WorldEdit

### Paper version

> version
[17:21:57 INFO]: Checking version, please wait...
[17:21:57 INFO]: This server is running Paper version git-Paper-201 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 57555b8)
You are running the latest version
Previous version: git-Paper-199 (MC: 1.19.2)

**Comment by NubeBuster** [comment] 2022-10-15 20:38
I've looked in the code of paper, if the event is cancelled the ClientboundAnimatePacket is never breadcasted.
This makes me think that the problem is in your code. Could you send the code on how you handle the event?

**Comment by lynxplay** [comment] 2022-10-19 16:21
Yea I cannot replicate this whatsoever. As pointed out by nubebuster, the code here does early return properly which prevents sending the animation packets.

I am closing this as a cannot replicate.
If you have specific steps to replicate this, feel free to provide them here :)

**Closed as not planned by lynxplay** 2022-10-19 16:21 UTC
Labels: type: bug, resolution: cannot reproduce

**Comment by Tennessene** [comment] 2022-10-20 22:11
Sorry for not responding sooner. I must have missed something obvious in my plugin that I couldn’t figure out. Usually that’s what happens. I try to fix some weird error for an hour and I realize I didn’t register it or something dumb like that. 

The code was literally just a listener for PlayerArmSwingEvent and event.setCanceled(true); was inside.

**Comment by NubeBuster** [comment] 2022-10-21 01:38
You should try and reproduce without plugins. Since you have ProtocolLib this might interfere
