### ISSUE TITLE
Monster Spawn Issue

### ISSUE THREAD

**Issue by Draghonir** [PaperSpigot/Paper#9791] opened 2023-10-04 11:20 UTC
### Expected behavior

i think the issue become to bb1c0dd Implement tracking range y setting 

### Observed/Actual behavior

 I noticed that monsters no longer spawn!

### Steps/models to reproduce

When I updated the Paper 1.20.2 jar from build 207 to 212, I noticed that monsters no longer spawn! I haven't changed anything in my configuration; everything was working perfectly before the update. The gamerule "domobspawning" was set to true, and the world was set to difficulty hard. I tried to reproduce the issue on a test server with no plugins, and the same issue occurred - no mobs spawn!

### Plugin and Datapack List

<img width="665" alt="g" src="https://github.com/PaperMC/Paper/assets/107469643/daa5c2de-8451-41c0-b513-b37582f62116">

### Paper version

Paper 1.20.2 build 212

**Comment by Legoman99573** [comment] 2023-10-04 11:34
Can confirm this myself even with plugins installed. Mobs that are already in the world will still be around.

**Comment by Malfrador** [comment] 2023-10-04 12:22
Can confirm, starting build 211. This is caused by the default value for `monster-spawn-max-light-level` (paper world config) being -1, and the server now using that for Monster spawning checks. Because the minimum light level is 0, this check will always fail, causing no monsters to spawn.

As a temporary workaround, setting `monster-spawn-max-light-level` to `0` fixes the issue. 
Of course default config settings shouldn't break vanilla behaviour like this, so this will be fixed properly in a future build.

**Closed as completed** 2023-10-04 17:08 UTC
Labels: type: bug, status: accepted, priority: high
