### ISSUE TITLE
Crashes after 1.19.3 Paper version update

### ISSUE THREAD

**Issue by LoyalPineapple** [PaperSpigot/Paper#8813] opened 2023-01-25 06:55 UTC
### Stack trace

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:657)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:1164)
	at net.minecraft.server.level.ChunkTracker.processTrackQueue(ChunkTracker.java:1266)
	at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:1278)
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:818)
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:649)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:686)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:657)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:1164)
	at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:1266)
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1278)
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:818)
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:649)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:686)

### Plugin and Datapack List

Custom

### Paper version

381

### Other

If the issue is not within Paper but is in a plugin, how would you pinpoint which part of a plugin is causing it?

**Comment by Warriorrrr** [comment] 2023-01-25 07:04
Not a paper issue, a plugin most likely altered the map from another thread. I say most likely there since you skipped listing what plugins you're running.

**Comment by lynxplay** [comment] 2023-01-25 07:08
Closing this as a general duplicate of #6758 or other related issues.
All other instances have been related to plugins accessing internals off the main thread as Warriorrrr pointed out.
Make sure to keep your plugins up to date or try to troubleshoot which plugin is causing this following https://docs.papermc.io/paper/basic-troubleshooting#find-out-what-plugin-is-causing-the-problem.

Feel free to join our [discord](https://discord.gg/papermc) if you have any further questions.

**Closed as not planned by lynxplay** 2023-01-25 07:08 UTC
Labels: resolution: invalid
