### ISSUE TITLE
EntityCombustEvent cancellation can't fully prevent entities from being set on fire

### ISSUE THREAD

**Issue by CofiPRT** [PaperSpigot/Paper#8523] opened 2022-10-29 23:42 UTC
### Expected behavior

Canceling every event of type `EntityCombustEvent` should guarantee no entity ever gets set on fire.

### Observed/Actual behavior

Under conditions that might trigger an `EntityCombustEvent` on the same entity very quickly (every tick), the entity may eventually get set on fire.

### Steps/models to reproduce

For the plugin:
- Use a handler that cancels any `EntityCombustEvent`
- Use a handler that cancels any `BlockIgniteEvent` (to avoid setting fire to a block, and that block, in turn, set fire to the entity)
- (Optional) To better observe the behavior, use a handler that cancels `EntityDamageByEntityEvent` if the damager is a `LightningStrike`

In-game:
- Use an entity of your choosing (e.g.: a `Sheep`)
- In a repeating command block, summon lightning at the sheep's location `execute at @e[type=sheep,limit=1,sort=nearest] run summon minecraft:lightning_bolt`

### Plugin and Datapack List

A simple plugin that includes the aforementioned handlers.
No other plugins or datapacks.

### Paper version

This server is running Paper version git-Paper-246 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: aaf5e39)
You are running the latest version

### Other

Upon following the steps required to reproduce the issue, the sheep shall be set on fire and eventually be killed by the fire.

It's important to mention that running that command **once** will effectively leave the sheep **unharmed**. The problem arises when the lightning bolts are summoned incredibly fast, every tick to be exact.

**Comment by lynxplay** [comment] 2022-10-29 23:57
Notably, this is only an issue specifically related to lightning striking an entity, specifically due to the following excerpt from `net/minecraft/world/entity/Entity.java`:

```java
public void thunderHit(ServerLevel world, LightningBolt lightning) {
    this.setRemainingFireTicks(this.remainingFireTicks + 1);
    // CraftBukkit start
    final org.bukkit.entity.Entity thisBukkitEntity = this.getBukkitEntity();
    final org.bukkit.entity.Entity stormBukkitEntity = lightning.getBukkitEntity();
    final PluginManager pluginManager = Bukkit.getPluginManager();
    // CraftBukkit end

    if (this.remainingFireTicks == 0) {
```

This is done as, by default, the remainingFireTicks are set to `-this.getFireImmuneTicks()` when extinguished.
As the default fire immunity tick is -1, this logic moves the fire ticks up to 0, allowing the if check to pass, calling the `EntityCombustEvent`.

Unfortunately this allows the remainingFireTicks to climb all the way up to 1 (over two ticks), meaning the entity will take fire damage.

A rather straight forward solution here might be to simply *not* increase the `remainingFireTicks` by one and instead checking against the entities `-this.getFireImmuneTicks()`. I have yet to look deep enough into this to figure out if there is any specific reason for this weird logic, so more testing/investigating here is needed.

However this change should be small no matter what, (the alternative being rolling back the `remainingFireTicks` by one tick if the `EntityCombustEvent` was cancelled) and hence I am marking this as a good first issue :)

**Comment by Machine-Maker** [comment] 2022-10-31 03:45
I like your alternative solution better, simply decreasing the `remainingFireTicks` by one if the combust event is canceled.

**Comment by Lulu13022002** [comment] 2022-10-31 12:58
I can also reproduce this with the fire block while moving very fast inside the fire which has the same code pattern

**Comment by lynxplay** [comment] 2022-10-31 13:00
Ah sweet, yea I must have missed that. Looking through at least the existing calls to
`setRemainingFireTicks`, `thunderHit` and `BaseFireBlock` seem to be the only ones using this logic.

**Closed as completed** 2022-10-31 16:31 UTC
Labels: type: bug, status: accepted, good first issue, version: 1.19
