### ISSUE TITLE
Small part of end the biome turn into plains biome 

### ISSUE THREAD

**Issue by ChongJF** [PaperSpigot/Paper#7125] opened 2021-12-15 14:18 UTC
### Expected behavior

It should stay as The End

### Observed/Actual behavior

The biome become plains biome and overworld mobs started to spawn (zombie,creeper,spider)

### Steps/models to reproduce

I am not sure but probally when updating server to 1.18

### Plugin and Datapack List

Plugins (20): AuthMe, CoreProtect, DiscordSRV, EasySetSpawn*, EpicGuard*, Essentials, EssentialsChat, InventoryRollbackPlus, LuckPerms, OreAnnouncer, PlaceholderAPI, ProtectionStones, ProtocolLib, SkinsRestorer, TAB, Themis, UltimateAutoRestart, Vault, WorldEdit, WorldGuard

Datapacks: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-76 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 95d881f)

**Comment by husscraft** [comment] 2021-12-16 14:22
Got the same issue on my server!

**Comment by naunaud84820** [comment] 2021-12-16 22:21
Same for me (end generated in 1.17)
Using papermc 1.18.1 77, screen: https://i.ibb.co/hW9xy6r/2021-12-16-23-13-08.png
we have updated the server at paper 1.18 (maybe n°15) and at 1.17 we used airplane.

**Comment by EterNityCH** [comment] 2021-12-16 22:45
Can you guys provide the version of paper you are running in 1.17? I am trying to recreate this but was not able to. @ChongJF @husscraft 

Also was the chunk in question a newly generated chunk or an old and upgraded chunks?

**Comment by Chew** [comment] 2021-12-17 00:13
And did y'all use `--forceUpgrade`? (If so, DO NOT use it)

**Comment by ChongJF** [comment] 2021-12-17 02:53
> Can you guys provide the version of paper you are running in 1.17? I am trying to recreate this but was not able to. @ChongJF @husscraft
> 
> Also was the chunk in question a newly generated chunk or an old and upgraded chunks?

This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)

**Comment by kennytv** [comment] 2021-12-17 15:07
Can't reproduce this locally, so it'd be nice if someone could provide their 1.17 world where they know/can reproduce that it produces the given issue when upgrading said world to 1.18 on Paper.

**Comment by Spottedleaf** [comment] 2021-12-17 15:08
Can you provide the world pre-conversion? One of the things done during the upgrade process is to make the biome data paletted, so it might be a converter problem.

**Comment by orang3i** [comment] 2021-12-18 08:16
> Can't reproduce this locally, so it'd be nice if someone could provide their 1.17 world where they know/can reproduce that it produces the given issue when upgrading said world to 1.18 on Paper.

yes op chongjf who opened this issue is co owner in my server where this happned i have the 1.17 backup

https://drive.google.com/file/d/1O2PMGmOWx7tUlZBAoogrnkN-edrduty3/view?usp=sharing

![unknown-3.png](https://user-images.githubusercontent.com/86411355/146634542-645c1a3b-4320-474b-8681-d7308ccb5595.png)

**Comment by Spottedleaf** [comment] 2021-12-18 09:07
Fixed by https://github.com/PaperMC/Paper/commit/8c189d0faf0d76465dc39dd1774f5ad67a282229

Let me know if you see any more of this

**Closed as completed by Spottedleaf** 2021-12-18 09:07 UTC
Labels: type: bug

**Comment by captain-reginald** [comment] 2023-03-23 16:15
I didn't notice it until now so it's possible that it happened sooner and I just didn't go to that area before, but I'm having this issue in 1.19.3.
