### ISSUE TITLE
Items modified while saving

### ISSUE THREAD

**Issue by dudullle** [PaperSpigot/Paper#7599] opened 2022-03-14 11:19 UTC
### Expected behavior

When we generate an item with the Adventure API by using :
`Component.text("Bla bla")` for the name and lore, 
We can see by running the command `/data get entity @p SelectedItem` that the item has some data ...

We expect that when we restart the server, items stored in chests has this same data.

### Observed/Actual behavior

Correct data of the item :
![image](https://user-images.githubusercontent.com/12424963/158160182-80713287-8ce0-42b1-a8ab-863c06a94507.png)

Incorrect data of the item :
![image](https://user-images.githubusercontent.com/12424963/158160093-44d558b4-e396-4cf4-b46b-dc6333fbea59.png)

This happens when an item generated with Components is stored in a chest and the server is restarted (to force the map to be saved and loaded from disk)

Another effect of this, we can see that we can't stack correct items with incorrect ones.

### Steps/models to reproduce

- Generate an ItemStack with a name and lore generated from "Component.text(...)"
- Observe the data with `/data get entity @p SelectedItem` while holding the ItemStack in your hand
- Place a chest and place the ItemStack inside this chest
- Stop and Start the server
- Get the ItemStack in the chest
- Observe the data with `/data get entity @p SelectedItem`

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/12424963/158161359-1533c189-4075-4c30-9d3e-a7e599371d78.png)

### Paper version

 This server is running Paper version git-Paper-248 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 1ce3555)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-181 (MC: 1.18.1)

### Other

This issue may happen with inventories. We are using a plugin for player inventories that saves serialized items in a database. On my server, player's inventory items are saved and read right

**Comment by kezz** [comment] 2022-03-14 11:23
This screams that there is some conversion to legacy and back before saving. Doesn't seem like a Paper issue - is most likely an issue with the plugin you're using to serialize items into a database.

**Comment by dudullle** [comment] 2022-03-14 11:23
> This screams that there is some conversion to legacy and back before saving. Doesn't seem like a Paper issue - is most likely an issue with the plugin you're using to serialize items into a database.

I'm not using plugins to serialize data for chests. Only for players AND for players, it works correctly

**Comment by kezz** [comment] 2022-03-14 11:39
And you're sure that this plugin doesn't touch the saving process at all for chests?

Basically, can you provide a MWE?

**Comment by dudullle** [comment] 2022-03-14 12:33
> And you're sure that this plugin doesn't touch the saving process at all for chests?
> 
> Basically, can you provide a MWE?

Done with an empty server, with only the plugin with one command with the following code (And the main that registers the command) :

```
public class CustomItCommand implements CommandExecutor {
    @Override
    public boolean onCommand(@NotNull CommandSender sender, org.bukkit.command.@NotNull Command command, @NotNull String label, @NotNull String[] args) {
        ItemStack it = new ItemStack(Material.DIRT, 32);
        ItemMeta itm = it.getItemMeta();
        itm.displayName(Component.text("§bBla bla"));
        List<Component> cmps = new ArrayList<>();
        cmps.add(Component.text("§aBla bla bla"));

        itm.lore(cmps);
        it.setItemMeta(itm);


        Player p = (Player) sender;
        p.getInventory().addItem(it);
        return true;
    }
}
```
Plugins : (just the test plugin)
![image](https://user-images.githubusercontent.com/12424963/158172202-64583052-f8a3-4d08-952f-f13de17475d9.png)

Generated item : 
![image](https://user-images.githubusercontent.com/12424963/158172318-370de0e2-bd32-41f1-a7b2-0df40ab9322c.png)

Saved & Loaded Item :
![image](https://user-images.githubusercontent.com/12424963/158172399-bfa2454e-521b-4760-a72d-a8bf8436d98b.png)

By using "§" for text colors and bold, It seems that these color codes are translated by Adventure API

⚠️ And without the plugin that manages inventories, the issue is present for player inventories (No need to restart the server to reproduce)

**Comment by kezz** [comment] 2022-03-14 12:49
Have you tried this without abusing components by incorrectly putting legacy section signs in them? This could be triggering the conversion.

Basically, [use Adventure properly](https://docs.adventure.kyori.net/) and create your components correctly (e.g. `Component.text("Bla bla", NamedTextColor.AQUA)`) and see if you're still having this issue.

**Comment by dudullle** [comment] 2022-03-14 13:27
> Have you tried this without abusing components by incorrectly putting legacy section signs in them? This could be triggering the conversion.

Thx for your help, by using the API without the color codes incorrectly, it works !
BTW this is a possible source of issues... i'm probably sure that i'm not the only one who makes this mistake... it may be useful to prevent this by throwing an exception or serialize (this may not be optimized) at the item creation ? (it's just a suggestion to prevent others users to create tickets like i've done)

**Comment by Machine-Maker** [comment] 2022-03-14 18:37
> it may be useful to prevent this by throwing an exception or serialize (this may not be optimized) at the item creation ?

Yeah we tried something similar, warning when the legacy `§` char was detected in components but uh, it got a large response, and there are still a few places where that is the **only** way to change colors. like in PlayerProfile player names (which is a client issue that it works at all but unfortunately it is used by plugins)

**Comment by electronicboy** [comment] 2022-03-15 18:38
Issue here is that the server has logic to detect such broken data and fix it, given that if we don't it creates issues in many dozens of other places due to inconsistent data, not to mention that this is only an issue when you're doing something which is unsupported and going to break anyways

as far as I'm concerned, this is really not an issue, the server is converting mangled itemstack data as expected

**Comment by Machine-Maker** [comment] 2022-03-15 22:30
I agree with cat. `§` chars in the top level of components are converted to a component structure instead of keeping the section char. I think https://github.com/PaperMC/Paper/pull/6704 should fix this in more places making sure things stack that should be able to stack.

**Comment by lynxplay** [comment] 2022-08-08 01:09
This is a non-issue caused by using legacy text format in components which is not supported.
I am closing the issue due to said incorrect usage of adventure. The linked PR might work a bit towards this but this is nothing we want to support anyway :+1:

**Closed as not planned by lynxplay** 2022-08-08 01:09 UTC
Labels: type: bug, resolution: unsupported, version: 1.18
