### ISSUE TITLE
World save error and server hang

### ISSUE THREAD

**Issue by soshimee** [PaperSpigot/Paper#8054] opened 2022-06-26 00:03 UTC
### Stack trace

Save
```
25.06 23:49:55 [Server] ERROR Failed to schedule unload callback for chunk [134217728, 134217728]
25.06 23:49:55 [Server] INFO java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:51) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
25.06 23:49:55 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
25.06 23:49:55 [Server] INFO Caused by: net.minecraft.ReportedException: Exception generating new chunk
25.06 23:49:55 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1305) ~[?:?]
25.06 23:49:55 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.19.jar:?]
25.06 23:49:55 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$39(ChunkTracker.java:1286) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
25.06 23:49:55 [Server] INFO ... 8 more
25.06 23:49:55 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 536871213 out of bounds for length 315
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.Aquifer$NoiseBasedAquifer.getAquiferStatus(Aquifer.java:320) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.Aquifer$NoiseBasedAquifer.computeSubstance(Aquifer.java:188) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.NoiseChunk.lambda$new$0(NoiseChunk.java:133) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.material.MaterialRuleList.calculate(MaterialRuleList.java:14) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.NoiseChunk.getInterpolatedState(NoiseChunk.java:150) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.iterateNoiseColumn(NoiseBasedChunkGenerator.java:189) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.getBaseColumn(NoiseBasedChunkGenerator.java:131) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.structure.structures.NetherFossilStructure.findGenerationPoint(NetherFossilStructure.java:39) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.structure.Structure.generate(Structure.java:83) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.chunk.ChunkGenerator.tryGenerateStructure(ChunkGenerator.java:828) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.chunk.ChunkGenerator.lambda$createStructures$19(ChunkGenerator.java:772) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.chunk.ChunkGenerator.createStructures(ChunkGenerator.java:755) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$2(ChunkStatus.java:51) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:275) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1288) ~[?:?]
25.06 23:49:55 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.19.jar:?]
25.06 23:49:55 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$39(ChunkTracker.java:1286) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
25.06 23:49:55 [Server] INFO ... 8 more
25.06 23:49:55 [Server] ERROR Exception stopping the server
25.06 23:49:55 [Server] INFO java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:51) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
25.06 23:49:55 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
25.06 23:49:55 [Server] INFO Caused by: net.minecraft.ReportedException: Exception generating new chunk
25.06 23:49:55 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1305) ~[?:?]
25.06 23:49:55 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.19.jar:?]
25.06 23:49:55 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$39(ChunkTracker.java:1286) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
25.06 23:49:55 [Server] INFO ... 8 more
25.06 23:49:55 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 536871213 out of bounds for length 315
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.Aquifer$NoiseBasedAquifer.getAquiferStatus(Aquifer.java:320) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.Aquifer$NoiseBasedAquifer.computeSubstance(Aquifer.java:188) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.NoiseChunk.lambda$new$0(NoiseChunk.java:133) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.material.MaterialRuleList.calculate(MaterialRuleList.java:14) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.NoiseChunk.getInterpolatedState(NoiseChunk.java:150) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.iterateNoiseColumn(NoiseBasedChunkGenerator.java:189) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.getBaseColumn(NoiseBasedChunkGenerator.java:131) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.structure.structures.NetherFossilStructure.findGenerationPoint(NetherFossilStructure.java:39) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.levelgen.structure.Structure.generate(Structure.java:83) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.chunk.ChunkGenerator.tryGenerateStructure(ChunkGenerator.java:828) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.chunk.ChunkGenerator.lambda$createStructures$19(ChunkGenerator.java:772) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.chunk.ChunkGenerator.createStructures(ChunkGenerator.java:755) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$2(ChunkStatus.java:51) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:275) ~[paper-1.19.jar:git-Paper-"e4f5e1c"]
25.06 23:49:55 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1288) ~[?:?]
25.06 23:49:55 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.19.jar:?]
25.06 23:49:55 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$39(ChunkTracker.java:1286) ~[?:?]
25.06 23:49:55 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
25.06 23:49:55 [Server] INFO ... 8 more
```

### Plugin and Datapack List

Seems to be unrelated.

### Actions to reproduce (if known)

Teleporting very far out from the center of the world.

### Paper version

```
26.06 00:02:52 [Server] INFO Checking version, please wait...
26.06 00:02:53 [Server] INFO This server is running Paper version git-Paper-"37afe98" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 37afe98)
26.06 00:02:53 [Server] INFO You are running the latest version
26.06 00:02:53 [Server] INFO Previous version: git-Paper-"e4f5e1c" (MC: 1.19)
```

**Comment by NoahvdAa** [comment] 2022-06-26 00:06
Sounds like a duplicate of #7006.

**Comment by soshimee** [comment] 2022-06-26 00:10
By very far out, I mean VERY far out, to the float limit using NBT editing or via API.

**Comment by Owen1212055** [comment] 2022-07-30 04:42
Can reproduce. It might be worth seeing if this still happens on leaf's chunk system recode.

**Comment by Owen1212055** [comment] 2022-09-12 18:39
This is generally a non issue, see the reason behind https://github.com/PaperMC/Paper/issues/7006.
Generally loading chunks this far will cause unexpected/unsupported problems.

**Closed as not planned by Owen1212055** 2022-09-12 18:39 UTC
Labels: type: bug, resolution: won't fix
