### ISSUE TITLE
NoSuchMethodError at Random.nextFloat(float) when running with OpenJDK-17 on alpine

### ISSUE THREAD

**Issue by helightdev** [PaperSpigot/Paper#7138] opened 2021-12-18 19:17 UTC
### Stack trace

```
https://paste.gg/p/anonymous/0ff54ad28a344a1eb480da05afc3fb06
```

### Plugin and Datapack List

None

### Actions to reproduce (if known)

Run the newest version of paper spigot 1.18.1 inside a docker container with the openjdk:17-alpine and wait for a vine to grow

### Paper version

System Info: Java 17 (OpenJDK 64-Bit Server VM 17-ea+14) Host: Linux 5.10.16.3-microsoft-standard-WSL2 (amd64)
/\
Comment: This container is not running in the wsl2 environment directly, although the docker daemon is running inside of wsl2.
The actual server is running on alpine linux

This server is running Paper version git-Paper-81 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8c189d0)

### Other

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Random.html is not listing nextFloat with parameters.

**Comment by kennytv** [comment] 2021-12-18 19:18
Your Java version is outdated (duplicate of #7062)

**Closed as completed by kennytv** 2021-12-18 19:18 UTC
Labels: resolution: duplicate, resolution: invalid
