### ISSUE TITLE
`delay-chunk-unloads-by` is ignored

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#9200] opened 2023-05-10 16:49 UTC
### Expected behavior

Chunk unloads should be delayed by specified amount of time, allowing, for example, to teleport tamed mobs to the player who teleported from one location to other using plugin command, or to reduce the disk load in case of the player moves between two locations too often.

### Observed/Actual behavior

Chunks gets unloaded immediately after the last player leaves them.

### Steps/models to reproduce

See [this](https://discord.com/channels/289587909051416579/289587909051416579/1105804318721970196) message in Paper Discord server.

### Plugin and Datapack List

Essentials, LuckPerms, Vault... I think it's not important, since the issue is addressed [here](https://discord.com/channels/289587909051416579/289587909051416579/1105894991395565770).

### Paper version

```json
"currentVersion": "git-Paper-527 (MC: 1.19.4)"
```

**Comment by lynxplay** [comment] 2023-05-10 16:55
Duplicate of https://github.com/PaperMC/Paper/issues/8731

**Closed as not planned** 2023-05-10 16:56 UTC
Labels: type: bug, resolution: duplicate
