### ISSUE TITLE
Mobs don't get knockback when in fire.

### ISSUE THREAD

**Issue by Letrixix** [PaperSpigot/Paper#7189] opened 2021-12-25 13:05 UTC
### Expected behavior

The mobs should always get knockback.

### Observed/Actual behavior

Mobs don't get knockback when in fire (block)

### Steps/models to reproduce

https://drive.google.com/file/d/1cM1wCKFs0NWYmNrY6uubVt3Jz4FjYNuR/view?usp=sharing

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/87038960/147385491-cbaa2084-f2e2-4453-9595-723abbc5bcc0.png)
(a new server)
![image](https://user-images.githubusercontent.com/87038960/147385507-fd5c2b2b-1bde-484f-b53b-bcaebb318102.png)

### Paper version

This server is running Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 464b171)§r

**Comment by Machine-Maker** [comment] 2021-12-25 18:10
This is either intended or a vanilla bug. I get the same results in vanilla singleplayer, can you confirm that?

**Comment by Machine-Maker** [comment] 2021-12-25 18:17
Actually, this was [already reported to the Official Minecraft Bug Tracker](https://bugs.mojang.com/browse/MC-100769) and marked as "Works as Intended".

**Closed as completed by Machine-Maker** 2021-12-25 18:17 UTC
Labels: type: bug, resolution: works as intended
