### ISSUE TITLE
EAR doesn't work correctly

### ISSUE THREAD

**Issue by Krakenied** [PaperSpigot/Paper#11073] opened 2024-07-14 11:53 UTC
### Expected behavior

Monsters shouldn't move, unless I'm in 1 block distance from them. On Spigot, it seems to be _much less reproducible_. Yeah, I know it sounds weird. I haven't noticed the issue to affect animals, however it may be an incorrect assumption.

### Observed/Actual behavior

Monsters move. It happens only sometimes - maybe after generation/spawn/chunk load?

### Steps/models to reproduce

```
    entity-activation-range:
      animals: 1
      monsters: 1
      raiders: 1
      misc: 1
      water: 1
      villagers: 1
      flying-monsters: 1
      wake-up-inactive:
        animals-max-per-tick: 0 # 4
        animals-every: 1200
        animals-for: 100
        monsters-max-per-tick: 0 # 8
        monsters-every: 400
        monsters-for: 100
        villagers-max-per-tick: 0 # 4
        villagers-every: 600
        villagers-for: 100
        flying-monsters-max-per-tick: 0 # 8
        flying-monsters-every: 200
        flying-monsters-for: 100
      villagers-work-immunity-after: 100
      villagers-work-immunity-for: 20
      villagers-active-for-panic: true
      tick-inactive-villagers: true
      ignore-spectators: false
```

### Plugin and Datapack List

n/a

### Paper version

```
> version
[13:20:26 INFO]: Checking version, please wait...
[13:20:26 INFO]: This server is running Paper version 1.21-63-master@2288e13 (2024-07-13T18:51:26Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-DEV-ea5f7d2 (MC: 1.21)
```

### Other

https://github.com/user-attachments/assets/38ef1b24-17e0-48c9-90ef-9f5d142333aa

Useless video details:
The Spigot version used: `CraftBukkit version 4263-Spigot-491f367-bed1e3f`
World seed: `6680692373436498971`
Coordinates: `-150 100 9750`

**Comment by Krakenied** [comment] 2024-07-14 11:57
Oh, and there's the video

https://github.com/user-attachments/assets/38ef1b24-17e0-48c9-90ef-9f5d142333aa

**Comment by electronicboy** [comment] 2024-07-14 12:30
This generally looks like this is working as intended, EAR, and especially EAR 2, is not designed to entirely take mobs out of the active range out of the game, I can expand upon this after I've woken up and recovered more IQ points for the day

**Comment by lynxplay** [comment] 2024-07-15 16:56
To go a bit further here, EAR is not supposed to be a replacement for simulation distance, as in, it does not offer a hard cap between ticking and non-ticking.

Entities already have a lot of triggers that mark them immune to EAR for a set amount of ticks based on state or events.
Or via things like the wake-up function defined in your config. EAR is hence more a reduction of ticks needed on entities in its range than a full stop to their activity.

I'll be closing this as "works as intended" thank you anyway for the detailed repot! I hope my explanation makes sense.

**Closed as not planned by lynxplay** 2024-07-15 16:56 UTC
Labels: type: bug, resolution: works as intended, version: 1.21
