### ISSUE TITLE
server crashes after using structure command

### ISSUE THREAD

**Issue by RambonL** [PaperSpigot/Paper#7963] opened 2022-06-13 09:33 UTC
### Stack trace

https://paste.gg/p/anonymous/da0951225a644fb1b6509caf4b856dfc

### Plugin and Datapack List

GeyserMC
Floodgate

### Actions to reproduce (if known)

/locate structure minecraft:village_desert

### Paper version

> version
[11:14:48 INFO]: Checking version, please wait...
[11:14:48 INFO]: This server is running Paper version git-Paper-8 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e4f5e1c)
You are running the latest version
Previous version: git-Paper-4 (MC: 1.19)
>

**Comment by rm20killer** [comment] 2022-06-13 11:06
experienced this issue too, but issue is upstream. It also freeze the game in singleplayer
https://bugs.mojang.com/browse/MC-250276

**Comment by electronicboy** [comment] 2022-06-13 14:55
Expensive command loads upto like 10k chunks (ignoring all of the extra chunks generated for the process of actually generating those 10k chunks if it tries), duplicate of #2312

**Closed as not planned by electronicboy** 2022-06-13 14:55 UTC
Labels: type: bug, resolution: duplicate, version: 1.19
