### ISSUE TITLE
Spectator doesn't have no-clip

### ISSUE THREAD

**Issue by zai4z** [PaperSpigot/Paper#9146] opened 2023-04-17 20:24 UTC
### Expected behavior

Spectator should be able to phase through walls by default

### Observed/Actual behavior

https://user-images.githubusercontent.com/79854735/232601324-2b7b5d9e-5031-4bb7-8640-6a6bbafd3b50.mp4

### Steps/models to reproduce

https://user-images.githubusercontent.com/79854735/232601379-d6b5aaf2-1de7-4e6a-b65c-313a20b525f0.mp4

### Plugin and Datapack List

![2023-04-17_21 22 36](https://user-images.githubusercontent.com/79854735/232601737-34b081e1-547a-4886-8d54-84fe85249da3.png)

### Paper version

paper-1.19.4-514

**Comment by electronicboy** [comment] 2023-04-17 20:25
are you able to reproduce without plugins on the server? (and the proxy if using one)

**Comment by zai4z** [comment] 2023-04-17 21:25
I just restarted server... and it worked initially but after teleporting it stopped working

**Comment by potatoru** [comment] 2023-04-18 08:09
I have the same issue after updating to 1.19.4. I would check it without plugins.

**Comment by Leguan16** [comment] 2023-05-12 18:15
Can not reproduce with a fresh 1.19.4-528 server (no plugins).

https://github.com/PaperMC/Paper/assets/59799222/9aa3560d-edfd-4d1b-998a-5ef6328a9bad

(also does work as intended for walls)

**Comment by electronicboy** [comment] 2023-05-12 18:17
Closing, this is pretty much always down to plugins messing with stuff breaking the clients mapping of attributes

**Closed as not planned by electronicboy** 2023-05-12 18:17 UTC
Labels: type: bug
