### ISSUE TITLE
Add Spigot support for `PathfinderGoal#j()`

### ISSUE THREAD

**Issue by gmitch215** [PaperSpigot/Paper#9201] opened 2023-05-10 18:43 UTC
### Is your feature request related to a problem?

Currently, Paper has removed the default `PathfinderGoal#getFlags` method, making frameworks and other NMS-dependent plugins that rely on fetching PathinferGoal flags incompatible with Paper and its forks.

Adding or reworking the current method of fetching the EnumSet of PathfinderGoal flags should help frameworks like my [MobChip](https://github.com/GamerCoder215/MobChip) framework have PaperMC support.

### Describe the solution you'd like.

Add or rework the current method to fetch all of the flags present in a PathfinderGoal, implementing support for Spigot plugins and frameworks that rely on the method to fetch information

### Describe alternatives you've considered.

No current alternatives, affects most paper forks

**Comment by Malfrador** [comment] 2023-05-10 18:46
The method isn't removed, the return type was just changed to a `com.destroystokyo.paper.util.set.OptimizedSmallEnumSet<Goal.Flag>` to get rid of the Stream in the PathfinderGoalSelector.

**Comment by lynxplay** [comment] 2023-05-10 19:32
Yea I don't think there is a nice or simple way to bring this back.
The small enum set there is pretty essential for the rest of the patch.
Beyond that, messing with internals is still messing with internals, you are in unsupported land. As pointed out above, you should be able to work around this pretty nicely with some logic that abstracts the `Goal#getFlags` method into some type that is usable for you.

I'll be closing this for now, if anyone has some nice proposal on how to provide this functionality without extra performance overhead or compatibility loss on papers side, I'd be more than happy to reopen this.

**Closed as not planned by lynxplay** 2023-05-10 19:32 UTC
Labels: resolution: won't fix, type: feature

**Comment by GamerCoder215** [comment] 2023-05-10 22:08
> Yea I don't think there is a nice or simple way to bring this back. The small enum set there is pretty essential for the rest of the patch. Beyond that, messing with internals is still messing with internals, you are in unsupported land. As pointed out above, you should be able to work around this pretty nicely with some logic that abstracts the `Goal#getFlags` method into some type that is usable for you.
> 
> I'll be closing this for now, if anyone has some nice proposal on how to provide this functionality without extra performance overhead or compatibility loss on papers side, I'd be more than happy to reopen this.

The issue isn't that the **type** needs to change persay, but the name of the method instead, since the optimized `getFlags` method is ignored for obfuscation. I'm willing to use reflection for Paper support, but there is a much larger and bigger community in using Spigot API for **development** than as a server **software**, so I probably will not drop Spigot in the future.

A middle ground would either be renaming or reobfuscating the method in future builds or creating a bridge method of the same name that returns the same thing.

**Comment by lynxplay** [comment] 2023-05-11 05:32
>  but the name of the method instead

Yea, that would be an obvious way, however would break those plugins that already use said method internally.
We'd be evaluating between breaking plugins that use paper internals vs leaving plugins that use spigot internals broken :/
(using the fact that our `getFlags` method is not obfuscated is not really viable down the line as we also provide mojang mapped server instances)

We cannot *effectively* create a bridge method with the same name, same parameters but different return type as overloading on return types is generally prohibited by the compiler.

We could however look into a simple way to compute an EnumSet from the returned SmallEnumSet, tho that code should be so simple that it would be easier to just write it yourself in your plugin, returning generally all of this to "you are using internals, you will sadly have to live with the consequences", wich don't get me wrong, I wish you wouldn't have to, keeping compatibility with spigot would be great here, I just don't see a nice way forward that does not infringe on my above criteria
that is:

>  without extra performance overhead or compatibility loss on papers side

I hope you can understand my points here 🙂

**Comment by GamerCoder215** [comment] 2023-05-11 16:09
> There’s like zero reason to account for this. NMS compatibility with spigot is not promised in any way.

> note that that method is also exposed via paper api, so that makes it even more unlikely that we will fix nms compat, especially since that page is pretty old.

I know this may sound a bit petty (and I fully understand why you probably won't implement this), but it may be fairer to specify that Paper **does** heavily modify NMS internals (for good performance reasons) and may not have full compatibility with **all** spigot plugins, as stated [here](https://docs.papermc.io/paper/migration):

> Paper retains full compatibility with all Spigot plugins, allowing a seamless transition. 

That way I (as well as future devs) don't get confused about why Paper isn't compatible with Spigot NMS internals.
