### ISSUE TITLE
1.21.3-12 fatal error on launching

### ISSUE THREAD

**Issue by RetroQuiCoule** [PaperSpigot/Paper#11579] opened 2024-11-04 21:34 UTC
### Expected behavior

I expected to launch my server on my ubuntu VM.

### Observed/Actual behavior

When I launched my paper.jar file, everything load, without plugins. when the server show "Done". It crash and show this Java error.
It append only with the 1.21.3 version of paper.
I tried on my 1.20.4 server and everything was perfect.
[hs_err_pid2218781.log](https://github.com/user-attachments/files/17624025/hs_err_pid2218781.log)

### Steps/models to reproduce

Launch paper on an ubuntu 22.04.4 distrib

### Plugin and Datapack List

no datapack, no plugin

### Paper version

paper 1.21.3-12
#11561

### Other

Good luck and you do an really amazing work thank you

**Comment by electronicboy** [comment] 2024-11-04 21:41
https://github.com/async-profiler/async-profiler/issues/1045

**Comment by electronicboy** [comment] 2024-11-10 04:42
Use Java 21, the profiler library version spark uses does not support 23

**Comment by FoxWhiskey** [comment] 2024-11-10 11:35
**Awesome!**
I can confirm that Java 23 actually is incompatible! I downgraded to Java 21 and have not observed any crashes since then.
Thank you so much for this valueable hint!

On a side note - @RetroQuiCoule  also uses Java 23.

**Comment by codebycam** [comment] 2024-11-16 01:47
There is an open PR to update the async-profiler in spark that will resolve this issue: https://github.com/lucko/spark/pull/386.

**Comment by kennytv** [comment] 2024-11-21 09:43
Should be fixed https://github.com/PaperMC/Paper/commit/c28d89d625c60243c52857e0c7e6398b73602156

**Closed as completed by kennytv** 2024-11-21 09:43 UTC
Labels: type: bug
