### ISSUE TITLE
Block Microsoft Telemetry, Content Moderation, & Strip Client Accessible User Identifiers

### ISSUE THREAD

**Issue by Zaptosis** [PaperSpigot/Paper#8065] opened 2022-06-28 05:43 UTC
### Is your feature request related to a problem?

Microsoft is killing Minecraft Java edition & destroying the independence server owners to run their own communities as they see fit.

Content moderation & any Microsoft access to a private server at all is antithetical to the openness & freedom of Minecraft players & server owners which played a huge part in its growth as the world more successful game.

As a community we must declare total war on Microsoft.

### Describe the solution you'd like.

Modify the paper jar file file to block **all** Microsoft telemetry & strip out all user identifiers from being accessible by the local game clients, making it impossible to verify messages & user activity by the local client to eliminate the possibility of client side reporting.

### Describe alternatives you've considered.

If Paper is unwilling to block Microsoft & strip user identifiers then independent plugin developers should silently introduce this functionality into their own plugins in protest of content moderation & multiplayer bans.

If 20% of plugin devs being blocking Microsoft then it would essentially ensure the vast majority of modded servers are inaccessible by Microsoft since most servers have 30 plugins.

Maybe create an open source drop in code for devs to paste into their plugins that combat content moderation.

**Comment by NoahvdAa** [comment] 2022-06-28 05:48
Duplicate of #8043. If you want to disable chat reporting, use a plugin for it, Paper will not have an option for it. Also, the alternative you propose would probably be considered malicious by most platforms and get the plugin authors banned.

**Comment by Zaptosis** [comment] 2022-06-28 05:55
@NoahvdAa Please explain in what world protecting user privacy is "malicious"? Is this 1984 double speak, or have you truly drank the kool-aid?

**Closed as not planned** 2022-06-28 05:55 UTC
Labels: resolution: duplicate, type: feature

**Comment by Machine-Maker** [comment] 2022-06-28 05:57
This is not the place for this discussion, please use our forums (there is already [a thread on this topic](https://forums.papermc.io/threads/mojang-chat-report.371/)), or read though the issue this duplicates.

**Comment by Zaptosis** [comment] 2022-06-28 05:58
@Machine-Maker This is not a duplicate, the issue Noah references mainly talks about user identifiers, this is more broadly about blocking all Microsoft telemetry & increasing the privacy protections of paper. Removing signatures is just 1 part of the puzzle proposed here.

**Comment by Machine-Maker** [comment] 2022-06-28 06:06
I don't think the java server sends any telemetry in the first place, the snooper is on the client. So all that's left in your issue, is duplicated by the mentioned issue.

**Comment by Zaptosis** [comment] 2022-06-28 06:09
Oof, I assumed they would run that on the server. I don't know anything about java, but I feel like this would still work, especially the alternative plan to introduce private protecting guerrilla warfare tactics by independent plugin devs.

Do you think this could be an effective tactic to combat content moderation?

**Comment by Machine-Maker** [comment] 2022-06-28 06:10
Literally https://github.com/PaperMC/Paper/issues/8065#issuecomment-1168260884

**Comment by Zaptosis** [comment] 2022-06-28 06:11
lol I don't use GitHub, idk the culture here; but as you wish I'll go there
