### ISSUE TITLE
obfuscated plugin breaks after remapping

### ISSUE THREAD

**Issue by rudde0** [PaperSpigot/Paper#11504] opened 2024-10-20 09:23 UTC
### Expected behavior

it should loaded correctly (by skip remapping task or we can add a value in plugin.yml to disable plugin remapping)

### Observed/Actual behavior

plugin doesn't load by the server unless I add `-Dpaper.disablePluginRemapping=true` to JVM flags

```
[12:18:58 INFO]: [PluginRemapper] Remapping plugin 'plugins\Wind-1.30.3.jar'...
[12:18:58 ERROR]: [PluginRemapper] Encountered exception remapping plugins
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\Wind-1.30.3.jar'
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\Wind-1.30.3.jar'
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:358) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Failed to execute task me/creeper/wind/a
        at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:56) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:177) ~[purpur-1.21.1.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:95) ~[purpur-1.21.1.jar:?]
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Duplicate key a (attempted merging values private final me/creeper/wind/a/a Ljava/util/Map; and private static final me/creeper/wind/a/a [Ljava/lang/String;)
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:52) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:177) ~[purpur-1.21.1.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:95) ~[purpur-1.21.1.jar:?]
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[purpur-1.21.1.jar:1.21.1-2323-4671e1e]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.lang.IllegalStateException: Duplicate key a (attempted merging values private final me/creeper/wind/a/a Ljava/util/Map; and private static final me/creeper/wind/a/a [Ljava/lang/String;)
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135) ~[?:?]
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182) ~[?:?]
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.neoforged.art.internal.ClassProviderImpl$ClassInfo.<init>(ClassProviderImpl.java:122) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.ClassProviderBuilderImpl.lambda$addClass$1(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at net.neoforged.art.internal.ClassProviderBuilderImpl.addClass(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.lambda$run$2(RenamerImpl.java:178) ~[purpur-1.21.1.jar:?]
        at net.neoforged.art.internal.AsyncHelper.lambda$null$0(AsyncHelper.java:33) ~[AutoRenamingTool-2.0.3.jar:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        ... 3 more
```

### Steps/models to reproduce

I can share the plugin with paper devs but I can't share publicly.

1. Load the obfuscated plugin
2. Try to boot the server with paper remapping

### Plugin and Datapack List

Not relevant with other plugins.

/plugins doesn't show the obfuscated and remapped plugin's name.

### Paper version

Current Purpur Version: 1.21.1-2323-4671e1e (MC: 1.21.1)*
* You are 3 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21.1-2313-20fa61e (MC: 1.21.1)

**Comment by Warriorrrr** [comment] 2024-10-20 09:26
Duplicate of #11005, see the recommendations in the comment there

**Closed as not planned by Warriorrrr** 2024-10-20 09:26 UTC
Labels: type: bug, resolution: duplicate

**Comment by rudde0** [comment] 2024-10-20 10:35
I have recommendation instead of just a post the issue.

Why don't we just add an option to disable-remapping in plugin.yml?

**Comment by electronicboy** [comment] 2024-10-20 10:55
You can mark your plugin as being mojmap compatible to skip the remapper, but, you really should fix your jar file being improperly packaged

**Comment by rudde0** [comment] 2024-10-20 11:25
I don't have the source code.

**Comment by electronicboy** [comment] 2024-10-20 11:28
if you can modify the plugin.yml you can modify/add the `META-INF/MANIFEST.MF` file manually to add that metadata manually

**Comment by bilektugrul** [comment] 2024-10-20 13:40
> if you can modify the plugin.yml you can modify/add the `META-INF/MANIFEST.MF` file manually to add that metadata manually

We are adding ``paperweight-mappings-namespace: spigot`` to MANIFEST.MF but it does not change anything.

**Comment by electronicboy** [comment] 2024-10-20 13:44
spigot is the assumed default, given that we use mojmap, we'd need to remap anything that is spigot mapped; utilise the mojang one to say that it's already mapped in a supported manner for your server

**Comment by bilektugrul** [comment] 2024-10-20 14:03
> spigot is the assumed default, given that we use mojmap, we'd need to remap anything that is spigot mapped; utilise the mojang one to say that it's already mapped in a supported manner for your server

Even when its ``paperweight-mappings-namespace: mojang+yarn``, Paper tries to remap it.
