### ISSUE TITLE
Entity#setTarget has no effect

### ISSUE THREAD

**Issue by dev-json** [PaperSpigot/Paper#11129] opened 2024-07-21 03:37 UTC
### Expected behavior

Normally the Entity#setTarget method should override/untarget the current target of a mob

### Observed/Actual behavior

In the current state this method is not setting the target due the mob memory(brain + MemoryModuleType.ATTACK_TARGET) which still keeps the target.

- [ ] 

### Steps/models to reproduce

1. Create a mob (a piglin for example)
2. Let the piglin targetting you
3. After some time (BukkitScheduler) or conditions try to set the target on "null"
4. The mob is still attacking you and the target has not been updated!

### Plugin and Datapack List

None

### Paper version

This server is running Paper version git-Paper-461 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: b600140)
You are 36 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.20.6-130-5d8e53d (MC: 1.20.6)

### Other

Im not sure if this is a possible bug, just wanted to mention this behavior.
You can get around this problem, if you clear the ATTACK_TARGET memory from the mob, but this makes the #setTarget method useless.

**Comment by Warriorrrr** [comment] 2024-07-21 09:11
This seems like a possible duplicate of #6862

**Comment by electronicboy** [comment] 2024-07-21 12:44
Duplicate of #6862 
The problem here is that newer mobs use a much different system for this stuff rather than just *an* field stored on the entity, there are more data points which need to be handled to properly manage the entities and their state without shotgunning side effects

**Closed as completed by electronicboy** 2024-07-21 12:44 UTC
Labels: type: bug, resolution: duplicate, version: 1.20.4
