### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by 2279881513** [PaperSpigot/Paper#9308] opened 2023-06-11 13:17 UTC
### Stack trace

https://paste.gg/p/anonymous/f2d8e23342cb48ea8fc7e1684e49bd47
https://paste.gg/p/anonymous/53000b2e90984df0b25b0f60c72c97d0

### Plugin and Datapack List

[21:16:57 INFO]: Server Plugins (22):
[21:16:57 INFO]: Bukkit Plugins:
[21:16:57 INFO]:  - *AntiCropTrample, CoreProtect, DeathCommands, DieMsgQG, 更多附魔, GSit, Images, InventoryRollbackPlus, ItemNBTEdit, JoinCommand
[21:16:57 INFO]:  LuckPerms, NexEngine, OpenInv, PlaceholderAPI, ProtocolLib, ProtocolStringReplacer, SkinsRestorer, SpawnLimit, SuperVanish, ViaBackwards
[21:16:57 INFO]:  ViaVersion, Xm

[21:17:11 INFO]: There are 5 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/Terralith_1.19.4_v2.3.7.zip (world)], [file/rainbeau-s-ocean-villages-19-220922.zip (world)], [file/rainbeau-s-ships-on-seas-19-220922.zip (world)]
[21:17:11 INFO]: There are no more data packs available

### Paper version

[21:15:11 INFO]: Checking version, please wait...
[21:15:14 INFO]: This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version
Previous version: git-Paper-"bcec5b1" (MC: 1.19.4)

### Other

What is the problem? Why did it crash?

**Comment by lynxplay** [comment] 2023-06-11 15:43
Duplicate of #9234, spiders generating off thread still call an on-thread event right now.

**Closed as not planned by lynxplay** 2023-06-11 15:43 UTC
Labels: resolution: duplicate, version: 1.19.4

**Comment by 2279881513** [comment] 2023-06-12 00:09
Please solve this as soon as possible.
