### ISSUE TITLE
Flat bedrock doesn't seem to work on newer versions.

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#9586] opened 2023-08-08 02:05 UTC
### Expected behavior

On 1.20.1, flat bedrock doesn't work. Well, yeah, it's supossed to work, and make all bedrock flat. It works on 1.18.2.

### Observed/Actual behavior

Bedrock generated normally, but it isn't supossed to. It's supossed to be flat.

### Steps/models to reproduce

1.- Install Paper, 1.20.1
2.- Enable "flat-bedrock" setting. Set it to true.
3.- Dig straight down
4.- Cry because it didn't work

### Plugin and Datapack List

ViaVersion & ViaBackwards. No datapacks.

### Paper version

This server is running Paper version git-Paper-108 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: d6d2b6f)
You are running the latest version
Previous version: git-Paper-388 (MC: 1.18.2)

### Other

The setting doesn't work in newever versions (1.20.1 tested). It works on 1.18.2, as far as I have tested.

**Comment by Owen1212055** [comment] 2023-08-08 02:16
Dupe of https://github.com/PaperMC/Paper/issues/8954

**Closed as not planned by Owen1212055** 2023-08-08 02:16 UTC
Labels: type: bug, resolution: duplicate
