### ISSUE TITLE
Players gets kicked from a server due to out-of-order chat

### ISSUE THREAD

**Issue by LielSadchip** [PaperSpigot/Paper#9594] opened 2023-08-10 17:46 UTC
### Expected behavior

I would like to this problem be fixed somehow, thank you.
Or at least get some advice

### Observed/Actual behavior

I dont know how to fix it or where to find answers, the last post about this issue was almoust a year ago.
A few players from my server being kicked for writing simple message or commands in chat for "out-of-order chat" (server console) (multiplayer.disconnect.out_of_order_chat in velocity console).
Some of them already used to it, but a few still pretty angry about it.
Server is running on Paper-307 (MC: 1.19.2)

Thank you in advance for help.

### Steps/models to reproduce

![image](https://github.com/PaperMC/Paper/assets/141951472/b41651f8-fb88-4ca1-bb84-bec9d8e16143)

### Plugin and Datapack List

Plugins (24): ajLeaderboards, AntiPopup, ChatEx, CoreProtect, DeluxeMenus, EasyWhitelist*, Essentials, EssentialsSpawn, gJoin*, Harbor, HolographicDisplays, LuckPerms, Multiverse-Core, Orebfuscator, PL-Hide, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, SkinsRestorer, TAB, ViaVersion, Vulcan, WorldEdit, WorldGuard

There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### Paper version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

**Comment by lynxplay** [comment] 2023-08-10 17:54
Generally, ensure that the system time on your PC is correct. The players that are affected should do the same.
This is generally caused by a chat message being processed that claims to have been created before the previous chat message sent by said player.

Beyond this, you are using a no longer maintained version of paper, hence I'll be closing this.
Feel free to shoot by in our [discord](https://discord.gg/papermc) if you need further help if you decide to use a supported version.

**Closed as not planned by lynxplay** 2023-08-10 17:54 UTC
Labels: type: bug, version: 1.19.2

**Comment by TetraTheta** [comment] 2023-08-10 18:53
Just for your information, but this behavior is likely to be fixed in next Minecraft version, maybe 1.20.2.  
In [Minecraft Snapshot 23w32a](https://www.minecraft.net/en-us/article/minecraft-snapshot-23w32a), they added this note:
> * Clients will no longer disconnect themselves when receiving an invalid chat message
>   * A placeholder message will instead be shown in chat

Sorry for sending message in closed issue!

**Comment by electronicboy** [comment] 2023-08-10 21:14
> Just for your information, but this behavior is likely to be fixed in next Minecraft version, maybe 1.20.2.
In [Minecraft Snapshot 23w32a](https://www.minecraft.net/en-us/article/minecraft-snapshot-23w32a), they added this note:

that is primarily intended for the client disconnecting itself due to an out of order chat message, not the server; 

For velocity, this is generally a known bug but sadly I don't have hardware able to work on much atm, https://github.com/PaperMC/Velocity/pull/1042 from a quick looks moves chat on velocity to generally work how I said it should, and so *should* resolve this issue, but need people to test it given my lack of means to do so

**Comment by 7wOv6ySCjo** [comment] 2026-04-25 10:50
> > Just for your information, but this behavior is likely to be fixed in next Minecraft version, maybe 1.20.2.
> > In [Minecraft Snapshot 23w32a](https://www.minecraft.net/en-us/article/minecraft-snapshot-23w32a), they added this note:
> 
> that is primarily intended for the client disconnecting itself due to an out of order chat message, not the server;
> 
> For velocity, this is generally a known bug but sadly I don't have hardware able to work on much atm, [PaperMC/Velocity#1042](https://github.com/PaperMC/Velocity/pull/1042) from a quick looks moves chat on velocity to generally work how I said it should, and so _should_ resolve this issue, but need people to test it given my lack of means to do so

The bug is still occurring in version 26.1.2
We get the error: ‘keepalive: time out (out of order!)’
Several disconnections a day for various players.

I'm not entirely sure whether it's an ‘out of order’ error with keepalive packets or with the chat specifically. The strange thing is that you don't even need to type commands or send messages in the chat; just exploring the world for a few minutes is enough to trigger this ‘timeout’ error.
