### ISSUE TITLE
Scheduler Timings don't work during Recursive scheduling

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#10426] opened 2024-04-17 13:51 UTC
### Expected behavior

if I schedule something in a scheduled runnable then my scheduled runnable should run in the amout of ticks I specified.

### Observed/Actual behavior

the scheduled runnable runs instanly

### Steps/models to reproduce

try scheduling something in a scheduled runnable

### Plugin and Datapack List

no other plugins

### Paper version

[15:50:38 INFO]: Checking version, please wait...
[15:50:38 INFO]: This server is running Paper version git-Paper-451 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: ab1afb0)
You are 34 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-340 (MC: 1.20.4)

**Comment by Nacioszeczek** [comment] 2024-04-17 13:52
Please provide code that you believe doesn't work as intended and update your server.

**Comment by lynxplay** [comment] 2024-04-21 00:57
Closing this as it is missing a code example.

If you have a code example for your issue, feel free to post it below and we can reopen the issue :)

**Closed as not planned by lynxplay** 2024-04-21 00:57 UTC
Labels: type: bug, resolution: invalid
