### ISSUE TITLE
Command tab completion is temperamental in Java 17

### ISSUE THREAD

**Issue by james090500** [PaperSpigot/Paper#6936] opened 2021-11-25 18:27 UTC
### Expected behavior

When typing "/" command should offer auto complete suggestions.
![image](https://user-images.githubusercontent.com/20372645/143487784-32ffb054-7e71-49ef-a060-3954b1cc05af.png)

### Observed/Actual behavior

When typing "/" no commands are suggested. Also all commands are shown as "Not found"
![image](https://user-images.githubusercontent.com/20372645/143487848-d3601ea0-470b-4a59-8a15-99d4d688a1d0.png)
![image](https://user-images.githubusercontent.com/20372645/143487857-d4125e52-e660-413d-9dc3-64d4a2279e69.png)

### Steps/models to reproduce

We are struggling to replicate this issue but we have identified it only happens on Java 17 and affected servers will work on Java 16.
This can happen with no plugins as well. 

### Plugin and Datapack List

[19:25:54 INFO]: Plugins (15): CapeCraftProxy, ChatControlRed, Essentials, EssentialsSpawn, HeadDatabase, JetsAntiAFKPro, LiteBans, LuckPerms, PlaceholderAPI, ProtocolLib, TAB, TAB-BukkitBridge, Vault, VoidGen, WorldEdit

[19:25:56 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[19:25:56 INFO]: There are no more data packs available

### Paper version

version
[19:26:12 INFO]: This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
You are running the latest version

### Other

timings report
[19:27:07 INFO]: Preparing Timings Report...
[19:27:08 INFO]: View Timings Report: https://timings.aikar.co/?id=d7b53960850345faa6639d03cd7a96ef

**Comment by NotMyFault** [comment] 2021-11-25 18:32
It might be worth to reproduce without plugins, include the exact Java version and which vendor you're using it from and your full OS version. Tab completion works fine for me, but I've seen similar issues on the discord over the past couple of days.

Given a more comprehensive test:
| Paper version | OS version | Java Version | Result |
| ----------- | ----------- |----------- |----------- |
| 1.17-388 | Windows v21H2 (22000.348) | openjdk Corretto 17.0.1.12.1 | Can't replicate |
| 1.17-388 | macOS 12.0.1 v21A559 | openjdk Temurin 17.0.1+12 | Can't replicate |

**Comment by james090500** [comment] 2021-11-25 21:38
Just spun up a test server and managed to replicate this. No plugins or config changes. This is on the same Pterodactyl node etc. 

![image](https://user-images.githubusercontent.com/20372645/143501286-8d9bb23b-e500-47a1-9adc-5656f278c6b1.png)

https://timings.aikar.co/?id=1817585c13b64ffeb65f8ff11c61926e

| Paper version | OS version | Java Version | Result
| -- | -- | -- | -- |
|1.17-388|Debian 11 5.10.0-8-amd64|Unknown|Replicate

I can't figure out the Java version but the image in use is `ghcr.io/pterodactyl/yolks:java_17`

**Comment by lynxplay** [comment] 2021-11-25 21:59
I cannot reproduce this with the specified `ghcr.io/pterodactyl/yolks:java_17` container. The yolk images ship the [openjdk](https://hub.docker.com/layers/openjdk/library/openjdk/17-slim/images/sha256-f79c5855377d924c417e4eb235a976cea09107ab84afe730b92933a0e051fa02?context=explore) image as their base and use its java.

For reproducibility, here is my docker cli invocation to automatically download and start the latest paper version:
```bash
docker run --rm -p 25565:25565 -it ghcr.io/pterodactyl/yolks:java_17 bash -c 'curl https://papermc.io/api/v2/projects/paper/versions/1.17.1/builds/388/downloads/paper-1.17.1-388.jar > paperclip.jar; echo "eula=true" > eula.txt; java -jar paperclip.jar --nogui'
```

The docker daemon is running on the same system as my testing client, I am connecting with the 1.17.1 vanilla client.
These are the results:
![image](https://user-images.githubusercontent.com/32834385/143503120-231bd9e1-eb59-4edd-820b-0a92a37799bd.png)
![image](https://user-images.githubusercontent.com/32834385/143503127-a5dc4868-df9a-4b4f-9fc9-95b9134ce6b7.png)
which are as expected.

**Comment by Proximyst** [comment] 2021-11-25 22:13
Do you run this after logging in WHILE op? Being opped while already online will result in this, which we can’t control.

**Comment by jpenilla** [comment] 2021-11-25 22:26
> Do you run this after logging in WHILE op? Being opped while already online will result in this, which we can’t control.

Being opped while logged in should work fine, the command tree should be rebuilt and sent again on being made op

**Comment by lynxplay** [comment] 2021-11-25 22:35
Besides that the `/version` command does not require you to be an operator and, at least in my tests, I did join the fresh server without adding myself as an operator right after the servers creation.

**Comment by josephjthomas** [comment] 2021-11-25 22:54
Same issue over here! After I updated from Java 16 to Java 17 all tab commands break. I had to revert to Java 16 for now

**Comment by mja00** [comment] 2021-11-26 02:22
Couldn't reproduce the issue on my test server which was running Paper build 388 and Java 17 packaged by CentOS [here](https://centos.pkgs.org/8-stream/centos-appstream-x86_64/java-17-openjdk-17.0.0.0.26-0.2.ea.el8.x86_64.rpm.html)

Even tried with the listed plugins and couldn't get it to break. 

| Paper Version | OS Version           | Java Version        | Result             |
|---------------|----------------------|---------------------|--------------------|
| 1.17.1-388    | [Centos 7 Docker Base](https://hub.docker.com/layers/centos/library/centos/centos7/images/sha256-b98bfc4a7094a98ed52d49f9558bb15a4cee9854f182d30085d459d4a55d2e03?context=explore) | OpenJDK 17.0.0.0.26 | Couldn't replicate |

**Comment by SirYwell** [comment] 2021-11-26 05:53
I was able to reproduce the issue with `-XX:ActiveProcessorCount=1`.

This is a [bug in the JDK](https://bugs.openjdk.java.net/browse/JDK-8274349) that will be fixed in the next release. Seems like tab completions are using unjoined tasks and therefore the result is never sent to the player if the JVM only got one CPU core assigned.

You can add the flag `-Djava.util.concurrent.ForkJoinPool.common.parallelism=1` to your start script as a workaround or just use more than one CPU core (which I would recommend).

**Comment by Proximyst** [comment] 2021-11-26 06:43
Closing, then. Thanks a lot for your finds, @SirYwell.

For reference, here are _some_ of the most active distributions if you do not fetch Java from your package manager:

  - https://adoptium.net/
  - https://aws.amazon.com/corretto/
  - https://www.azul.com/

Check your place of choice regularly till the aforementioned bug is fixed in an upcoming release 😃.

**Closed as completed by Proximyst** 2021-11-26 06:43 UTC
Labels: type: bug
