### ISSUE TITLE
EntityPickupItemEvent causing ghost items when changing the ItemStack of the item

### ISSUE THREAD

**Issue by TropicalShadow** [PaperSpigot/Paper#7346] opened 2022-01-15 06:21 UTC
### Expected behavior

When the player picks up the Item Entity it should give the ItemStack associated with it even if the ItemStack was changed during an event and it should go directly into the player's inventory with no gaps from top-left to bottom-right

### Observed/Actual behavior

When the player picks up an item it will either not show anything but still show the player picking up the Item, it removes the item on the floor and makes the sound, but leaves a void in the slot it should have gone into... or it will fill the inventory avoiding the slots which have been made "void".

When the player picks up an item checking the inventory for the ghost items it only shows the items that are visually showing in the inventory.

After re-logging, the items that left a "void" will re-appear as if nothing happened.

https://user-images.githubusercontent.com/52831503/149611135-a02b7877-d65e-4658-a650-dc8b44f6073b.mp4

### Steps/models to reproduce

add an event that replaces the ItemStack of an entity item on pickup, as shown below.
by editing the Item's ItemStack it will cause the issue above...

```kt
    @EventHandler
    fun onItemPickup(event: EntityPickupItemEvent){
        event.item.itemStack = ItemStack(Material.POTION)
        if(event.entity is Player){
            (event.entity as Player).inventory.forEach{
                if (it == null) return else // inventory returns Null ? not sure if this is just the empty gaps or the items that don't appear... appear as null
                println("${it.i18NDisplayName}")
            }
        }
    }
```

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/52831503/149611058-321fec6b-59c7-448b-a436-ab37e86fb47d.png)
Note: tested after manual server restarting... so it most likely isn't due to BileTools

### Paper version

```
[06:01:38 INFO]: This server is running Paper version git-Paper-152 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 78999b5)
You are running the latest version
```

### Other

Do note I have tested this issue with only non-stackable items.
This issue from what I have tested only occurs in the player's inventory `not hotbar`

**Comment by Owen1212055** [comment] 2022-01-15 15:23
This is a vanilla issue caused by the quirkiness of creative mode. 
This can be reproduced by spamming items just like you did but in vanilla.

![image](https://user-images.githubusercontent.com/23108066/149627161-512cca81-a9c0-4cbb-bcc5-580e3835e9e7.png)

Rejoining...
![image](https://user-images.githubusercontent.com/23108066/149627192-2d18e80e-2803-4ee3-9c11-e6f02de91fb6.png)

**Comment by Machine-Maker** [comment] 2022-01-22 07:49
Yes @TropicalShadow see if you can reproduce this issue in survival mode somehow. If it is just a creative mode thing, I'm not sure what the server can do about that. Lots of inventory things are different in creative mode.

**Comment by aurorasmiles** [comment] 2022-08-05 12:07
Creative mode inventories have been a general source of problems that are outside of the scope of Paper. Since this seems to be a creative only issue, ass MM already said, there is not too much we can do, and I'll close this issue for now.

**Closed as not planned by aurorasmiles** 2022-08-05 12:07 UTC
Labels: type: bug, resolution: awaiting response
