### ISSUE TITLE
Leasing Trader Llamas to Wandering Trader removes the Llamas

### ISSUE THREAD

**Issue by Pitrex111** [PaperSpigot/Paper#11173] opened 2024-07-26 22:26 UTC
### Expected behavior

When using setLeashHolder method on llama with Wandering Trader llama becomes successfully leashed.

### Observed/Actual behavior

Only wandering traders appears when llamas are leashed to him

### Steps/models to reproduce

If I use following lines:
```
Location origin = <logic for getting proper location>
WanderingTrader trader = (WanderingTrader) origin.getWorld().spawnEntity(origin, EntityType.WANDERING_TRADER);
Llama llama1 = (Llama) origin.getWorld().spawnEntity(origin, EntityType.TRADER_LLAMA);
Llama llama2 = (Llama) origin.getWorld().spawnEntity(origin, EntityType.TRADER_LLAMA);
```

Both llamas and wandering trader spawns, but when I add those 2 lines only wandering trader appears
```
llama1.setLeashHolder(trader);
llama2.setLeashHolder(trader);
```

### Plugin and Datapack List

[00:25:48 INFO]: Server Plugins (17):
[00:25:48 INFO]: Bukkit Plugins:
[00:25:48 INFO]:  - dynmap, ICraft2.0-Special, *JoinFullServer, LogBlock, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NoChatReports, *PermissionsEx, PexTabCompleter
[00:25:48 INFO]:  ProtocolLib, *SimplePrefix-Reloaded, Skoice, TreasureChestX, *VoidWorld, WorldEdit, WorldGuard

[00:26:00 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[00:26:00 INFO]: There are no more data packs available

### Paper version

[00:26:09 INFO]: Checking version, please wait...
[00:26:10 INFO]: This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-318 (MC: 1.20.2)

**Comment by Lulu13022002** [comment] 2024-07-27 10:52
Duplicate of https://github.com/PaperMC/Paper/issues/10937.

**Closed as not planned by Lulu13022002** 2024-07-27 10:52 UTC
Labels: type: bug, resolution: works as intended, version: 1.21
