### ISSUE TITLE
NBT data loss on item

### ISSUE THREAD

**Issue by BornToDoStuff** [PaperSpigot/Paper#9469] opened 2023-07-10 21:22 UTC
### Expected behavior

I have a datapack that allows for applying armor trims to items. When an armor trim is applied I expect the NBT data associated with the trim to remain on the item while moving between inventories, dropped on the ground, etc.

### Observed/Actual behavior

When armor trim is applied if a player moves the item between inventory slots too quickly the NBT data for the trim simply vanishes into the void.

### Steps/models to reproduce

**Steps I took to replicate:**
- booted fresh 1.20.1-69 server on local
- installed datapack to allow for tools to have armor trim applied (nothing else, no plugins, no config changes, etc)
- restarted server
- gave myself op, changed gamemode to creative, gave myself needed items for recipe
- apply template to tool (pickaxe primarily used for testing)
- quickly randomly move tool around inventory/rapidly click on it (if its slow enough it doesnt seem to happen)
- NBT data for trim is lost.

### Plugin and Datapack List

Server Plugins (0):
There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [file/dp-trimmable-tools-mc1.20-v1.0.4.zip (world)]

### Paper version

This server is running Paper version git-Paper-69 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6b325cd)
You are running the latest version

### Other

**Notes:**
- I was not able to replicate this on a vanilla local server, or singleplayer
- I also tested it in survival and experienced the same NBT data loss
- all tests were done with a vanilla client (resource packs only)
- other (vanilla) NBT data (for enchants, names, etc) is not lost

[2023-07-10-2.log](https://github.com/PaperMC/Paper/files/12008605/2023-07-10-2.log) (log is second file because it was restarted after adding datapack)
[dp-trimmable-tools-mc1.20-v1.0.4.zip](https://github.com/PaperMC/Paper/files/12008606/dp-trimmable-tools-mc1.20-v1.0.4.zip)

**Comment by BornToDoStuff** [comment] 2023-07-10 21:23
potentially related to #5845

**Comment by electronicboy** [comment] 2023-07-10 21:24
linked issue only related to creative mode

**Comment by Machine-Maker** [comment] 2023-07-10 22:08
Confirmed, and there should be a relatively easy fix for this specific issue.

**Comment by rayblon** [comment] 2023-11-17 14:17
I'm not sure if this adds to the issue much but some things seem to de-trim non-armor items more frequently. Going slow doesn't seem reliable either as sometimes waiting 10 seconds between actions can still  result in certain actions de-trimming an item stack.

some such instances:
- Right clicking a trimmed item stack like carved pumpkins to split the stack can detrim both stacks
- Middle clicking stackable trimmed items can de-trim both, or make your cursor pick up an untrimmed copy of the stack
- middle clicking unstackable. non-armor, trimmed items seems to reliably de-trim the copy you pick up
- putting any non trimmed items in one's hotbar or armor slots
- shift clicking a carved pumpkin item stack and consequently equipping one pumpkin will detrim both the worn and displaced stack



Interestingly, hoppers and droppers don't seem to cause any issues with de-trimming, and dropping the item or throwing it also seems reliably safe. Shift clicking in and out of inventories is also reliable, including shift clicking into hotbars. It appears to be specific to player interactions

**Comment by H1sho** [comment] 2024-03-30 14:40
Bug is still a thing. When we can expect it to be resolved? Also: https://hub.spigotmc.org/stash/users/derfrzocker/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaArmor.java?at=fixes%2Fskull-meta-note-block-sound

In spigot it is caused by slim item type list. Idk if same problem is here.

**Comment by electronicboy** [comment] 2024-03-30 14:58
There is a PR which is linked but it needs rebasing and testing

**Comment by Machine-Maker** [comment] 2024-04-28 00:38
Fixed in 4ad6022ee3ba2219f8c56ad2cb92eba2fd3c7d34

**Closed as completed by Machine-Maker** 2024-04-28 00:38 UTC
Labels: type: bug, status: accepted
