### ISSUE TITLE
Multiple InventoryClickEvent called instead of InventoryDragEvent in CREATIVE

### ISSUE THREAD

**Issue by seercle** [PaperSpigot/Paper#10384] opened 2024-04-03 07:31 UTC
### Expected behavior

I expect ```InventoryDragEvent``` being called, as it does with other game modes

### Observed/Actual behavior

When in creative, instead of calling ```InventoryDragEvent``` at the end of the drag as usual, one ```InventoryClickEvent``` is fired per slot dragged into

### Steps/models to reproduce

```Java
public class DragIssuePlugin extends JavaPlugin implements Listener {

  @Override
  public void onEnable() {
    getServer().getPluginManager().registerEvents(this, this);
  }

  @EventHandler
  public void onInventoryClick(InventoryClickEvent e){
    e.getWhoClicked().sendMessage("CLICK");
  }

  @EventHandler
  public void onInventoryDrag(InventoryDragEvent e){
    e.getWhoClicked().sendMessage("DRAG");
  }
}
```

### Plugin and Datapack List

None except the one mentioned above

### Paper version

```
This server is running Paper version git-Paper-464 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: e709245)
You are running the latest version
Previous version: git-Paper-"00fd87a" (MC: 1.20.4)
```

### Other

This issue is likely related to [#10377](https://github.com/PaperMC/Paper/issues/10377), as both are issues with InventoryClickEvent in creative

**Comment by electronicboy** [comment] 2024-04-03 07:34
This is 100% down to how the client behaves in creative mode, the API is likely working 100% as intended from what the client is sending it

**Comment by Machine-Maker** [comment] 2024-04-08 00:56
I'm closing this as WAI. To be clear, this only happens in the **creative inventory screen** while in creative mode, not in other regular inventories. The client does indeed send an individual `ServerboundSetCreativeModeSlotPacket` for each slot to set the contents based on the client drag. The event that is fired for each of those packets is an `InventoryCreativeEvent` (which is a subclass of `InventoryClickEvent`).

**Closed as not planned by Machine-Maker** 2024-04-08 00:56 UTC
Labels: type: bug, resolution: works as intended
