### ISSUE TITLE
World#createExplosion does not damage or deal knockback to the explosion cause

### ISSUE THREAD

**Issue by sh-dima** [PaperSpigot/Paper#11167] opened 2024-07-25 21:46 UTC
### Expected behavior

Explosions created using [World#createExplosion](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#createExplosion(double,double,double,float,boolean,boolean,org.bukkit.entity.Entity)) should deal damage and knockback to all entities within the range of the explosion, including the entity specified as the explosion cause.

### Observed/Actual behavior

Explosions created using [World#createExplosion](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#createExplosion(double,double,double,float,boolean,boolean,org.bukkit.entity.Entity)) deal the proper damage and knockback to all entities other than the entity specified as the `source` argument.

### Steps/models to reproduce

I encountered this issue while developing [my plugin](https://github.com/Slqmy/bad-piggies-plugin). The instant TNT feature does not work correctly because of this, and functions as described above.

Steps to reproduce:
- Create a new server with the latest version of Paper.
- Install [my plugin](https://github.com/Slqmy/bad-piggies-plugin) (or any other plugin that uses the [World#createExplosion](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#createExplosion(double,double,double,float,boolean,boolean,org.bukkit.entity.Entity)) method).
- Do whatever action triggers the [World#createExplosion](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#createExplosion(double,double,double,float,boolean,boolean,org.bukkit.entity.Entity)) method.

For example, here is the code used in [my plugin](https://github.com/Slqmy/bad-piggies-plugin):
```java
    private void detonateInstantTnt(@NotNull Block instantTnt, @Nullable Entity cause) {
        instantTnt.setType(Material.AIR);

        float power = (float) plugin.getConfig().getDouble("features.instant-tnt.explosion.power");
        boolean shouldSetFire = plugin.getConfig().getBoolean("features.instant-tnt.explosion.sets-fire");
        boolean shouldBreakBlocks = plugin.getConfig().getBoolean("features.instant-tnt.explosion.breaks-blocks");

        instantTnt.getWorld().createExplosion(BlockUtil.getBlockCenterLocation(instantTnt), power, shouldSetFire, shouldBreakBlocks, cause);

        removeInstantTnt(instantTnt);
    }
```

My `config.yml`:
```yaml
features:
  instant-tnt:
    enabled: true
    # The unit for this variable is meters per second.
    minimum-collision-detonation-speed: 0.75
    explosion:
      power: 2.0
      breaks-blocks: false
      sets-fire: false
      spread-radius-blocks: 8.0
      blocks-per-tick-delay: 0.0
```

### Plugin and Datapack List

Output after doing `/plugins`:
```
Server Plugins (1):
Paper Plugins:
 - BadPiggiesPlugin
```

Output after doing `/datapack list`:
```
There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
There are no more data packs available
```

### Paper version

```
Checking version, please wait...
This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)\nYou are running the latest version
```

**Comment by lynxplay** [comment] 2024-07-26 13:23
Yea, this is simply vanilla behaviour.
The API could expose a way to pass in a damage source, that way the "source" entity could remain null but the damage source may have an indirect entity, but changing vanilla behaviour here is a no-go.

Closing this as works as intended.

**Closed as not planned by lynxplay** 2024-07-26 13:23 UTC
Labels: type: bug, resolution: works as intended, version: 1.21
