### ISSUE TITLE
Rasbrerry Pi 4  WARN this.cpuVendor

### ISSUE THREAD

**Issue by daretmavi** [PaperSpigot/Paper#10264] opened 2024-02-19 12:36 UTC
### Stack trace

```
Feb 19 13:04:27 raspberrypi java[4910]: 2024-02-19 13:04:27,888 ServerMain WARN Advanced terminal features are not available in this environment
Feb 19 13:04:31 raspberrypi java[4910]: [13:04:29 WARN]: Failed to get system info for Microarchitecture
Feb 19 13:04:31 raspberrypi java[4910]: java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
Feb 19 13:04:31 raspberrypi java[4910]:         at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:6.4.5]
Feb 19 13:04:31 raspberrypi java[4910]:         at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
Feb 19 13:04:31 raspberrypi java[4910]:         at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:6.4.5]
Feb 19 13:04:31 raspberrypi java[4910]:         at net.minecraft.SystemReport.setDetail(SystemReport.java:62) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at net.minecraft.SystemReport.putProcessor(SystemReport.java:153) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at net.minecraft.SystemReport.lambda$putHardware$4(SystemReport.java:72) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at net.minecraft.SystemReport.ignoreErrors(SystemReport.java:85) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at net.minecraft.SystemReport.lambda$putHardware$4(SystemReport.java:72) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at net.minecraft.SystemReport.lambda$new$2(SystemReport.java:47) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at net.minecraft.SystemReport.ignoreErrors(SystemReport.java:85) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at net.minecraft.SystemReport.lambda$new$2(SystemReport.java:47) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at net.minecraft.CrashReport.<init>(CrashReport.java:34) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at net.minecraft.CrashReport.preload(CrashReport.java:257) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at net.minecraft.server.Main.main(Main.java:126) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[paper-1.20.4.jar:git-Paper-430]
Feb 19 13:04:31 raspberrypi java[4910]:         at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
Feb 19 13:04:31 raspberrypi java[4910]:         at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

### Plugin and Datapack List

Server Plugins (26):
Paper Plugins:
 - PaperTweaks
Bukkit Plugins:
 - BetterEconomy, Bookshelf, BooksWithoutBorders, BurgerHud, CustomCompass, EzChestShop, FastChunkPregenerator, FastLogin, Graves, GriefPrevention
 InteractionVisualizer, InvisibleItemFrames, LittleComposter, Lootin, LuckPerms, NotTooExpensive, ProtocolLib, SkinsRestorer, squaremap, TreeFeller
 UserLogin, Vault, ViewDistanceTweaks, voicechat, WanderingTrades

>datapack list 
There are 8 data pack(s) enabled: [vanilla (built-in)], [file/BacktoBlocks.zip (world)], [file/CraftableBundlesRabbit.zip (world)], [file/CraftableNametag.zip (world)], [file/LightBlockEditor.zip (world)], [file/armor_statues_v2.10.2.zip (world)], [file/bukkit (world)], [file/double shulker shells v1.3.6 (MC 1.20-1.20.4).zip (world)]There are no more data packs available

### Actions to reproduce (if known)

Server started on Raspberry Pi
(Linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux)

### Paper version

paper-1.20.4-430

### Other

It's just warning and server works.
(paper-1.18.2-388 works on the same HW without warnings.)

Seems to be the similar issue like it was in #9785

**Comment by electronicboy** [comment] 2024-02-19 12:38
Duplicate of #9785 
Will be fixed once oshi is updated, I don't think that there is much care from us to update it as it's just a generally meaningless warning on mostly unsupported platforms

**Closed as not planned by electronicboy** 2024-02-19 12:38 UTC
Labels: resolution: duplicate, version: 1.20.4
