### ISSUE TITLE
Place a hopper that is instantly charged still generate block update

### ISSUE THREAD

**Issue by s-yh-china** [PaperSpigot/Paper#9205] opened 2023-05-12 14:47 UTC
### Expected behavior

not generate block update like vanilla
![237983762-c1b36fd6-9976-40b2-a2cc-50dd52803176](https://github.com/PaperMC/Paper/assets/58360096/c4ec37c2-b5b7-4bb0-80f1-a75d3469304e)

### Observed/Actual behavior

Place a hopper that is instantly charged still generate block update.
![237983583-7a5426c7-1b87-4bb9-9d9f-ec91ed6b8e47](https://github.com/PaperMC/Paper/assets/58360096/520d3b28-76e2-4f25-abf7-2d447b802e04)

### Steps/models to reproduce

place hopper on a redstone block

### Plugin and Datapack List

None

### Paper version

commit 9846d0d89e7598fc28a8c8534d80d4c5dc42021c

**Comment by GLDYM** [comment] 2023-05-12 14:56
Expected behavior & Observed/Actual behavior is reversed (
In vanilla it does't generate block update, but in Paper it does.

**Comment by Machine-Maker** [comment] 2023-05-12 16:49
I'm not quite understanding the issue. Is the water in those images supposed to represent something? What kind of update are we talking about? placing blocks do cause block updates in both vanilla and paper afaik.

**Comment by s-yh-china** [comment] 2023-05-12 18:32
> I'm not quite understanding the issue. Is the water in those images supposed to represent something? What kind of update are we talking about? placing blocks do cause block updates in both vanilla and paper afaik.

In vanilla, if I place a hopper near a redstone block, then this hopper will not generate block update.

**Comment by Leguan16** [comment] 2023-05-13 10:25
> I'm not quite understanding the issue. Is the water in those images supposed to represent something? What kind of update are we talking about? placing blocks do cause block updates in both vanilla and paper afaik.

I think they are talking about the water, yes. 
Look at this (which represents the vanilla server I suppose)
![image](https://github.com/PaperMC/Paper/assets/59799222/26e7fe43-2ff6-4581-99f8-5345fb98de49)
An this is how its on Paper:
![image](https://github.com/PaperMC/Paper/assets/59799222/ffef5de2-294e-4a5e-8475-4515125b69dc)

**Comment by imDaniX** [comment] 2023-05-25 12:25
The vanilla behavior looks like a bug to me more, than the fact it doesn't persist on Paper. Should this really be "fixed"?

**Comment by Owen1212055** [comment] 2023-05-28 17:29
As per Paper's policy, in general, this is more of a fix for broken Vanilla behavior. So, closing.

**Closed as completed by Owen1212055** 2023-05-28 17:29 UTC
Labels: type: bug

**Comment by Lulu13022002** [comment] 2025-04-25 14:40
Fixed in 1.21.5
