### ISSUE TITLE
When I type something or paste something, not all characters get accepted.

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [PaperSpigot/Paper#11019] opened 2024-07-05 06:52 UTC
### Expected behavior

When I type something or paste something, all characters get accepted.

### Observed/Actual behavior

Input will randomly not be accepted - this is anything from me typing to me hitting the enter key to hitting delete.

### Steps/models to reproduce

I'm not sure what is applicable, so here is all possibly relevant information:

**Java Version**
```
openjdk version "22.0.1" 2024-04-16
OpenJDK Runtime Environment (build 22.0.1+8-16)
OpenJDK 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)
```

**OS Information**
```
OS Name: Microsoft Windows 10 Home
Version: 10.0.19045 Build 19045
```

### Plugin and Datapack List

**Plugins**
```
> pl
[20:42:47 INFO]: Server Plugins (0):
```

**Datapacks**
```
> datapack list
[20:43:28 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[20:43:28 INFO]: There are no more data packs available
```

### Paper version

NOTE: I know this isn't the latest version, but from testing I have found that the issue does NOT happen with version paper-1.20-17, but DOES happen in version paper-1.20.1-196. If needed, I can try and find the exact build where the issue starts (I only tested with the latest builds of each version until I found the latest version + build that worked).

```
> version
[20:43:53 INFO]: Checking version, please wait...
[20:43:54 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-17 (MC: 1.20)
```

### Other

Here is an example of what happens:
I have the message `This is a weird bug that happens randomly` copied, and I am pasting it onto the command line. The output is shown below for multiple pastes:
![image](https://github.com/PaperMC/Paper/assets/70504198/9e34b30b-3152-439e-b507-638062fcf519)
![image](https://github.com/PaperMC/Paper/assets/70504198/77fa15b9-0062-4570-a806-4aa38e826cf4)
![image](https://github.com/PaperMC/Paper/assets/70504198/5715b2e6-3e37-45fa-ae8c-a6bebc49bc86)
![image](https://github.com/PaperMC/Paper/assets/70504198/ec1baa2c-2c83-4228-9339-c88dc3c63f05)
![image](https://github.com/PaperMC/Paper/assets/70504198/bf3d40f6-26bc-4ee3-baea-57c393c50f91)

I have found that if I type super slow and one character at a time, the characters will get accepted most of the time.

**Comment by electronicboy** [comment] 2024-07-05 07:16
duplicate of #10405

**Closed as not planned by electronicboy** 2024-07-05 07:16 UTC
Labels: type: bug, version: 1.20.1
