### ISSUE TITLE
EntityShootBowEvent consuming arrows when cancelled

### ISSUE THREAD

**Issue by Jiangyuluo** [PaperSpigot/Paper#11222] opened 2024-08-08 08:52 UTC
### Expected behavior

when I cancel the EntityShootBowEvent, the arrow will not be consumed

### Observed/Actual behavior

After canceling the EntityShootBowEvent, the arrow was not fired, but it was still consumed

### Steps/models to reproduce

    @EventHandler
    public void onEntityShootBow(EntityShootBowEvent event) {
        event.setCancelled(true);
    }
entering the game, take out the bow. The arrow was not shot, but it was consumed

### Plugin and Datapack List

only test plugins available and no datapack

### Paper version

https://api.papermc.io/v2/projects/paper/versions/1.21/builds/127/downloads/paper-1.21-127.jar

**Comment by lynxplay** [comment] 2024-08-08 08:53
Duplicate of https://github.com/PaperMC/Paper/issues/10665

**Closed as not planned by lynxplay** 2024-08-08 08:53 UTC
Labels: type: bug, resolution: duplicate
