### ISSUE TITLE
Rails do not update and get locked in the on/off state across chunk boundaries. 

### ISSUE THREAD

**Issue by OhTheNoises** [PaperSpigot/Paper#9227] opened 2023-05-25 17:24 UTC
### Expected behavior

A line of rails should update together when powered on even across a chunk boundary. 

### Observed/Actual behavior

The rails in question seem to update randomly and in a unpredictable order sometimes locking up and not updating at all, the error changes sides depending on which chunk I stand in. When I stand in one chunk the half of the rails that are in the chunk I'm standing in update properly, when I stand in the other chunk the other rails work properly and the first chunk's rails freeze.[](url)
![2023-05-25_13 16 05](https://github.com/PaperMC/Paper/assets/49348348/fe37df81-8358-491f-9b7a-25651fdada8f)
![2023-05-25_13 16 04](https://github.com/PaperMC/Paper/assets/49348348/fbaf6537-9241-4b60-8943-421980594d63)

### Steps/models to reproduce

Built a gnembon multi-itemsorter across a chunk boundary

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/49348348/847a3068-39ff-4ae3-aabc-9e368ad3be92)

### Paper version

![image](https://github.com/PaperMC/Paper/assets/49348348/edc5e650-d482-4cc5-b2b6-b29e148e3e74)

**Comment by Nacioszeczek** [comment] 2023-08-15 00:52
I've been running the sorter for a while with the rails on a chunk boundary and couldn't reproduce this. Please make sure the issue still occurs on the latest version of Paper, and if it does feel free to reply to this issue with the world and we'll reopen it. For now, closing.

**Closed as not planned by Nacioszeczek** 2023-08-15 00:52 UTC
Labels: type: bug, resolution: cannot reproduce
