### ISSUE TITLE
Add another overload for Player#sendBlockDamage with entityId

### ISSUE THREAD

**Issue by u9g** [PaperSpigot/Paper#7319] opened 2022-01-11 20:03 UTC
### Is your feature request related to a problem?

You can only tick two different blocks at once if they have different entityIds.

### Describe the solution you'd like.

just add another overload that allows giving another entityid or some abstraction over that.

### Describe alternatives you've considered.

going to userdev.

**Comment by Owen1212055** [comment] 2022-01-11 20:17
Will be Resolved by: https://github.com/PaperMC/Paper/pull/5840
So Dupe of: https://github.com/PaperMC/Paper/issues/5246

**Comment by lynxplay** [comment] 2022-01-11 22:39
Indeed, thanks for the scouting <3.
Closing this as a duplicate of #5246

**Closed as completed by lynxplay** 2022-01-11 22:39 UTC
Labels: resolution: duplicate, type: feature
