### ISSUE TITLE
Hoglins Target Is Always Null

### ISSUE THREAD

**Issue by KillerCreeper112** [PaperSpigot/Paper#8963] opened 2023-03-12 18:12 UTC
### Expected behavior

When using the .getTarget() method on a hoglin, the hoglin's target should be returned.

### Observed/Actual behavior

It always returns null, even if the hoglin is targetting an entity.

### Steps/models to reproduce

@Override
    public void onEnable() {
        new BukkitRunnable(){
            @Override
            public void run() {
                for(Hoglin h : Bukkit.getWorld("world").getEntitiesByClass(Hoglin.class)){
                    Bukkit.broadcast(Component.text(h.getTarget() + ""));
                }
         }
}

Spawn in a hoglin while in survival and have it target you.

### Plugin and Datapack List

Just the custom written one that has the code written above, in the steps to reproduce.

### Paper version

This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version
Previous version: git-Paper-447 (MC: 1.19.3)

**Comment by electronicboy** [comment] 2023-03-12 18:14
This is because Hoglins are newer entities which use the brain/memory system, rather than the old legacy system which actually set the target to a field

I don't think that we can do much about the target without going down an entire rabbit hole

**Comment by Warriorrrr** [comment] 2023-03-12 18:15
Probably related to #6862

**Comment by Machine-Maker** [comment] 2023-03-12 19:42
Duplicate of https://github.com/PaperMC/Paper/issues/6862

The alternative is to use the memory methods (for which there is an [open PR](https://github.com/PaperMC/Paper/pull/5605) adding the missing ones).

**Closed as not planned by Machine-Maker** 2023-03-12 19:42 UTC
Labels: type: bug, resolution: duplicate

**Comment by KillerCreeper112** [comment] 2023-03-12 20:11
So will Paper support the new system? 2 years seems like a while for it to not be supported.

**Comment by electronicboy** [comment] 2023-03-12 20:13
it already supports the system as spigot has API for it, just spigots API is missing access to a lot of them at the moment; As you can see, there is already a PR to add those, just needs a bit more work from what I recall
