### ISSUE TITLE
Block Physics Event is completely broken since minecraft 1.19

### ISSUE THREAD

**Issue by bergerkiller** [PaperSpigot/Paper#8368] opened 2022-09-18 16:42 UTC
### Expected behavior

Block physics event is fired in all situations where blocks will break. Cancelling the event will prevent blocks breaking. Or an alternative event to cancel this.

### Observed/Actual behavior

No event fired. Blocks break, plugins cant cancel it. It's no longer possible to have blocks suspended in the air.

### Steps/models to reproduce

Try to set any block in the World that requires a block to attach to. These are:
- Signs
- Rails
- Portals
- Plants

Now try to prevent those blocks breaking when their connecting block breaks. It's not possible. BlockPhysicsEvent doesn't fire at all when these blocks get 'updated' internally and discover that they are no longer supported. Floating rails/signs, portals in free air or other kind of decorative effects are no longer possible.

### Plugin and Datapack List

TrainCarts and BKCommonLib are most affected. MyWorlds is affected because of portals breaking when updated.

In particular what broke are Traincarts' upside-down rails. I've managed to make it work a little bit by hacks such as updating block data without physics events firing. But placing any block nearby breaks every single block like a cactus.

https://user-images.githubusercontent.com/957601/190918431-7df74a90-005f-447c-a889-059a699415cb.mp4

### Paper version

This server is running Paper version git-Paper-137 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e8c2c3b)

### Other

Since Minecraft 1.19. Probably a code change and the physics event, or an alternative event, was never added where it should be. I'm OK with an alternative event like "BlockSupportBrokenEvent" or something.

**Comment by Owen1212055** [comment] 2022-09-18 16:43
Are you able to test if https://github.com/PaperMC/Paper/pull/8264
resolves this?

Most likely related to https://github.com/PaperMC/Paper/issues/8191

**Comment by bergerkiller** [comment] 2022-09-18 16:45
Do you have a jar I can test with?

**Comment by bergerkiller** [comment] 2022-09-18 17:01
That PR indeed fixes the problem for me :heart:

**Comment by bergerkiller** [comment] 2022-09-18 17:02
However, portal blocks do still break. Its less of a concern for me though

**Comment by Lulu13022002** [comment] 2022-09-18 18:26
Oh i can't reproduce with the PR for nether portal or you mean when you lit the portal ?

![image](https://user-images.githubusercontent.com/41980282/190922613-6bcdc7ad-ac0a-41f6-b73d-23925a75267f.png)

**Comment by bergerkiller** [comment] 2022-09-18 18:40
MyWorlds has a tool item that places down nether portals in free air. When I use it to place portal blocks down it works. But when I break one portal block, the entire portal breaks.

<https://github.com/bergerhealer/MyWorlds/blob/master/src/main/java/com/bergerkiller/bukkit/mw/MWListener.java#L418>

overrideportalphysics is active (I checked)

Let me check whether maybe that BlockData read from the event is to blame. Its possible that isnt of a portal block at all.

**Comment by bergerkiller** [comment] 2022-09-18 18:49
Ah yep, works fine but it often triggers with blockdata air as the 'cause'. I guess it makes sense. I remember seeing somewhere that the block data that causes the change can differ from the block data of the portal block itself.

Dont want to change the code though. Reading the block data of a block inside a physics event is horrible for performance. Unless paper adds a separate field for the block data of the block undergoing physics, I'll just leave it broken.

**Comment by lynxplay** [comment] 2022-09-20 17:11
I'll close this issue as a duplicate of https://github.com/PaperMC/Paper/issues/8191. While said issue is sadly rather small minded (as it only points these issues out for rails), there isn't much of a point in keeping two issues open for the same underlying issue (the fact that `CollectingNeighborUpdater` has taken over a few parts of where the physics event was usually called).

Anyone that is awaiting a fix for this issue may start watching #8191 or presumably lulu's PR.

**Closed as not planned by lynxplay** 2022-09-20 17:11 UTC
Labels: type: bug, resolution: duplicate, version: 1.19
