### ISSUE TITLE
1.21.3 Failed to teleport entity CraftPlayer

### ISSUE THREAD

**Issue by RanMinecraft** [PaperSpigot/Paper#11586] opened 2024-11-05 11:00 UTC
This server is running Paper version 1.21.3-13-master@42a1901 (2024-11-05T09:59:36Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-2331-e86a1b6 (MC: 1.21.3)

player.teleportAsync(location);

```
        at net.minecraft.world.entity.ai.attributes.AttributeInstance.addModifier(AttributeInstance.java:80) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.world.entity.ai.attributes.AttributeInstance.addPermanentModifier(AttributeInstance.java:106) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.world.entity.ai.attributes.AttributeInstance.addPermanentModifiers(AttributeInstance.java:112) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.world.entity.ai.attributes.AttributeMap.lambda$assignPermanentModifiers$7(AttributeMap.java:120) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$1.forEach(Object2ObjectOpenHashMap.java:1188) ~[fastutil-8.5.12.jar:?]
        at net.minecraft.world.entity.ai.attributes.AttributeMap.assignPermanentModifiers(AttributeMap.java:117) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.level.ServerPlayer.restoreFrom(ServerPlayer.java:2289) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:787) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1520) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at org.bukkit.craftbukkit.entity.CraftEntity.lambda$teleportAsync$1(CraftEntity.java:1074) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1576) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1553) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1546) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:117) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1503) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1343) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-13-42a1901]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Comment by electronicboy** [comment] 2024-11-05 11:02
You're missing the actual error, but, this is likely a duplicate of #11576

**Closed as not planned by electronicboy** 2024-11-05 11:02 UTC
Labels: version: 1.21.3
