### ISSUE TITLE
Server crash - Exception generating new chunk (ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by SnickoDeadMC** [PaperSpigot/Paper#7551] opened 2022-03-06 01:41 UTC
### Stack trace

https://pastebin.com/GtzBRUc5

### Plugin and Datapack List

Plugins: { FarmControl v1.1.8 com.froobworld.farmcontrol.FarmControl [froobynooby], PlaceholderAPI v2.11.0 me.clip.placeholderapi.PlaceholderAPIPlugin [HelpChat], zPermissions v1.5-SNAPSHOT org.tyrannyofheaven.bukkit.zPermissions.ZPermissionsPlugin [ZerothAngel], ShulkerPacks v1.5.16 me.darkolythe.shulkerpacks.ShulkerPacks [], spark v1.6.4 me.lucko.spark.bukkit.BukkitSparkPlugin [Luck], HolographicDisplays v3.0.0-SNAPSHOT-b204 me.filoghost.holographicdisplays.plugin.HolographicDisplays [filoghost], Votifier v2.7.3 com.vexsoftware.votifier.NuVotifierBukkit [Ichbinjoe, blakeman8192, Kramer, tuxed], ezBroadcast v1.2* me.qintinator.ezbroadcast.Main [], Insights v6.11.0 dev.frankheijden.insights.Insights [FrankHeijden], ImageMaps v1.0.6 net.craftcitizen.imagemaps.ImageMaps [SydMontague], Minepacks v2.4.5.1-Release at.pcgamingfreaks.Minepacks.Bukkit.MinepacksBadRabbit [GeorgH93], UltimateTrash v1.0.5 br.net.fabiozumbi12.UTrash.UTrash [], Not-Too-Expensive v1.1 me.mr_redstone5230.nottooexpensive.NotTooExpensive [Mr_redstone5230, Jamezrin], VillagerTradeLimiter v1.4.2 com.pretzel.dev.villagertradelimiter.VillagerTradeLimiter [PretzelJohn], EpicGuard v7.1.2 me.xneox.epicguard.paper.EpicGuardPaper [neox], ViaVersion v4.2.1 com.viaversion.viaversion.ViaVersionPlugin [_MylesC, creeper123123321, Gerrygames, kennytv, Matsv], Vault v1.7.3-b131 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], ViaBackwards v4.1.1 com.viaversion.viabackwards.BukkitPlugin [Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1], ViaRewind v2.0.2 de.gerrygames.viarewind.BukkitPlugin [Gerrygames], WorldEdit v7.2.8+6008-1246d61 com.sk89q.worldedit.bukkit.WorldEditPlugin [], ProtocolLib v4.8.0 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], ServerListMotdSpigot v1.2.9 eu.kennytv.serverlistmotd.spigot.ServerListMotdSpigotBase [KennyTV, Bradydawg], VotingPlugin v6.7.1 com.bencodez.votingplugin.VotingPluginMain [BenCodez], AsyncWorldEdit v3.9.4 org.primesoft.asyncworldedit.AsyncWorldEditBukkit [SBPrime], HoloExtension v0.0.4.4 Alpha eu.virtusdevelops.holoextension.HoloExtension [NeutralPlasma], WorldGuard v7.0.6+1cff55f com.sk89q.worldguard.bukkit.WorldGuardPlugin [], mcMMO v2.1.209 com.gmail.nossr50.mcMMO [nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking, electronicboy, kashike], NexEngine v2.1.1 build-26/02/2022 su.nexmedia.engine.NexEngine [NEX-Media], WorldGuardEvents v1.15.1 net.raidstone.wgevents.WorldGuardEvents [Weby], EnjinMinecraftPlugin v3.5.7 com.enjin.bukkit.EnjinMinecraftPlugin [www.Enjin.com], CMILib v1.1.2.0 net.Zrips.CMILib.CMILib [Zrips], Spartan vBuild 450 me.vagdedes.spartan.Register [Evangelos Dedes @Vagdedes], ExcellentCrates v4.0.3.6 su.nightexpress.excellentcrates.ExcellentCrates [NightExpress], DiscordSRV v1.24.1-SNAPSHOT github.scarsz.discordsrv.DiscordSRV [Scarsz, Androkai, Vankka], SelectionVisualizer v3.1.0.0 com.Zrips.sv.Sv [Zrips], AdvancedEnchantments v8.8.19 net.advancedplugins.ae.Core [AdvancedPlugins], DeadMC v1 com.deadmc.DeadAPImaven.DeadMC [], LibsDisguises v10.0.27-SNAPSHOT me.libraryaddict.disguise.LibsDisguises [libraryaddict, Byteflux, Navid K.], TAB v3.1.0 me.neznamy.tab.platforms.bukkit.Main [NEZNAMY],}

### Paper version

This server is running Paper version git-Paper-228 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 6564f70)

### Other

I have no idea why a chunk is trying to get located at Location: 134217726,134217726 (coords:
2147483616,2147483616 to 2147483631,2147483631)
But I think because it's almost as big as the max number it is causing a negative wraparound for the coords (and out of bounds exception.

It crashes randomly sometimes 3 times a day. I notice it usually contains the NetherFossilFeature structure trying to be generated in the stack.

**Comment by SnickoDeadMC** [comment] 2022-03-09 08:55
Looks the same as https://github.com/PaperMC/Paper/issues/7006

**Comment by SnickoDeadMC** [comment] 2022-03-11 00:15
~~Deleting the nether world seemed to fix it. Maybe a corrupt chunk? Figured that out as all the crashes related to NetherFossilFeature.~~

edit: still happening a day later

**Comment by SnickoDeadMC** [comment] 2022-03-20 08:54
May be related? I got a bunch of these before the server crashed.

`[03:47:54 ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.ReportedException: Exception generating new chunk
        at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$36(ChunkMap.java:1272) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:1251) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1264) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:828) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:2725) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.MinecraftServer.executeMidTickTasks(MinecraftServer.java:2748) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:920) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:682) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-260]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[03:47:54 INFO]: [STDOUT] [net.minecraft.CrashReport] Negative index in crash report handler (0/12)`

**Comment by electronicboy** [comment] 2022-03-20 08:56
Duplicate of #7006 as you identified already

**Closed as completed by electronicboy** 2022-03-20 08:56 UTC
