### ISSUE TITLE
Sapling Growth triggers piston buds

### ISSUE THREAD

**Issue by niklaslorenz** [PaperSpigot/Paper#7445] opened 2022-02-05 14:51 UTC
### Expected behavior

When a sapling advances in it's growth state (naturally or by using bonemeal), it triggers observer blocks, but does not update nearby pistons unless it actually grows into a tree and the sapling is replaced with a log.

### Observed/Actual behavior

On a Paper-Server a sapling does update nearby pistons when growing, even if it does not become a tree.

### Steps/models to reproduce

Just build the pictured structure and use bonemeal on the sapling. The piston is a sticky piston.
![Sapling_Bud_Bug](https://user-images.githubusercontent.com/50243091/152646621-2023ec5a-822e-4e45-b1ca-34b244c525f5.png)

### Plugin and Datapack List

[15:41:32 INFO]: Plugins (0):

### Paper version

[15:41:22 INFO]: Checking version, please wait...
[15:41:22 INFO]: This server is running Paper version git-Paper-186 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 6df4641)
You are running the latest version

**Comment by Machine-Maker** [comment] 2022-02-05 16:02
Duplicate of #6458 and fixed by #6464

**Closed as completed by Machine-Maker** 2022-02-05 16:02 UTC
Labels: type: bug, resolution: duplicate
