### ISSUE TITLE
Multilingualization of logs

### ISSUE THREAD

**Issue by creeper-0910** [PaperSpigot/Paper#9221] opened 2023-05-22 07:59 UTC
### Is your feature request related to a problem?

Hello, I have a question.
Is it possible to make the Paper server's death log and achievement messages multilingual?
We are using DiscordSRV, but it seems to be taking information from the logs and some of it is in English, so we would like to add a Japanese translation.

### Describe the solution you'd like.

Multilingualization of logs

### Describe alternatives you've considered.

I tried to apply the patch, but it seems that recent versions are no longer translatable.

**Comment by JMBoy01** [comment] 2023-05-22 08:47
Hello, I'm an enginering (in computer science) student from Belgium and I would like to try solve this issue. I have some decent knowledge of java and a little bit of experience with using papermc to write some plugins myself. I think Log4j is used but i couldn't find a build in way to chose a language for the log files. I will try and see if I can find another method.

**Comment by molor** [comment] 2023-05-22 09:24
> Log4j is used

No.
Related: https://github.com/PaperMC/Paper/issues/3257

**Comment by NoahvdAa** [comment] 2023-05-22 11:53
Closing this as a duplicate of #3527. 

As mentioned in the linked issue, the server jar only contains the `en_US` locale. This means we'll either need a reliable way to find and bundle all the language files (which are only in the client jar afaik), or we should let the user supply the language file and set the path to it via a config option or env var.

**Closed as not planned by NoahvdAa** 2023-05-22 11:53 UTC
Labels: resolution: duplicate, type: feature

**Comment by molor** [comment] 2023-05-22 12:39
(^ #3257, not #3527 XD)
