### ISSUE TITLE
Multiple players joining at once bypasses player limit

### ISSUE THREAD

**Issue by LaserSlime** [PaperSpigot/Paper#11713] opened 2024-12-06 18:19 UTC
### Expected behavior

The `max-players` option should never allow a player count above that limit, unless the last player(s) are excluded from it by being an op.

### Observed/Actual behavior

When multiple players join at the same time, they can slip past the `max-players` limit in server.properties despite not being allowed to.

### Steps/models to reproduce

1. Set up a fresh server and set "max-players" in server.properties to 2. (Note: In my testing I also set "offline-mode" to false since I don't have 3 accounts)
2. Boot up 3 seperate accounts.
3. Join with one of them
4. Now you have to quickly join with the other 2 accounts. To best reproduce this I recommend to use a tool like [clumsy](https://jagt.github.io/clumsy/download.html) and set your ping to 100ms. Alternatively you can try to join with all 3 accounts at once to increase the chance of it happening. Server side lag may also increase the chance of it happening.
5. Now there are 3 players on a server with a player limit of 2

### Plugin and Datapack List

No plugins or datapacks

### Paper version

This server is running Paper version 1.21.3-81-master@da71382 (2024-12-03T14:58:13Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version

### Other

This affects Spigot (see here: https://hub.spigotmc.org/jira/browse/SPIGOT-7864) but it does not affect vanilla servers.

**Comment by MiniDigger** [comment] 2024-12-06 18:50
duplicate of #10668

**Closed as not planned by MiniDigger** 2024-12-06 18:50 UTC
Labels: resolution: duplicate, version: 1.21.3
