### ISSUE TITLE
UUID's no longer autofill with certain vanilla commands following Paper 1.18.1 Patch #93

### ISSUE THREAD

**Issue by Rekn0wn** [PaperSpigot/Paper#7194] opened 2021-12-26 00:47 UTC
### Expected behavior

When targeting an entity, their UUID should normally autofill when trying to autocomplete certain commands such as /execute, /data, and /teleport. Following Patch #93, the UUID's would no longer autofill as they should, even when targeting an entity.

### Observed/Actual behavior

Following Patch #93, entity UUIDs would no longer autofill as they should, even when targeting an entity.
![image](https://user-images.githubusercontent.com/29575777/147396161-e807cff9-6792-49dd-b9f7-657b7d442933.png)
![image](https://user-images.githubusercontent.com/29575777/147396156-270d32f4-7067-4cc5-9793-b7016785588c.png)

### Steps/models to reproduce

Simply run any paper server Version #93 and up, target an entity such as an armor stand, and attempt to fill out a command that targets an entity such as /teleport or /execute as. Their UUID will not show up in the autofill list when it normally should.

### Plugin and Datapack List

This was tested and confirmed to occur on a Paper server with no active plugins or datapacks.

### Paper version

Paper Version that works normally:
This server is running Paper version git-Paper-92 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 264b11d)

Paper Versions with mentioned issue:
This server is running Paper version git-Paper-93 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 2cf6a57)
This server is running Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 464b171)\nYou are running the latest version

Also occurs in all versions in between

**Comment by Machine-Maker** [comment] 2021-12-26 00:47
Related to, but not a duplicate of, https://github.com/PaperMC/Paper/issues/7185

**Comment by molor** [comment] 2021-12-26 11:39
Have the same problem :c

**Closed as completed** 2021-12-30 07:11 UTC
Labels: type: bug, status: accepted
