### ISSUE TITLE
Server crashes almost immediately upon updating to 1.20.4

### ISSUE THREAD

**Issue by Budderman18** [PaperSpigot/Paper#10011] opened 2023-12-09 19:23 UTC
### Stack trace

org.spongepowered.configurate.serialize.SerializationException: [anticheat, anti-xray, hidden-blocks, 21] of type java.util.List<net.minecraft.world.level.block.Block>: Missing value in Registry[ResourceKey[minecraft:root / minecraft:block] (Stable)] with key minecraft:netherrite_block
	at io.papermc.paper.configuration.serializer.registry.RegistryValueSerializer.convertFromResourceKey(RegistryValueSerializer.java:26)
	at io.papermc.paper.configuration.serializer.registry.RegistryEntrySerializer.deserialize(RegistryEntrySerializer.java:42)
	at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:156)
	at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:121)
	at org.spongepowered.configurate.serialize.AbstractListChildSerializer.deserialize(AbstractListChildSerializer.java:61)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:76)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:56)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:230)
	at org.spongepowered.configurate.serialize.TypeSerializer.deserialize(TypeSerializer.java:96)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:76)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:56)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:230)
	at org.spongepowered.configurate.serialize.TypeSerializer.deserialize(TypeSerializer.java:96)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:76)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:56)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:230)
	at org.spongepowered.configurate.AbstractConfigurationNode.get0(AbstractConfigurationNode.java:203)
	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:161)
	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:521)
	at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:408)
	at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:174)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### Plugin and Datapack List

happens before plugins load, so this doesnt matter

### Paper version

can't even run /version, its build #319

**Comment by lynxplay** [comment] 2023-12-09 19:26
You have a spelling issue in your antixray config, it is
```diff
- minecraft:netherrite_block
+ minecraft:netherite_block
```

**Comment by lynxplay** [comment] 2023-12-09 19:32
Yea after a quick look, this failed quietly in previous versions and now properly breaks.
Closing this as works as intended.

**Closed as not planned by lynxplay** 2023-12-09 19:32 UTC
Labels: resolution: works as intended, version: 1.20.4
